section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "flrk_repair_order_bronze_DataDestination", IsNewTarget = false], Settings = [Kind = "Manual", AllowCreation = false, ColumnSettings = [Mappings = {[SourceColumnName = "repair_order_id", DestinationColumnName = "repair_order_id"], [SourceColumnName = "ro_task_id", DestinationColumnName = "ro_task_id"], [SourceColumnName = "task_labor_hourly_rate", DestinationColumnName = "task_labor_hourly_rate"], [SourceColumnName = "task_labor_hours", DestinationColumnName = "task_labor_hours"], [SourceColumnName = "task_labor_subtotal", DestinationColumnName = "task_labor_subtotal"], [SourceColumnName = "task_labor_tax_rate", DestinationColumnName = "task_labor_tax_rate"], [SourceColumnName = "task_labor_complaint", DestinationColumnName = "task_labor_complaint"], [SourceColumnName = "task_labor_cause_code", DestinationColumnName = "task_labor_cause_code"], [SourceColumnName = "task_labor_correction_code", DestinationColumnName = "task_labor_correction_code"], [SourceColumnName = "task_labor_system_code", DestinationColumnName = "task_labor_system_code"], [SourceColumnName = "task_labor_system_component_code", DestinationColumnName = "task_labor_system_component_code"], [SourceColumnName = "task_scheduled_maintenance_id", DestinationColumnName = "task_scheduled_maintenance_id"], [SourceColumnName = "task_issue_id", DestinationColumnName = "task_issue_id"], [SourceColumnName = "task_assigned_to", DestinationColumnName = "task_assigned_to"], [SourceColumnName = "task_added_datetime", DestinationColumnName = "task_added_datetime"]}], DynamicSchema = false, UpdateMethod = [Kind = "Append"], TypeSettings = [Kind = "Table"]]]}]
shared flrk_repair_order_bronze = let
  Source = Lakehouse.Contents(null){[workspaceId = "a6d2c31b-0b03-4c60-a258-c2664c56fe3d"]}[Data]{[lakehouseId = "f9a73da1-08e4-4f3d-a67f-74623bfde721"]}[Data],
  #"Navigation 1" = Source{[Id = "flrk_repair_order_bronze", ItemKind = "Table"]}[Data],
  #"Changed column type" = Table.TransformColumnTypes(#"Navigation 1", {{"id", Int64.Type}}),
  #"Renamed columns" = Table.RenameColumns(#"Changed column type", {{"id", "repair_order_id"}}),
  #"Removed columns" = Table.RemoveColumns(#"Renamed columns", {"group", "ro_group_hierarchy", "vin", "unit_number", "unit_type", "custom_asset_id", "vendor_name", "vendor_company_id", "vendor_city", "vendor_state", "vendor_province", "vendor_zip_code", "vendor_timezone", "customer_name", "customer_company_id", "odometer_miles", "engine_hours", "priority_code", "cost_center", "tag", "status", "created_by", "date_created", "date_started", "date_expected_finish", "date_finished", "date_invoiced", "date_invoice_paid", "po_number", "additional_charges", "tax_total", "credit_amount", "repair_orders.estimate", "grand_total", "paid_amount", "remit_to", "remit_to_company_id"}),
  #"Changed column type 1" = Table.TransformColumnTypes(#"Removed columns", {{"tasks.task_id", Int64.Type}}),
  #"Renamed columns 1" = Table.RenameColumns(#"Changed column type 1", {{"tasks.task_id", "task_id"}, {"tasks.labor_hourly_rate", "labor_hourly_rate"}}),
  #"Changed column type 2" = Table.TransformColumnTypes(#"Renamed columns 1", {{"labor_hourly_rate", type number}, {"tasks.labor_hours", type number}, {"tasks.labor_subtotal", type number}, {"tasks.labor_tax_rate", type number}}),
  #"Renamed columns 2" = Table.RenameColumns(#"Changed column type 2", {{"tasks.labor_hours", "labor_hours"}, {"tasks.labor_subtotal", "labor_subtotal"}, {"tasks.labor_tax_rate", "labor_tax_rate"}, {"tasks.labor_complaint", "labor_complaint"}, {"tasks.labor_cause_code", "labor_cause_code"}, {"tasks.labor_correction_code", "labor_correction_code"}, {"tasks.labor_system_code", "labor_system_code"}, {"tasks.labor_system_component_code", "labor_system_component_code"}, {"tasks.scheduled_maintenance_id", "scheduled_maintenance_id"}}),
  #"Changed column type 3" = Table.TransformColumnTypes(#"Renamed columns 2", {{"scheduled_maintenance_id", Int64.Type}}),
  #"Renamed columns 3" = Table.RenameColumns(#"Changed column type 3", {{"tasks.issue_id", "issue_id"}}),
  #"Changed column type 4" = Table.TransformColumnTypes(#"Renamed columns 3", {{"issue_id", Int64.Type}}),
  #"Renamed columns 4" = Table.RenameColumns(#"Changed column type 4", {{"tasks.assigned_to", "assigned_to"}, {"tasks.date_added", "task_added_date"}}),
  #"Changed column type 5" = Table.TransformColumnTypes(#"Renamed columns 4", {{"task_added_date", type datetime}}),
  #"Renamed columns 5" = Table.RenameColumns(#"Changed column type 5", {{"task_added_date", "task_added_datetime"}}),
  #"Removed columns 1" = Table.RemoveColumns(#"Renamed columns 5", {"notes.note_id", "notes.note", "notes.added_by", "notes.date_added", "tasks.parts.task_part_id", "tasks.parts.part_id", "tasks.parts.part_number", "tasks.parts.part_description", "tasks.parts.part_system_code", "tasks.parts.part_type", "tasks.parts.part_price", "tasks.parts.part_quantity", "tasks.parts.part_tax_rate", "tasks.parts.part_location", "tasks.parts.tire_brand", "tasks.parts.tire_product_line", "tasks.parts.tire_size", "tasks.parts.tire_type", "tasks.parts.date_added"}),
  #"Removed duplicates" = Table.Distinct(#"Removed columns 1"),
  #"Renamed columns 6" = Table.RenameColumns(#"Removed duplicates", {{"labor_hourly_rate", "task_labor_hourly_rate"}, {"labor_hours", "task_labor_hours"}, {"labor_subtotal", "task_labor_subtotal"}, {"labor_tax_rate", "task_labor_tax_rate"}, {"labor_complaint", "task_labor_complaint"}, {"labor_cause_code", "task_labor_cause_code"}, {"labor_correction_code", "task_labor_correction_code"}, {"labor_system_code", "task_labor_system_code"}, {"labor_system_component_code", "task_labor_system_component_code"}, {"scheduled_maintenance_id", "task_scheduled_maintenance_id"}, {"issue_id", "task_issue_id"}, {"assigned_to", "task_assigned_to"}, {"task_id", "ro_task_id"}})
in
  #"Renamed columns 6";
shared flrk_repair_order_bronze_DataDestination = let
  Pattern = Fabric.Warehouse([CreateNavigationProperties = false]),
  Navigation_1 = Pattern{[workspaceId = "a6d2c31b-0b03-4c60-a258-c2664c56fe3d"]}[Data],
  Navigation_2 = Navigation_1{[warehouseId = "f8578495-391e-4e7e-b791-4949397ba86f"]}[Data],
  TableNavigation = Navigation_2{[Schema = "silver", Item = "flrk_repair_order_task"]}[Data]
in
  TableNavigation;
