section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "VW_TRAILERS_DataDestination", IsNewTarget = false], Settings = [Kind = "Manual", AllowCreation = false, ColumnSettings = [Mappings = {[SourceColumnName = "TRTRLR", DestinationColumnName = "TRTRLR"], [SourceColumnName = "TROWNR", DestinationColumnName = "TROWNR"], [SourceColumnName = "TRCRED", DestinationColumnName = "TRCRED"], [SourceColumnName = "TRCRET", DestinationColumnName = "TRCRET"], [SourceColumnName = "TRCREI", DestinationColumnName = "TRCREI"], [SourceColumnName = "TRUPDD", DestinationColumnName = "TRUPDD"], [SourceColumnName = "TRUPDT", DestinationColumnName = "TRUPDT"], [SourceColumnName = "TRUPDI", DestinationColumnName = "TRUPDI"], [SourceColumnName = "TRCO", DestinationColumnName = "TRCO"], [SourceColumnName = "TRDV", DestinationColumnName = "TRDV"], [SourceColumnName = "TRTM", DestinationColumnName = "TRTM"], [SourceColumnName = "TRYEAR", DestinationColumnName = "TRYEAR"], [SourceColumnName = "TRMAKE", DestinationColumnName = "TRMAKE"], [SourceColumnName = "TRSER", DestinationColumnName = "TRSER"], [SourceColumnName = "TRMNPR", DestinationColumnName = "TRMNPR"], [SourceColumnName = "TRBAST", DestinationColumnName = "TRBAST"], [SourceColumnName = "TRNY", DestinationColumnName = "TRNY"], [SourceColumnName = "TRTYPE", DestinationColumnName = "TRTYPE"], [SourceColumnName = "TRTRST", DestinationColumnName = "TRTRST"], [SourceColumnName = "TRPDAT", DestinationColumnName = "TRPDAT"], [SourceColumnName = "TRARA", DestinationColumnName = "TRARA"], [SourceColumnName = "TRORD", DestinationColumnName = "TRORD"], [SourceColumnName = "TRDISP", DestinationColumnName = "TRDISP"], [SourceColumnName = "TRUNIT", DestinationColumnName = "TRUNIT"], [SourceColumnName = "TRDCTY", DestinationColumnName = "TRDCTY"], [SourceColumnName = "TRDST", DestinationColumnName = "TRDST"], [SourceColumnName = "TRETA", DestinationColumnName = "TRETA"], [SourceColumnName = "TRCCTY", DestinationColumnName = "TRCCTY"], [SourceColumnName = "TRCST", DestinationColumnName = "TRCST"], [SourceColumnName = "TRCDAT", DestinationColumnName = "TRCDAT"], [SourceColumnName = "TRMSG", DestinationColumnName = "TRMSG"], [SourceColumnName = "TRDLT", DestinationColumnName = "TRDLT"], [SourceColumnName = "TRFLET", DestinationColumnName = "TRFLET"], [SourceColumnName = "TRAXLE", DestinationColumnName = "TRAXLE"], [SourceColumnName = "TREMWT", DestinationColumnName = "TREMWT"], [SourceColumnName = "TRGRWT", DestinationColumnName = "TRGRWT"], [SourceColumnName = "TRHEIG", DestinationColumnName = "TRHEIG"], [SourceColumnName = "TRLENG", DestinationColumnName = "TRLENG"], [SourceColumnName = "TRCOST", DestinationColumnName = "TRCOST"], [SourceColumnName = "TRPRLD", DestinationColumnName = "TRPRLD"], [SourceColumnName = "TRCONT", DestinationColumnName = "TRCONT"], [SourceColumnName = "TRHOUR", DestinationColumnName = "TRHOUR"], [SourceColumnName = "TRHUB", DestinationColumnName = "TRHUB"], [SourceColumnName = "TRMULT", DestinationColumnName = "TRMULT"], [SourceColumnName = "TRWIDE", DestinationColumnName = "TRWIDE"], [SourceColumnName = "TRCUBE", DestinationColumnName = "TRCUBE"], [SourceColumnName = "TRIDIM", DestinationColumnName = "TRIDIM"], [SourceColumnName = "TRDDIM", DestinationColumnName = "TRDDIM"], [SourceColumnName = "TRTSIZ", DestinationColumnName = "TRTSIZ"], [SourceColumnName = "TRTTYP", DestinationColumnName = "TRTTYP"], [SourceColumnName = "TRMISC", DestinationColumnName = "TRMISC"], [SourceColumnName = "TRPERC", DestinationColumnName = "TRPERC"], [SourceColumnName = "TRLRAT", DestinationColumnName = "TRLRAT"], [SourceColumnName = "TRERAT", DestinationColumnName = "TRERAT"], [SourceColumnName = "TRLFLG", DestinationColumnName = "TRLFLG"], [SourceColumnName = "TRL_PL", DestinationColumnName = "TRL_PL"], [SourceColumnName = "TRLTMP", DestinationColumnName = "TRLTMP"], [SourceColumnName = "TRLCOD", DestinationColumnName = "TRLCOD"], [SourceColumnName = "TRCUST", DestinationColumnName = "TRCUST"], [SourceColumnName = "TRGATE", DestinationColumnName = "TRGATE"], [SourceColumnName = "TRTYP2", DestinationColumnName = "TRTYP2"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared VW_TRAILERS = let
  Source = DB2.Database("S10A3543.STEVENSTRANSPORT.COM:447", "S10A3543", [HierarchicalNavigation = true, Implementation = "Microsoft"]),
  #"Navigation 1" = Source{[Schema = "FABRIC"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Name = "VW_TRAILERS"]}[Data],
  #"Renamed columns" = Table.RenameColumns(#"Navigation 2", {{"TRCO#", "TRCO"}, {"TRDV#", "TRDV"}, {"TRTM#", "TRTM"}, {"TRORD#", "TRORD"}, {"TRL#PL", "TRL_PL"}})
in
  #"Renamed columns";
shared VW_TRAILERS_DataDestination = let
  Pattern = Lakehouse.Contents([CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "a6d2c31b-0b03-4c60-a258-c2664c56fe3d"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "f9a73da1-08e4-4f3d-a67f-74623bfde721"]}[Data],
  TableNavigation = Navigation_2{[Id = "ibmi_trailer_bronze", ItemKind = "Table"]}[Data]
in
  TableNavigation;
