table 'Bill-To Customers'
	lineageTag: e1c98fe6-23fb-444d-bb29-72c016a9e8b9

	column 'Customer Code'
		dataType: string
		lineageTag: 0a6ceb2e-b829-4f2b-9619-d1d98be0e74d
		summarizeBy: none
		sourceColumn: Customer Code

		annotation SummarizationSetBy = Automatic

	column 'City Code'
		dataType: string
		lineageTag: 69f511d1-6a13-420c-bd79-bcd6003a909e
		summarizeBy: none
		sourceColumn: Customer City Code

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 418b946d-cc04-4fe1-838d-20949ea6739d
		summarizeBy: none
		sourceColumn: Customer State

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: a49e1d64-563b-4ba3-9f3d-25d2cc875a15
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	partition 'Bill-To Customers' = m
		mode: import
		source =
				let
				    Source = Sql.Database("lofzv5bdxbxepf3ufbs6kug4du-eh6hum4723febkx4myauspbbvq.datawarehouse.fabric.microsoft.com", "data_central_wh"),
				    gold_dim_customer = Source{[Schema="gold",Item="dim_customer"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(gold_dim_customer,{{"customer_code", "Customer Code"}, {"cust_city_code", "Customer City Code"}, {"cust_area_code", "Customer State"}, {"cust_name", "Customer Name"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"cust_division_code", "is_deleted", "cust_address_line_1", "cust_address_line_2", "cust_address_city", "cust_address_state", "cust_address_zip", "cust_address_zip_extn", "bill_to_code", "bill_to_name", "cust_salesperson", "cust_shipper_code", "cust_shipper_area_code", "cust_shipper_phone", "cust_country", "controlling_shipper", "controlling_shipper_name", "is_allow_as_shipper", "is_allow_as_bill_to", "is_allow_as_load_at", "is_allow_as_consignee", "edi_profile_code", "cust_division_name", "commodity_code", "commodity_description", "pu_area_code", "pu_area_name", "last_activity_date"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

