[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "VW_SERVICE_EXCEPTIONS_DataDestination", IsNewTarget = true], Settings = [Kind = "Manual", AllowCreation = true, ColumnSettings = [Mappings = {[SourceColumnName = "SEORD", DestinationColumnName = "SEORD"], [SourceColumnName = "SESEQ", DestinationColumnName = "SESEQ"], [SourceColumnName = "SETYPE", DestinationColumnName = "SETYPE"], [SourceColumnName = "SEDISP", DestinationColumnName = "SEDISP"], [SourceColumnName = "SESTAT", DestinationColumnName = "SESTAT"], [SourceColumnName = "SEUNIT", DestinationColumnName = "SEUNIT"], [SourceColumnName = "SETRLR", DestinationColumnName = "SETRLR"], [SourceColumnName = "SEDRV1", DestinationColumnName = "SEDRV1"], [SourceColumnName = "SEDM", DestinationColumnName = "SEDM"], [SourceColumnName = "SEFM", DestinationColumnName = "SEFM"], [SourceColumnName = "SECSR", DestinationColumnName = "SECSR"], [SourceColumnName = "SESTP", DestinationColumnName = "SESTP"], [SourceColumnName = "SERPT", DestinationColumnName = "SERPT"], [SourceColumnName = "SESOCSR", DestinationColumnName = "SESOCSR"], [SourceColumnName = "SESODM", DestinationColumnName = "SESODM"], [SourceColumnName = "SERPCU", DestinationColumnName = "SERPCU"], [SourceColumnName = "SERPSH", DestinationColumnName = "SERPSH"], [SourceColumnName = "SERPLD", DestinationColumnName = "SERPLD"], [SourceColumnName = "SERPCN", DestinationColumnName = "SERPCN"], [SourceColumnName = "SERPDR", DestinationColumnName = "SERPDR"], [SourceColumnName = "SERPEQ", DestinationColumnName = "SERPEQ"], [SourceColumnName = "SERPWE", DestinationColumnName = "SERPWE"], [SourceColumnName = "SERPSL", DestinationColumnName = "SERPSL"], [SourceColumnName = "SERPCS", DestinationColumnName = "SERPCS"], [SourceColumnName = "SERPPL", DestinationColumnName = "SERPPL"], [SourceColumnName = "SERPDM", DestinationColumnName = "SERPDM"], [SourceColumnName = "SERPBR", DestinationColumnName = "SERPBR"], [SourceColumnName = "SEDATE", DestinationColumnName = "SEDATE"], [SourceColumnName = "SETIME", DestinationColumnName = "SETIME"], [SourceColumnName = "SECRED", DestinationColumnName = "SECRED"], [SourceColumnName = "SECRET", DestinationColumnName = "SECRET"], [SourceColumnName = "SECREI", DestinationColumnName = "SECREI"], [SourceColumnName = "SEPGM", DestinationColumnName = "SEPGM"], [SourceColumnName = "SEUPDD", DestinationColumnName = "SEUPDD"], [SourceColumnName = "SEUPDT", DestinationColumnName = "SEUPDT"], [SourceColumnName = "SEUPDI", DestinationColumnName = "SEUPDI"], [SourceColumnName = "SERPNC", DestinationColumnName = "SERPNC"], [SourceColumnName = "SERPRL", DestinationColumnName = "SERPRL"], [SourceColumnName = "SESOUSR", DestinationColumnName = "SESOUSR"], [SourceColumnName = "SEPLAN", DestinationColumnName = "SEPLAN"], [SourceColumnName = "SESEV", DestinationColumnName = "SESEV"], [SourceColumnName = "SEACRSN", DestinationColumnName = "SEACRSN"], [SourceColumnName = "SERPTDR", DestinationColumnName = "SERPTDR"], [SourceColumnName = "SESESTAT", DestinationColumnName = "SESESTAT"], [SourceColumnName = "SERM", DestinationColumnName = "SERM"], [SourceColumnName = "SERPRC", DestinationColumnName = "SERPRC"], [SourceColumnName = "SEREGN", DestinationColumnName = "SEREGN"]}], DynamicSchema = true, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared VW_SERVICE_EXCEPTIONS = let
  Source = DB2.Database("S10A3543.STEVENSTRANSPORT.COM:447", "S10A3543", [HierarchicalNavigation = true, Implementation = "Microsoft"]),
  #"Navigation 1" = Source{[Schema = "FABRIC"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Name = "VW_SERVICE_EXCEPTIONS"]}[Data],
  #"Renamed columns" = Table.RenameColumns(#"Navigation 2", {{"SEORD#", "SEORD"}, {"SESEQ#", "SESEQ"}, {"SESTP#", "SESTP"}}),
  #"Changed column type" = Table.TransformColumnTypes(#"Renamed columns", {{"SESEQ", Int64.Type}, {"SESTP", Int64.Type}, {"SEDATE", Int64.Type}, {"SETIME", Int64.Type}, {"SECRED", Int64.Type}, {"SECRET", Int64.Type}, {"SEUPDD", Int64.Type}, {"SEUPDT", Int64.Type}})
in
  #"Changed column type";
shared VW_SERVICE_EXCEPTIONS_DataDestination = let
  Pattern = Lakehouse.Contents([CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "a6d2c31b-0b03-4c60-a258-c2664c56fe3d"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "f9a73da1-08e4-4f3d-a67f-74623bfde721"]}[Data],
  TableNavigation = Navigation_2{[Id = "ibmi_service_exceptions_bronze", ItemKind = "Table"]}?[Data]?
in
  TableNavigation;
