section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "VW_PAID_LOADS_DataDestination", IsNewTarget = false], Settings = [Kind = "Manual", AllowCreation = false, ColumnSettings = [Mappings = {[SourceColumnName = "PAIDDATE", DestinationColumnName = "PAIDDATE"], [SourceColumnName = "ORDER_1", DestinationColumnName = "ORDER_1"], [SourceColumnName = "CUNAME", DestinationColumnName = "CUNAME"], [SourceColumnName = "CINAMEX", DestinationColumnName = "CINAMEX"], [SourceColumnName = "STATE", DestinationColumnName = "STATE"], [SourceColumnName = "OROSNM", DestinationColumnName = "OROSNM"], [SourceColumnName = "OROST", DestinationColumnName = "OROST"], [SourceColumnName = "ORDSNM", DestinationColumnName = "ORDSNM"], [SourceColumnName = "ORDST", DestinationColumnName = "ORDST"], [SourceColumnName = "ORPDATG", DestinationColumnName = "ORPDATG"], [SourceColumnName = "ORDDATG", DestinationColumnName = "ORDDATG"], [SourceColumnName = "EMILES", DestinationColumnName = "EMILES"], [SourceColumnName = "ORMILE", DestinationColumnName = "ORMILE"], [SourceColumnName = "EMPNMILE", DestinationColumnName = "EMPNMILE"], [SourceColumnName = "HUBMILES", DestinationColumnName = "HUBMILES"], [SourceColumnName = "HUBMMILE", DestinationColumnName = "HUBMMILE"], [SourceColumnName = "ORPREQ", DestinationColumnName = "ORPREQ"], [SourceColumnName = "ORSTP", DestinationColumnName = "ORSTP"], [SourceColumnName = "TOTALBILLE", DestinationColumnName = "TOTALBILLE"], [SourceColumnName = "LINEHAULX", DestinationColumnName = "LINEHAULX"], [SourceColumnName = "FUELSURCHA", DestinationColumnName = "FUELSURCHA"], [SourceColumnName = "UNLOADINGX", DestinationColumnName = "UNLOADINGX"], [SourceColumnName = "PALLETCHAR", DestinationColumnName = "PALLETCHAR"], [SourceColumnName = "OTHERCHARG", DestinationColumnName = "OTHERCHARG"], [SourceColumnName = "MEXICOCHAR", DestinationColumnName = "MEXICOCHAR"], [SourceColumnName = "STOPOFFCHA", DestinationColumnName = "STOPOFFCHA"], [SourceColumnName = "DETENTIONX", DestinationColumnName = "DETENTIONX"], [SourceColumnName = "DEADHEADX", DestinationColumnName = "DEADHEADX"], [SourceColumnName = "DHAMT1", DestinationColumnName = "DHAMT1"], [SourceColumnName = "DHAMT2", DestinationColumnName = "DHAMT2"], [SourceColumnName = "MPH2", DestinationColumnName = "MPH2"], [SourceColumnName = "ORARA", DestinationColumnName = "ORARA"], [SourceColumnName = "ORINAR", DestinationColumnName = "ORINAR"], [SourceColumnName = "CUSLMN", DestinationColumnName = "CUSLMN"], [SourceColumnName = "D2DM", DestinationColumnName = "D2DM"], [SourceColumnName = "D2FM", DestinationColumnName = "D2FM"], [SourceColumnName = "D2UNIT", DestinationColumnName = "D2UNIT"], [SourceColumnName = "RPLM", DestinationColumnName = "RPLM"], [SourceColumnName = "RPTM", DestinationColumnName = "RPTM"], [SourceColumnName = "RPNM", DestinationColumnName = "RPNM"], [SourceColumnName = "NETFSC", DestinationColumnName = "NETFSC"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared VW_PAID_LOADS = let
  Source = DB2.Database("S10A3543.STEVENSTRANSPORT.COM:447", "S10A3543", [HierarchicalNavigation = true, Implementation = "Microsoft"]),
  #"Navigation 1" = Source{[Schema = "FABRIC"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Name = "VW_PAID_LOADS"]}[Data],
  #"Renamed columns" = Table.RenameColumns(#"Navigation 2", {{"ORDER#1", "ORDER_1"}, {"ORSTP#", "ORSTP"}})
in
  #"Renamed columns";
shared VW_PAID_LOADS_DataDestination = let
  Pattern = Lakehouse.Contents([CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "a6d2c31b-0b03-4c60-a258-c2664c56fe3d"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "f9a73da1-08e4-4f3d-a67f-74623bfde721"]}[Data],
  TableNavigation = Navigation_2{[Id = "ibmi_paid_load_bronze", ItemKind = "Table"]}[Data]
in
  TableNavigation;
