[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "VW_EDI_ORDER_HISTORY_DataDestination", IsNewTarget = true], Settings = [Kind = "Manual", AllowCreation = true, ColumnSettings = [Mappings = {[SourceColumnName = "EOARA", DestinationColumnName = "EOARA"], [SourceColumnName = "EOODR", DestinationColumnName = "EOODR"], [SourceColumnName = "EOSTAT", DestinationColumnName = "EOSTAT"], [SourceColumnName = "EODATE", DestinationColumnName = "EODATE"], [SourceColumnName = "EOTIME", DestinationColumnName = "EOTIME"], [SourceColumnName = "EOCUST", DestinationColumnName = "EOCUST"], [SourceColumnName = "EOCONS", DestinationColumnName = "EOCONS"], [SourceColumnName = "EOBILL", DestinationColumnName = "EOBILL"], [SourceColumnName = "EOLDAT", DestinationColumnName = "EOLDAT"], [SourceColumnName = "EOPDAT", DestinationColumnName = "EOPDAT"], [SourceColumnName = "EOPTIM", DestinationColumnName = "EOPTIM"], [SourceColumnName = "EORPIK", DestinationColumnName = "EORPIK"], [SourceColumnName = "EODDAT", DestinationColumnName = "EODDAT"], [SourceColumnName = "EODTIM", DestinationColumnName = "EODTIM"], [SourceColumnName = "EORDEL", DestinationColumnName = "EORDEL"], [SourceColumnName = "EOCOMC", DestinationColumnName = "EOCOMC"], [SourceColumnName = "EOCOMD", DestinationColumnName = "EOCOMD"], [SourceColumnName = "EOINIT", DestinationColumnName = "EOINIT"], [SourceColumnName = "EOCAC", DestinationColumnName = "EOCAC"], [SourceColumnName = "EOCPHN", DestinationColumnName = "EOCPHN"], [SourceColumnName = "EORAC", DestinationColumnName = "EORAC"], [SourceColumnName = "EORPHN", DestinationColumnName = "EORPHN"], [SourceColumnName = "EOCTIM", DestinationColumnName = "EOCTIM"], [SourceColumnName = "EOWGT", DestinationColumnName = "EOWGT"], [SourceColumnName = "EOTWGT", DestinationColumnName = "EOTWGT"], [SourceColumnName = "EOHOOK", DestinationColumnName = "EOHOOK"], [SourceColumnName = "EOPLLT", DestinationColumnName = "EOPLLT"], [SourceColumnName = "EOBAMT", DestinationColumnName = "EOBAMT"], [SourceColumnName = "EOTAMT", DestinationColumnName = "EOTAMT"], [SourceColumnName = "EOOCTY", DestinationColumnName = "EOOCTY"], [SourceColumnName = "EOOST", DestinationColumnName = "EOOST"], [SourceColumnName = "EOOZN", DestinationColumnName = "EOOZN"], [SourceColumnName = "EOORG", DestinationColumnName = "EOORG"], [SourceColumnName = "EOOBEA", DestinationColumnName = "EOOBEA"], [SourceColumnName = "EOOGU", DestinationColumnName = "EOOGU"], [SourceColumnName = "EOOSNM", DestinationColumnName = "EOOSNM"], [SourceColumnName = "EODCTY", DestinationColumnName = "EODCTY"], [SourceColumnName = "EODST", DestinationColumnName = "EODST"], [SourceColumnName = "EODZN", DestinationColumnName = "EODZN"], [SourceColumnName = "EODRG", DestinationColumnName = "EODRG"], [SourceColumnName = "EODBEA", DestinationColumnName = "EODBEA"], [SourceColumnName = "EODGU", DestinationColumnName = "EODGU"], [SourceColumnName = "EODSNM", DestinationColumnName = "EODSNM"], [SourceColumnName = "EOMILE", DestinationColumnName = "EOMILE"], [SourceColumnName = "EOSTP#", DestinationColumnName = "EOSTP#"], [SourceColumnName = "EOLD#", DestinationColumnName = "EOLD#"], [SourceColumnName = "EOPDRV", DestinationColumnName = "EOPDRV"], [SourceColumnName = "EOTRLR", DestinationColumnName = "EOTRLR"], [SourceColumnName = "EOESTR", DestinationColumnName = "EOESTR"], [SourceColumnName = "EONWPK", DestinationColumnName = "EONWPK"], [SourceColumnName = "EOINAR", DestinationColumnName = "EOINAR"], [SourceColumnName = "EOTARF", DestinationColumnName = "EOTARF"], [SourceColumnName = "EOITEM", DestinationColumnName = "EOITEM"], [SourceColumnName = "EOLINE", DestinationColumnName = "EOLINE"], [SourceColumnName = "EOCSH", DestinationColumnName = "EOCSH"], [SourceColumnName = "EOCNS", DestinationColumnName = "EOCNS"], [SourceColumnName = "EOORBY", DestinationColumnName = "EOORBY"], [SourceColumnName = "EOPIEC", DestinationColumnName = "EOPIEC"], [SourceColumnName = "EOPORC", DestinationColumnName = "EOPORC"], [SourceColumnName = "EOMAN", DestinationColumnName = "EOMAN"], [SourceColumnName = "EOCUBE", DestinationColumnName = "EOCUBE"], [SourceColumnName = "EOSPEC", DestinationColumnName = "EOSPEC"], [SourceColumnName = "EOAPDT", DestinationColumnName = "EOAPDT"], [SourceColumnName = "EOAPTM", DestinationColumnName = "EOAPTM"], [SourceColumnName = "EOAPNM", DestinationColumnName = "EOAPNM"], [SourceColumnName = "EOAPIN", DestinationColumnName = "EOAPIN"], [SourceColumnName = "EOADDT", DestinationColumnName = "EOADDT"], [SourceColumnName = "EOADTM", DestinationColumnName = "EOADTM"], [SourceColumnName = "EOADNM", DestinationColumnName = "EOADNM"], [SourceColumnName = "EOADIN", DestinationColumnName = "EOADIN"], [SourceColumnName = "EOPREQ", DestinationColumnName = "EOPREQ"], [SourceColumnName = "EOCNSH", DestinationColumnName = "EOCNSH"], [SourceColumnName = "EOPUSH", DestinationColumnName = "EOPUSH"], [SourceColumnName = "EOARR", DestinationColumnName = "EOARR"], [SourceColumnName = "EOCPIC", DestinationColumnName = "EOCPIC"], [SourceColumnName = "EOCWGT", DestinationColumnName = "EOCWGT"], [SourceColumnName = "EOSHDT", DestinationColumnName = "EOSHDT"], [SourceColumnName = "EOSHTM", DestinationColumnName = "EOSHTM"], [SourceColumnName = "EOTMPH", DestinationColumnName = "EOTMPH"], [SourceColumnName = "EOTMPL", DestinationColumnName = "EOTMPL"], [SourceColumnName = "EOEQTY", DestinationColumnName = "EOEQTY"], [SourceColumnName = "EOCO", DestinationColumnName = "EOCO"], [SourceColumnName = "EODV", DestinationColumnName = "EODV"], [SourceColumnName = "EOTM", DestinationColumnName = "EOTM"], [SourceColumnName = "EOSEL1", DestinationColumnName = "EOSEL1"], [SourceColumnName = "EOSEL2", DestinationColumnName = "EOSEL2"], [SourceColumnName = "EOHAZM", DestinationColumnName = "EOHAZM"], [SourceColumnName = "EODLD", DestinationColumnName = "EODLD"], [SourceColumnName = "EODULD", DestinationColumnName = "EODULD"], [SourceColumnName = "EOBBOC", DestinationColumnName = "EOBBOC"], [SourceColumnName = "EOJIT", DestinationColumnName = "EOJIT"], [SourceColumnName = "EOAGNT", DestinationColumnName = "EOAGNT"], [SourceColumnName = "EOTNDT", DestinationColumnName = "EOTNDT"], [SourceColumnName = "EOTNTM", DestinationColumnName = "EOTNTM"], [SourceColumnName = "EORSTM", DestinationColumnName = "EORSTM"], [SourceColumnName = "EOEDCD", DestinationColumnName = "EOEDCD"], [SourceColumnName = "EOUSER", DestinationColumnName = "EOUSER"]}], DynamicSchema = true, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared VW_EDI_ORDER_HISTORY = let
  Source = DB2.Database("S10A3543.STEVENSTRANSPORT.COM:447", "S10A3543", [HierarchicalNavigation = true, Implementation = "Microsoft"]),
  #"Navigation 1" = Source{[Schema = "FABRIC"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Name = "VW_EDI_ORDER_HISTORY"]}[Data],
  #"Renamed columns" = Table.RenameColumns(#"Navigation 2", {{"EOODR#", "EOODR"}, {"EOCSH#", "EOCSH"}, {"EOCNS#", "EOCNS"}, {"EOMAN#", "EOMAN"}, {"EOCO#", "EOCO"}, {"EODV#", "EODV"}, {"EOTM#", "EOTM"}}),
  #"Changed column type" = Table.TransformColumnTypes(#"Renamed columns", {{"EODATE", Int64.Type}, {"EOPDAT", Int64.Type}, {"EODDAT", Int64.Type}, {"EOAPDT", Int64.Type}, {"EOADDT", Int64.Type}, {"EOSHDT", Int64.Type}, {"EOTNDT", Int64.Type}})
in
  #"Changed column type";
shared VW_EDI_ORDER_HISTORY_DataDestination = let
  Pattern = Lakehouse.Contents([HierarchicalNavigation = null, CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "a6d2c31b-0b03-4c60-a258-c2664c56fe3d"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "f9a73da1-08e4-4f3d-a67f-74623bfde721"]}[Data],
  TableNavigation = Navigation_2{[Id = "ibmi_edi_order_history_bronze", ItemKind = "Table"]}?[Data]?
in
  TableNavigation;
