[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "VW_PLSC_PLTMHBDP_DataDestination", IsNewTarget = false], Settings = [Kind = "Manual", AllowCreation = false, ColumnSettings = [Mappings = {[SourceColumnName = "PLTHTRUCK", DestinationColumnName = "PLTHTRUCK"], [SourceColumnName = "PLTHHBID", DestinationColumnName = "PLTHHBID"], [SourceColumnName = "PLTHTYPE", DestinationColumnName = "PLTHTYPE"], [SourceColumnName = "PLTHRECV", DestinationColumnName = "PLTHRECV"], [SourceColumnName = "PLTHLOGA", DestinationColumnName = "PLTHLOGA"], [SourceColumnName = "PLTHSPEED", DestinationColumnName = "PLTHSPEED"], [SourceColumnName = "PLTHODO", DestinationColumnName = "PLTHODO"], [SourceColumnName = "PLTHODOJ", DestinationColumnName = "PLTHODOJ"], [SourceColumnName = "PLTHHEAD", DestinationColumnName = "PLTHHEAD"], [SourceColumnName = "PLTHIGNS", DestinationColumnName = "PLTHIGNS"], [SourceColumnName = "PLTHRPM", DestinationColumnName = "PLTHRPM"], [SourceColumnName = "PLTHENGH", DestinationColumnName = "PLTHENGH"], [SourceColumnName = "PLTHENGHJ", DestinationColumnName = "PLTHENGHJ"], [SourceColumnName = "PLTHWINM", DestinationColumnName = "PLTHWINM"], [SourceColumnName = "PLTHACU", DestinationColumnName = "PLTHACU"], [SourceColumnName = "PLTHSAT", DestinationColumnName = "PLTHSAT"], [SourceColumnName = "PLTHGPSV", DestinationColumnName = "PLTHGPSV"], [SourceColumnName = "PLTHHDOP", DestinationColumnName = "PLTHHDOP"], [SourceColumnName = "PLTHFUEL", DestinationColumnName = "PLTHFUEL"], [SourceColumnName = "PLTHFUELU", DestinationColumnName = "PLTHFUELU"], [SourceColumnName = "PLTHLAT", DestinationColumnName = "PLTHLAT"], [SourceColumnName = "PLTHLON", DestinationColumnName = "PLTHLON"], [SourceColumnName = "PLTHLOCD", DestinationColumnName = "PLTHLOCD"], [SourceColumnName = "PLTHRPD", DestinationColumnName = "PLTHRPD"], [SourceColumnName = "PLTHRUM", DestinationColumnName = "PLTHRUM"], [SourceColumnName = "PLTHRDIR", DestinationColumnName = "PLTHRDIR"], [SourceColumnName = "PLTHRCITY", DestinationColumnName = "PLTHRCITY"], [SourceColumnName = "PLTHRSTATE", DestinationColumnName = "PLTHRSTATE"], [SourceColumnName = "PLTHRCUNTR", DestinationColumnName = "PLTHRCUNTR"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared VW_PLSC_PLTMHBDP = let
  Source = DB2.Database("S10A3543.STEVENSTRANSPORT.COM:447", "S10A3543", [HierarchicalNavigation = true, Implementation = "Microsoft"]),
  #"Navigation 1" = Source{[Schema = "FABRIC"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Name = "VW_PLSC_PLTMHBDP"]}[Data],
  #"Trimmed text" = Table.TransformColumns(#"Navigation 2", {{"PLTHTRUCK", each Text.Trim(_), type text}, {"PLTHTYPE", each Text.Trim(_), type text}, {"PLTHLOGA", each Text.Trim(_), type text}, {"PLTHODOJ", each Text.Trim(_), type text}, {"PLTHIGNS", each Text.Trim(_), type text}, {"PLTHENGHJ", each Text.Trim(_), type text}, {"PLTHWINM", each Text.Trim(_), type text}, {"PLTHGPSV", each Text.Trim(_), type text}, {"PLTHHDOP", each Text.Trim(_), type text}, {"PLTHLOCD", each Text.Trim(_), type text}, {"PLTHRUM", each Text.Trim(_), type text}, {"PLTHRDIR", each Text.Trim(_), type text}, {"PLTHRCITY", each Text.Trim(_), type text}, {"PLTHRSTATE", each Text.Trim(_), type text}, {"PLTHRCUNTR", each Text.Trim(_), type text}})
in
  #"Trimmed text";
shared VW_PLSC_PLTMHBDP_DataDestination = let
  Pattern = Lakehouse.Contents([HierarchicalNavigation = null, CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "a6d2c31b-0b03-4c60-a258-c2664c56fe3d"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "f9a73da1-08e4-4f3d-a67f-74623bfde721"]}[Data],
  TableNavigation = Navigation_2{[Id = "PLSC_INCR_PLTMHBDP", ItemKind = "Table"]}[Data]
in
  TableNavigation;
