section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "VW_CITIES_DataDestination", IsNewTarget = false], Settings = [Kind = "Manual", AllowCreation = false, ColumnSettings = [Mappings = {[SourceColumnName = "CIST", DestinationColumnName = "CIST"], [SourceColumnName = "CICTY", DestinationColumnName = "CICTY"], [SourceColumnName = "CIRCD", DestinationColumnName = "CIRCD"], [SourceColumnName = "CICOUN", DestinationColumnName = "CICOUN"], [SourceColumnName = "CILATD", DestinationColumnName = "CILATD"], [SourceColumnName = "CILNGD", DestinationColumnName = "CILNGD"], [SourceColumnName = "CICOMZ", DestinationColumnName = "CICOMZ"], [SourceColumnName = "CICNTY", DestinationColumnName = "CICNTY"], [SourceColumnName = "CIBEA", DestinationColumnName = "CIBEA"], [SourceColumnName = "CIRGU", DestinationColumnName = "CIRGU"], [SourceColumnName = "CISMSA", DestinationColumnName = "CISMSA"], [SourceColumnName = "CIZIP1", DestinationColumnName = "CIZIP1"], [SourceColumnName = "CIZIP2", DestinationColumnName = "CIZIP2"], [SourceColumnName = "CISPLC", DestinationColumnName = "CISPLC"], [SourceColumnName = "CIAREA", DestinationColumnName = "CIAREA"], [SourceColumnName = "CITERR", DestinationColumnName = "CITERR"], [SourceColumnName = "CITIME", DestinationColumnName = "CITIME"], [SourceColumnName = "CISAME", DestinationColumnName = "CISAME"], [SourceColumnName = "CIHZON", DestinationColumnName = "CIHZON"], [SourceColumnName = "CIDAY", DestinationColumnName = "CIDAY"], [SourceColumnName = "CIHHMG", DestinationColumnName = "CIHHMG"], [SourceColumnName = "CIBIGC", DestinationColumnName = "CIBIGC"], [SourceColumnName = "CIDUPL", DestinationColumnName = "CIDUPL"], [SourceColumnName = "CINEAR", DestinationColumnName = "CINEAR"], [SourceColumnName = "CIDIRN", DestinationColumnName = "CIDIRN"], [SourceColumnName = "CIDISN", DestinationColumnName = "CIDISN"], [SourceColumnName = "CISTIN", DestinationColumnName = "CISTIN"], [SourceColumnName = "CICOIN", DestinationColumnName = "CICOIN"], [SourceColumnName = "CISIZE", DestinationColumnName = "CISIZE"], [SourceColumnName = "CILEVL", DestinationColumnName = "CILEVL"], [SourceColumnName = "CIPOPE", DestinationColumnName = "CIPOPE"], [SourceColumnName = "CIPOPA", DestinationColumnName = "CIPOPA"], [SourceColumnName = "CINAME", DestinationColumnName = "CINAME"], [SourceColumnName = "CISHNM", DestinationColumnName = "CISHNM"], [SourceColumnName = "CILAT", DestinationColumnName = "CILAT"], [SourceColumnName = "CILONG", DestinationColumnName = "CILONG"], [SourceColumnName = "CILSTD", DestinationColumnName = "CILSTD"], [SourceColumnName = "CILSTT", DestinationColumnName = "CILSTT"], [SourceColumnName = "CILSTI", DestinationColumnName = "CILSTI"], [SourceColumnName = "CICO1Z", DestinationColumnName = "CICO1Z"], [SourceColumnName = "CICO1T", DestinationColumnName = "CICO1T"], [SourceColumnName = "CICO2Z", DestinationColumnName = "CICO2Z"], [SourceColumnName = "CICO2T", DestinationColumnName = "CICO2T"], [SourceColumnName = "CICQUL", DestinationColumnName = "CICQUL"], [SourceColumnName = "CICABR", DestinationColumnName = "CICABR"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared VW_CITIES = let
  Source = DB2.Database("S10A3543.STEVENSTRANSPORT.COM:447", "S10A3543", [HierarchicalNavigation = true, Implementation = "Microsoft"]),
  #"Navigation 1" = Source{[Schema = "FABRIC"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Name = "VW_CITIES"]}[Data],
  #"Renamed columns" = Table.RenameColumns(#"Navigation 2", {{"CIRCD#", "CIRCD"}})
in
  #"Renamed columns";
shared VW_CITIES_DataDestination = let
  Pattern = Lakehouse.Contents([CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "a6d2c31b-0b03-4c60-a258-c2664c56fe3d"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "f9a73da1-08e4-4f3d-a67f-74623bfde721"]}[Data],
  TableNavigation = Navigation_2{[Id = "ibmi_city_master_bronze", ItemKind = "Table"]}[Data]
in
  TableNavigation;
