table LoadFact
	lineageTag: 64a71bfb-db8e-4311-9f08-b2407d81e9ac

	measure LoadMiles = sum(LoadFact[load_miles_total])
		lineageTag: c4ca79d5-9e0e-422f-be26-11605cf73b6f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure WageRatePerRevenueMile = [GrossWageAmount]/[LoadMiles]
		lineageTag: 31c5b328-e761-4af8-8017-bb605e873116

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalAlerts = DISTINCTCOUNT ( DriverAlerts[alert_id])
		formatString: 0
		lineageTag: fa24c4c3-cf52-46cd-834b-b28758e0a727

		changedProperty = IsHidden

	column load_origin_area_code
		dataType: string
		lineageTag: 7effcea3-7b34-4fd0-b1c2-4bf86b876c5f
		summarizeBy: none
		sourceColumn: load_origin_area_code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column load_load_number
		dataType: string
		lineageTag: deb41321-5ac9-473f-b08a-0ae11b82bd67
		summarizeBy: none
		sourceColumn: load_load_number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column load_dispatch
		dataType: string
		lineageTag: 6c5370f0-e778-4c64-aba7-189b32ad4020
		summarizeBy: none
		sourceColumn: load_dispatch

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column load_status
		dataType: string
		lineageTag: 4e02f4ba-c486-47ff-bd4f-0e47e163ff9e
		summarizeBy: none
		sourceColumn: load_status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column load_dispatch_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 05cca3e0-968b-428b-b140-c874d9d2f815
		summarizeBy: none
		sourceColumn: load_dispatch_date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column load_dispatch_time
		dataType: string
		lineageTag: ccbdef73-ca5e-49f9-85c0-770129ec0681
		summarizeBy: none
		sourceColumn: load_dispatch_time

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column load_truck_number
		dataType: string
		lineageTag: c316a400-ea90-431a-97c5-a4e72d34dc0c
		summarizeBy: none
		sourceColumn: load_truck_number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column load_trailer_number
		dataType: string
		lineageTag: e3bb63ee-87aa-492d-af69-ca7a8ac91037
		summarizeBy: none
		sourceColumn: load_trailer_number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column load_route_line_codes
		dataType: string
		lineageTag: 1d7d3517-f0c1-43f2-8e4b-ebae7031ea0e
		summarizeBy: none
		sourceColumn: load_route_line_codes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column load_route_status
		dataType: string
		lineageTag: 9fe007d9-120a-4179-8e64-4d38e99c7985
		summarizeBy: none
		sourceColumn: load_route_status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column load_mile_flag
		dataType: string
		lineageTag: 139e20ec-8bd2-4031-bcc8-a070718aace2
		summarizeBy: none
		sourceColumn: load_mile_flag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column load_initials
		dataType: string
		lineageTag: 42f997b9-37e3-4ecf-a826-3a5299db2c81
		summarizeBy: none
		sourceColumn: load_initials

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column load_destination_area_code
		dataType: string
		lineageTag: d85830d3-06a0-40ab-b9e8-3cafb4bf8b53
		summarizeBy: none
		sourceColumn: load_destination_area_code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column load_route_line_extension
		dataType: string
		lineageTag: dee4fa2f-c66a-4e83-8741-ac032b0971f8
		summarizeBy: none
		sourceColumn: load_route_line_extension

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column load_dispatch_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 3d4f9fbb-0954-402a-b4e1-401f8fec7868
		summarizeBy: none
		sourceColumn: load_dispatch_end_date

		variation Variation
			isDefault
			relationship: d23dd774-11d8-4d6d-86b5-2303801b17c2
			defaultHierarchy: LocalDateTable_2da06a7a-c960-47f9-af38-7fd045b198c9.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column load_dispatch_end_time
		dataType: string
		lineageTag: 2d04fb11-9ad7-4df7-87a0-caf20ed2bd36
		summarizeBy: none
		sourceColumn: load_dispatch_end_time

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column load_multiple_trailers_on_dispatch
		dataType: string
		lineageTag: 20f1de40-7a8e-4019-85f0-73ccba159f86
		summarizeBy: none
		sourceColumn: load_multiple_trailers_on_dispatch

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column load_settlement_flag
		dataType: string
		lineageTag: 9f2c3950-1349-4a49-8e38-fe5006de4f4b
		summarizeBy: none
		sourceColumn: load_settlement_flag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column load_payroll_approval_flag
		dataType: string
		lineageTag: 55b8d6ab-2a54-4dc3-96b9-698f107b12d5
		summarizeBy: none
		sourceColumn: load_payroll_approval_flag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column load_truck_dmol_code
		dataType: string
		lineageTag: d80a49c1-8e05-4eaf-8c52-119f8c5dd763
		summarizeBy: none
		sourceColumn: load_truck_dmol_code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column load_truck_dm_code
		dataType: string
		lineageTag: 757c0970-c511-4433-961a-55ddce486a64
		summarizeBy: none
		sourceColumn: load_truck_dm_code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column load_driver_dmol_code
		dataType: string
		lineageTag: f915f403-f1e9-43b3-ab96-f1f659115a5c
		summarizeBy: none
		sourceColumn: load_driver_dmol_code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column load_driver_dm_code
		dataType: string
		lineageTag: 074891d3-0298-4883-96f1-4344527fc55e
		summarizeBy: none
		sourceColumn: load_driver_dm_code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column load_trip_jacket_received_flag
		dataType: string
		lineageTag: 987ab8a9-c311-4494-82b3-ff90ff2eebc7
		summarizeBy: none
		sourceColumn: load_trip_jacket_received_flag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column load_trip_jacket_received_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 62af5876-db74-4f65-a491-bbac172ce82f
		summarizeBy: none
		sourceColumn: load_trip_jacket_received_date

		variation Variation
			isDefault
			relationship: be4dcc0b-7f06-4dc3-bc36-60cdd389b764
			defaultHierarchy: LocalDateTable_f7a04461-84ad-4fd5-86d2-fe58b5969839.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column load_miles_hub_start
		dataType: double
		lineageTag: 6ae35bc1-e861-4c8b-bc03-208e1df82c25
		summarizeBy: sum
		sourceColumn: load_miles_hub_start

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column load_miles_hub_end
		dataType: double
		lineageTag: 7fae4b1b-051e-4f23-bd32-b064915d88f0
		summarizeBy: sum
		sourceColumn: load_miles_hub_end

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column load_unit_division_code
		dataType: string
		lineageTag: a0d10ab0-d346-4303-bb13-a7f294469350
		summarizeBy: none
		sourceColumn: load_unit_division_code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column load_team_status_code
		dataType: string
		lineageTag: adb71917-2c84-45f1-a8f7-84aa7032c9b0
		summarizeBy: none
		sourceColumn: load_team_status_code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column load_trainer_team_code
		dataType: string
		lineageTag: bbab6ff0-a84e-42a6-af62-339970e7bf62
		summarizeBy: none
		sourceColumn: load_trainer_team_code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column is_deleted
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a6bdcee7-c9b8-4326-a2b7-39c306e26a7b
		summarizeBy: none
		sourceColumn: is_deleted

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column load_seat_1_driver_code
		dataType: string
		lineageTag: 3d38cc7a-7a53-4f47-8727-1ad0e8416ca4
		summarizeBy: none
		sourceColumn: load_seat_1_driver_code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column load_seat_2_driver_code
		dataType: string
		lineageTag: cfad6031-6979-4236-aa89-f5f81f74d7d0
		summarizeBy: none
		sourceColumn: load_seat_2_driver_code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column load_miles_dead_head
		dataType: double
		lineageTag: 3f8d6d69-e750-4caa-9994-06dd1cb7cc3a
		summarizeBy: sum
		sourceColumn: load_miles_dead_head

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column load_miles_total
		dataType: double
		lineageTag: 7cae1a44-d838-423e-8df8-d61812d1aa1c
		summarizeBy: sum
		sourceColumn: load_miles_total

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column load_miles_loaded
		dataType: double
		lineageTag: faaad45f-7186-41c7-868c-b892a950d176
		summarizeBy: sum
		sourceColumn: load_miles_loaded

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column load_business_unit_code
		dataType: string
		lineageTag: 3ff57c4d-d67a-4c9f-859e-7f3cf3c30d3e
		summarizeBy: none
		sourceColumn: load_business_unit_code

		annotation SummarizationSetBy = Automatic

	partition LoadFact = m
		mode: import
		source =
				let
				    Source =
				        Sql.Database(
				            "lofzv5bdxbxepf3ufbs6kug4du-dpb5fjqdbnqezisyyjteyvx6hu.datawarehouse.fabric.microsoft.com",
				            "data_central_wh",
				            [
				                Query = "
				SELECT *
				FROM [data_central_wh].[gold].[vw_ibmi_load_combined]
				WHERE load_dispatch_date >= DATEADD(MONTH, -6, CAST(GETDATE() AS DATE))
				"
				            ]
				        ),
				    #"Reordered Columns" = Table.ReorderColumns(Source,{"load_origin_area_code", "load_load_number", "load_dispatch", "load_status", "load_dispatch_time", "load_dispatch_date", "load_truck_number", "load_trailer_number", "load_seat_1_driver_code", "load_seat_2_driver_code", "load_route_line_codes", "load_route_status", "load_miles_dead_head", "load_miles_total", "load_miles_loaded", "load_mile_flag", "load_initials", "load_destination_area_code", "load_route_line_extension", "load_dispatch_end_date", "load_dispatch_end_time", "load_multiple_trailers_on_dispatch", "load_settlement_flag", "load_payroll_approval_flag", "load_truck_dmol_code", "load_truck_dm_code", "load_driver_dmol_code", "load_driver_dm_code", "load_trip_jacket_received_flag", "load_trip_jacket_received_date", "load_miles_hub_start", "load_miles_hub_end", "load_unit_division_code", "load_team_status_code", "load_trainer_team_code", "is_deleted", "load_business_unit_code"})
				in
				    #"Reordered Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

