CREATE TABLE [gold].[dim_customer_old] (

	[customer_id_pk] int NULL, 
	[city_id_fk] int NULL, 
	[pu_area_id_fk] int NULL, 
	[division_id_fk] int NULL, 
	[customer_code] varchar(8000) NULL, 
	[is_deleted] varchar(5) NULL, 
	[cust_name] varchar(8000) NULL, 
	[cust_address_line_1] varchar(8000) NULL, 
	[cust_address_line_2] varchar(8000) NULL, 
	[cust_address_city] varchar(8000) NULL, 
	[cust_address_state] varchar(8000) NULL, 
	[cust_address_zip] varchar(8000) NULL, 
	[cust_address_zip_extn] varchar(8000) NULL, 
	[bill_to_code] varchar(8000) NULL, 
	[bill_to_name] varchar(8000) NULL, 
	[cust_salesperson] varchar(8000) NULL, 
	[cust_shipper_code] varchar(8000) NULL, 
	[cust_shipper_area_code] decimal(3,0) NULL, 
	[cust_shipper_phone] decimal(7,0) NULL, 
	[cust_country] varchar(8000) NULL, 
	[controlling_shipper] varchar(8000) NULL, 
	[controlling_shipper_name] varchar(8000) NULL, 
	[is_allow_as_shipper] varchar(8000) NULL, 
	[is_allow_as_bill_to] varchar(8000) NULL, 
	[is_allow_as_load_at] varchar(8000) NULL, 
	[is_allow_as_consignee] varchar(8000) NULL, 
	[edi_profile_code] varchar(8000) NULL, 
	[cust_division_code] varchar(8000) NULL, 
	[cust_division_name] varchar(8000) NULL, 
	[commodity_code] varchar(8000) NULL, 
	[commodity_description] varchar(8000) NULL, 
	[pu_area_code] varchar(8000) NULL, 
	[pu_area_name] varchar(8000) NULL, 
	[last_activity_date] date NULL
);