CREATE TABLE [gold].[fact_thermoking_reefer_status] (

	[vehicleName] varchar(8000) NULL, 
	[dataDate] date NULL, 
	[dataTime] time(0) NULL, 
	[isPowerOn] bit NULL, 
	[voltage] float NULL, 
	[fuelLevel] bigint NULL, 
	[dischargeAirTemp_C] float NULL, 
	[dischargeAirTemp_F] float NULL, 
	[returnAirTemp_C] float NULL, 
	[returnAirTemp_F] float NULL, 
	[setPointTemp_C] float NULL, 
	[setPointTemp_F] float NULL, 
	[ambientTemp_C] float NULL, 
	[ambientTemp_F] float NULL, 
	[doorStatus] bigint NULL, 
	[doorlocked] varchar(8000) NULL, 
	[operatingMode] varchar(8000) NULL, 
	[engineHours] bigint NULL, 
	[engineRpm] bigint NULL, 
	[electricalHours] bigint NULL, 
	[totalHours] bigint NULL, 
	[unitMode] bit NULL, 
	[unitModeDetail] varchar(8000) NULL, 
	[powerSource] varchar(8000) NULL, 
	[devicePortA] varchar(8000) NULL, 
	[devicePortB] varchar(8000) NULL, 
	[devicePortC] varchar(8000) NULL, 
	[multiTemp] bit NULL, 
	[maintenanceHours] bigint NULL, 
	[odometer] varchar(8000) NULL, 
	[controllerStatus] varchar(8000) NULL
);