CREATE TABLE [gold].[fact_maint_activity] (

	[repair_order_id] bigint NULL, 
	[ro_group] varchar(8000) NULL, 
	[ro_vin] varchar(8000) NULL, 
	[ro_unit_number] varchar(8000) NULL, 
	[ro_unit_type] varchar(8000) NULL, 
	[ro_vendor_name] varchar(8000) NULL, 
	[ro_location_type] varchar(6) NOT NULL, 
	[ro_status] varchar(8000) NULL, 
	[ro_open_closed] varchar(6) NOT NULL, 
	[ro_created_datetime] datetime2(6) NULL, 
	[ro_created_date] date NULL, 
	[ro_started_datetime] datetime2(6) NULL, 
	[ro_started_date] date NULL, 
	[ro_expected_finish_datetime] datetime2(6) NULL, 
	[ro_expected_finish_date] date NULL, 
	[ro_finished_datetime] datetime2(6) NULL, 
	[ro_finished_date] date NULL, 
	[ro_invoiced_datetime] datetime2(6) NULL, 
	[ro_invoiced_date] date NULL, 
	[ro_invoice_paid_datetime] datetime2(6) NULL, 
	[ro_invoice_paid_date] date NULL, 
	[ro_down_hours] int NULL, 
	[ro_additional_charges] float NULL, 
	[ro_tax_total] float NULL, 
	[ro_credit_amount] float NULL, 
	[ro_estimate] float NULL, 
	[ro_grand_total] float NULL, 
	[ro_paid_amount] float NULL
);