CREATE TABLE [gold].[fact_ar_weekly_snapshot] (

	[record_code] varchar(8000) NULL, 
	[customer_code] varchar(8000) NULL, 
	[invoice_number] varchar(8000) NULL, 
	[adj_batch_code] varchar(8000) NULL, 
	[record_type] varchar(8000) NULL, 
	[record_number] decimal(38,6) NULL, 
	[customer_name] varchar(8000) NULL, 
	[sequence_code] varchar(8000) NULL, 
	[statement_number] varchar(8000) NULL, 
	[dispatch_date] datetime2(6) NULL, 
	[amount] decimal(38,6) NULL, 
	[balance_forward] decimal(38,6) NULL, 
	[is_daily_pro_register] varchar(8000) NULL, 
	[is_weekly_pro_register] varchar(8000) NULL, 
	[is_monthly_pro_register] varchar(8000) NULL, 
	[is_non_current] varchar(8000) NULL, 
	[invoice_date] date NULL, 
	[load_number] varchar(8000) NULL, 
	[deposit_date] datetime2(6) NULL, 
	[cust_order_number] varchar(8000) NULL, 
	[book_month] varchar(8000) NULL, 
	[book_year] varchar(8000) NULL, 
	[SnapshotDate] date NULL, 
	[DaysOpen] bigint NULL, 
	[Open_30] bigint NULL, 
	[Open_45] bigint NULL, 
	[Open_60] bigint NULL, 
	[Open_90] bigint NULL, 
	[Open_120] bigint NULL
);