CREATE TABLE [gold].[ibmi_stopoff_mat] (

	[stopoff_load_number] varchar(8000) NULL, 
	[stopoff_stop_number] decimal(34,6) NULL, 
	[stopoff_stop_type] varchar(8) NOT NULL, 
	[stopoff_stop_code] varchar(8000) NULL, 
	[stopoff_customer_code] varchar(8000) NULL, 
	[stopoff_city_code] varchar(8000) NULL, 
	[stopoff_state] varchar(8000) NULL, 
	[stopoff_customer_area_code] decimal(34,6) NULL, 
	[stopoff_customer_phone_number] decimal(34,6) NULL, 
	[stopoff_contact_info] varchar(8000) NULL, 
	[stopoff_shipper_edi_code] varchar(8000) NULL, 
	[stopoff_consignee_edi_code] varchar(8000) NULL, 
	[stopoff_last_status] varchar(9) NOT NULL, 
	[stopoff_est_arrival_date] date NULL, 
	[stopoff_est_arrival_time] time(0) NULL, 
	[stopoff_appt_early_date] date NULL, 
	[stopoff_appt_late_date] date NULL, 
	[stopoff_appt_early_time] time(0) NULL, 
	[stopoff_appt_late_time] time(0) NULL, 
	[stopoff_arrival_date] date NULL, 
	[stopoff_arrival_time] time(0) NULL, 
	[stopoff_load_unload_date] date NULL, 
	[stopoff_load_unload_time] time(0) NULL, 
	[is_appt_required] varchar(7) NOT NULL, 
	[stopoff_shipper_specific_code] varchar(8000) NULL, 
	[stopoff_seal_1_code] varchar(8000) NULL, 
	[stopoff_seal_2_code] varchar(8000) NULL, 
	[stopoff_weight] decimal(34,6) NULL, 
	[stopoff_pieces] varchar(8000) NULL, 
	[stopoff_unit_of_measure] varchar(8000) NULL, 
	[stopoff_pallets_on] decimal(34,6) NULL, 
	[stopoff_pallets_off] decimal(34,6) NULL, 
	[stopoff_load_unload_type] varchar(16) NOT NULL, 
	[stopoff_truck_number] varchar(8000) NULL, 
	[stopoff_trailer_number] varchar(8000) NULL, 
	[stopoff_dispatch] varchar(8000) NULL, 
	[stopoff_appt_created_initials] varchar(8000) NULL, 
	[stopoff_appt_created_date] date NULL, 
	[stopoff_appt_created_time] time(0) NULL, 
	[stopoff_message] varchar(8000) NULL, 
	[is_appt_created] varchar(7) NOT NULL, 
	[stopoff_appt_date_at_dispatch] date NULL, 
	[stopoff_appt_time_at_dispatch] time(0) NULL, 
	[actual_arrival_dt] datetime2(0) NULL, 
	[appt_late_date_dt] datetime2(0) NULL, 
	[og_appt_late_dt] datetime2(0) NULL, 
	[division_code] varchar(8000) NULL, 
	[HasLateServiceException] int NULL, 
	[LateServiceExceptionReasonCode] varchar(8000) NULL, 
	[OnTimePickupLateCount] int NULL, 
	[OnTimeDeliveryLateCount] int NULL, 
	[OnTimePickupLateCount_OG] int NULL, 
	[OnTimeDeliveryLateCount_OG] int NULL, 
	[stopoff_dispatch_new] varchar(2) NULL
);