-- Auto Generated (Do not modify) 1CEDF078B409C122A3EDB4BAF2678FC1160E2102A90B325624323387D886FA00
CREATE         VIEW silver.vw_ibmi_incr_order_all
AS

SELECT 
    [cd_order_origin_area_code]         AS order_origin_area_code,
    [cd_order_load_number]              AS order_load_number,
    [cd_order_status_code]              AS order_status_code,
    [cd_order_date]                     AS order_date,
    [cd_order_time]                     AS order_time,
    [cd_order_customer_code]            AS order_customer_code,
    [cd_order_consignee_code]           AS order_consignee_code,
    [cd_order_billto_code]              AS order_billto_code,
    [cd_order_loadat_code]              AS order_loadat_code,
    [cd_order_early_pickup_date]        AS order_early_pickup_date,
    [cd_order_early_pickup_time]        AS order_early_pickup_time,
    [is_pickup_required]                AS is_pickup_required,
    [cd_order_early_delivery_date]      AS order_early_delivery_date,
    [cd_order_early_delivery_time]      AS order_early_delivery_time,
    [is_delivery_required]              AS is_delivery_required,
    [cd_order_commodity_code]           AS order_commodity_code,
    [cd_order_commodity_description]    AS order_commodity_description,
    [cd_order_creation_initials]        AS order_creation_initials,
    [cd_order_customer_phone_area_code] AS order_customer_phone_area_code,
    [cd_order_customer_phone_number]    AS order_customer_phone_number,
    [cd_order_consignee_phone_area_code]AS order_consignee_phone_area_code,
    [cd_order_consignee_phone_number]   AS order_consignee_phone_number,
    [cd_order_load_weight]              AS order_load_weight,
    [cd_order_pallet_count]             AS order_pallet_count,
    [cd_order_origin_city_code]         AS order_origin_city_code,
    [cd_order_origin_state]             AS order_origin_state,
    [cd_order_origin_bea_code]          AS order_origin_bea_code,
    [cd_order_origin_gu_code]           AS order_origin_gu_code,
    [cd_order_origin_city_short_name]   AS order_origin_city_short_name,
    [cd_order_destination_city_code]    AS order_destination_city_code,
    [cd_order_destination_state]        AS order_destination_state,
    [cd_order_destination_bea_code]     AS order_destination_bea_code,
    [cd_order_destination_gu_code]      AS order_destination_gu_code,
    [cd_order_destination_city_short_name] AS order_destination_city_short_name,
    [cd_order_miles_billable]           AS order_miles_billable,
    [cd_order_load_type]                AS order_load_type,
    [cd_order_stop_count]               AS order_stop_count,
    [cd_order_dispatch_count]           AS order_dispatch_count,
    [cd_order_preload_trailer]          AS order_preload_trailer,
    [cd_order_revenue_estimation]       AS order_revenue_estimation,
    [cd_order_new_origin_area_code]     AS order_new_origin_area_code,
    [cd_order_destination_area_code]    AS order_destination_area_code,
    [cd_order_bill_of_lading]           AS order_bill_of_lading,
    [cd_order_purchase_order]           AS order_purchase_order,
    [cd_order_pick_up_code]             AS order_pick_up_code,
    [cd_order_piece_count]              AS order_piece_count,
    [cd_order_collection_method_code]   AS order_collection_method_code,
    [cd_order_load_volume]              AS order_load_volume,
    [cd_order_message]                  AS order_message,
    [cd_order_late_pickup_date]         AS order_late_pickup_date,
    [cd_order_late_pickup_time]         AS order_late_pickup_time,
    [cd_order_late_delivery_date]       AS order_late_delivery_date,
    [cd_order_late_delivery_time]       AS order_late_delivery_time,
    [cd_order_required_pallet_count]    AS order_required_pallet_count,
    [cd_order_ship_date]                AS order_ship_date,
    [order_ship_time]                   AS order_ship_time,
    [cd_order_temp_high]                AS order_temp_high,
    [cd_order_temp_low]                 AS order_temp_low,
    [cd_order_last_update_date]         AS order_last_update_date,
    [cd_order_last_update_time]         AS order_last_update_time,
    [cd_order_last_update_initials]     AS order_last_update_initials,
    [cd_order_company_code]             AS order_company_code,
    [cd_order_division_code]            AS order_division_code,
    [cd_order_lane_code]                AS order_lane_code,
    [cd_order_seal_code]                AS order_seal_code,
    [cd_order_service_failure_code]     AS order_service_failure_code,
    [cd_order_driver_commit_flag]       AS order_driver_commit_flag,
    [is_edi_load]                       AS is_edi_load,
    [is_edi_stats_complete]             AS is_edi_stats_complete,
    [is_driver_loaded]                  AS is_driver_loaded,
    [is_driver_unloaded]                AS is_driver_unloaded,
    [is_delivery_receipt_signed]        AS is_delivery_receipt_signed,
    [cd_order_delivery_receipt_req]     AS order_delivery_receipt_req,
    [cd_order_edi_message_billing_flag] AS order_edi_message_billing_flag,
    [is_load_just_in_time]              AS is_load_just_in_time,
    [cd_order_edi_billing_code]         AS order_edi_billing_code,
    [is_edi_inbound_or_outbound]        AS is_edi_inbound_or_outbound,
    [cd_order_current_city_code]        AS order_current_city_code,
    [cd_order_current_state]            AS order_current_state,
    [cd_order_loaded_call_date]         AS order_loaded_call_date,
    [cd_order_empty_call_date]          AS order_empty_call_date,
    [cd_order_trailer_length]           AS order_trailer_length,
    [cd_order_trailer_height]           AS order_trailer_height,
    [has_permit]                        AS has_permit,
    [has_permit_complete]               AS has_permit_complete,
    [cd_order_latitude]                 AS order_latitude,
    [cd_order_longitude]                AS order_longitude,
    [is_tentitive_load]                 AS is_tentitive_load,
    [cd_order_hours_under_dispatch]     AS order_hours_under_dispatch,
    [cd_order_origin_zone_code]         AS order_origin_zone_code,
    [cd_order_origin_region_code]       AS order_origin_region_code,
    [cd_order_destination_zone_code]    AS order_destination_zone_code,
    [cd_order_destination_region_code]  AS order_destination_region_code,
    [is_to_be_rated]                    AS is_to_be_rated,
    [has_new_gu_code]                   AS has_new_gu_code,
    [is_exclude_from_model]             AS is_exclude_from_model,
    [is_deleted] AS is_deleted,
    [cd_order_carry_over_flag]          AS order_carry_over_flag,
    [cd_order_truck_type_requirement_code] AS order_truck_type_requirement_code,
    [cd_order_delivery_code]            AS order_delivery_code
FROM [silver].[ibmi_incr_cd_order_new]  

UNION ALL

SELECT 
    [tlb_order_origin_area_code],
    [tlb_order_load_number],
    [tlb_order_status_code],
    [tlb_order_date],
    [tlb_order_time],
    [tlb_order_customer_code],
    [tlb_order_consignee_code],
    [tlb_order_billto_code],
    [tlb_order_loadat_code],
    [tlb_order_early_pickup_date],
    [tlb_order_early_pickup_time],
    [is_pickup_required],
    [tlb_order_early_delivery_date],
    [tlb_order_early_delivery_time],
    [is_delivery_required],
    [tlb_order_commodity_code],
    [tlb_order_commodity_description],
    [tlb_order_creation_initials],
    [tlb_order_customer_phone_area_code],
    [tlb_order_customer_phone_number],
    [tlb_order_consignee_phone_area_code],
    [tlb_order_consignee_phone_number],
    [tlb_order_load_weight],
    [tlb_order_pallet_count],
    [tlb_order_origin_city_code],
    [tlb_order_origin_state],
    [tlb_order_origin_bea_code],
    [tlb_order_origin_gu_code],
    [tlb_order_origin_city_short_name],
    [tlb_order_destination_city_code],
    [tlb_order_destination_state],
    [tlb_order_destination_bea_code],
    [tlb_order_destination_gu_code],
    [tlb_order_destination_city_short_name],
    [tlb_order_miles_billable],
    [tlb_order_load_type],
    [tlb_order_stop_count],
    [tlb_order_dispatch_count],
    [tlb_order_preload_trailer],
    [tlb_order_revenue_estimation],
    [tlb_order_new_origin_area_code],
    [tlb_order_destination_area_code],
    [tlb_order_bill_of_lading],
    [tlb_order_purchase_order],
    [tlb_order_pick_up_code],
    [tlb_order_piece_count],
    [tlb_order_collection_method_code],
    [tlb_order_load_volume],
    [tlb_order_message],
    [tlb_order_late_pickup_date],
    [tlb_order_late_pickup_time],
    [tlb_order_late_delivery_date],
    [tlb_order_late_delivery_time],
    [tlb_order_required_pallet_count],
    [tlb_order_ship_date],
    [order_ship_time],
    [tlb_order_temp_high],
    [tlb_order_temp_low],
    [tlb_order_last_update_date],
    [tlb_order_last_update_time],
    [tlb_order_last_update_initials],
    [tlb_order_company_code],
    [tlb_order_division_code],
    [tlb_order_lane_code],
    [tlb_order_seal_code],
    [tlb_order_service_failure_code],
    [tlb_order_driver_commit_flag],
    [is_edi_load],
    [is_edi_stats_complete],
    [is_driver_loaded],
    [is_driver_unloaded],
    [is_delivery_receipt_signed],
    [tlb_order_delivery_receipt_req],
    [tlb_order_edi_message_billing_flag],
    [is_load_just_in_time],
    [tlb_order_edi_billing_code],
    [is_edi_inbound_or_outbound],
    [tlb_order_current_city_code],
    [tlb_order_current_state],
    [tlb_order_loaded_call_date],
    [tlb_order_empty_call_date],
    [tlb_order_trailer_length],
    [tlb_order_trailer_height],
    [has_permit],
    [has_permit_complete],
    [tlb_order_latitude],
    [tlb_order_longitude],
    [is_tentitive_load],
    [tlb_order_hours_under_dispatch],
    [tlb_order_origin_zone_code],
    [tlb_order_origin_region_code],
    [tlb_order_destination_zone_code],
    [tlb_order_destination_region_code],
    [is_to_be_rated],
    [has_new_gu_code],
    [is_exclude_from_model],
    [is_deleted],
    [tlb_order_carry_over_flag],
    [tlb_order_truck_type_requirement_code],
    [tlb_order_delivery_code]
FROM [silver].[ibmi_incr_tlb_order_new]
WHERE tlb_order_load_number NOT IN (SELECT cd_order_load_number FROM [silver].[ibmi_incr_cd_order_new])

UNION ALL

SELECT 
    [order_origin_area_code],
    [order_load_number],
    [order_status_code],
    [order_date],
    [order_time],
    [order_customer_code],
    [order_consignee_code],
    [order_billto_code],
    [order_loadat_code],
    [order_early_pickup_date],
    [order_early_pickup_time],
    [is_pickup_required],
    [order_early_delivery_date],
    [order_early_delivery_time],
    [is_delivery_required],
    [order_commodity_code],
    [order_commodity_description],
    [order_creation_initials],
    [order_customer_phone_area_code],
    [order_customer_phone_number],
    [order_consignee_phone_area_code],
    [order_consignee_phone_number],
    [order_load_weight],
    [order_pallet_count],
    [order_origin_city_code],
    [order_origin_state],
    [order_origin_bea_code],
    [order_origin_gu_code],
    [order_origin_city_short_name],
    [order_destination_city_code],
    [order_destination_state],
    [order_destination_bea_code],
    [order_destination_gu_code],
    [order_destination_city_short_name],
    [order_miles_billable],
    [order_load_type],
    [order_stop_count],
    [order_dispatch_count],
    [order_preload_trailer],
    [order_revenue_estimation],
    [order_new_origin_area_code],
    [order_destination_area_code],
    [order_bill_of_lading],
    [order_purchase_order],
    [order_pick_up_code],
    [order_piece_count],
    [order_collection_method_code],
    [order_load_volume],
    [order_message],
    [order_late_pickup_date],
    [order_late_pickup_time],
    [order_late_delivery_date],
    [order_late_delivery_time],
    [order_required_pallet_count],
    [order_ship_date],
    [order_ship_time],
    [order_temp_high],
    [order_temp_low],
    [order_last_update_date],
    [order_last_update_time],
    [order_last_update_initials],
    [order_company_code],
    [order_division_code],
    [order_lane_code],
    [order_seal_code],
    [order_service_failure_code],
    [order_driver_commit_flag],
    [is_edi_load],
    [is_edi_stats_complete],
    [is_driver_loaded],
    [is_driver_unloaded],
    [is_delivery_receipt_signed],
    [order_delivery_receipt_req],
    [order_edi_message_billing_flag],
    [is_load_just_in_time],
    [order_edi_billing_code],
    [is_edi_inbound_or_outbound],
    [order_current_city_code],
    [order_current_state],
    [order_loaded_call_date],
    [order_empty_call_date],
    [order_trailer_length],
    [order_trailer_height],
    [has_permit],
    [has_permit_complete],
    [order_latitude],
    [order_longitude],
    [is_tentitive_load],
    [order_hours_under_dispatch],
    [order_origin_zone_code],
    [order_origin_region_code],
    [order_destination_zone_code],
    [order_destination_region_code],
    [is_to_be_rated],
    [has_new_gu_code],
    [is_exclude_from_model],
    [is_deleted],
    [order_carry_over_flag],
    [order_truck_type_requirement_code],
    [order_delivery_code]
FROM [silver].[ibmi_incr_order_new]
WHERE order_load_number NOT IN (SELECT cd_order_load_number FROM [silver].[ibmi_incr_cd_order_new])
  AND order_load_number NOT IN (SELECT tlb_order_load_number FROM [silver].[ibmi_incr_tlb_order_new])