section Section1;
shared Query = let
  Source = DB2.Database("S10A3543.STEVENSTRANSPORT.COM:447", "S10A3543", [HierarchicalNavigation = true, Implementation = "Microsoft"]),
  #"From Value" = Table.FromValue(Source),
  #"Remove Columns" = Table.RemoveColumns(#"From Value", Table.ColumnsOfType(#"From Value", {type table, type record, type list, type nullable binary, type binary, type function}))
in
  #"Remove Columns";
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "VW_DRIVERS_DataDestination", IsNewTarget = false], Settings = [Kind = "Manual", AllowCreation = false, ColumnSettings = [Mappings = {[SourceColumnName = "DRCODE", DestinationColumnName = "DRCODE"], [SourceColumnName = "DRNAME", DestinationColumnName = "DRNAME"], [SourceColumnName = "DRSHNM", DestinationColumnName = "DRSHNM"], [SourceColumnName = "DRADD", DestinationColumnName = "DRADD"], [SourceColumnName = "DRCITY", DestinationColumnName = "DRCITY"], [SourceColumnName = "DRST", DestinationColumnName = "DRST"], [SourceColumnName = "DRZIP", DestinationColumnName = "DRZIP"], [SourceColumnName = "DRZP2", DestinationColumnName = "DRZP2"], [SourceColumnName = "DRAC", DestinationColumnName = "DRAC"], [SourceColumnName = "DRPHON", DestinationColumnName = "DRPHON"], [SourceColumnName = "DRSS", DestinationColumnName = "DRSS"], [SourceColumnName = "DRSUPR", DestinationColumnName = "DRSUPR"], [SourceColumnName = "DRFMGR", DestinationColumnName = "DRFMGR"], [SourceColumnName = "DRCRED", DestinationColumnName = "DRCRED"], [SourceColumnName = "DRCRET", DestinationColumnName = "DRCRET"], [SourceColumnName = "DRCREI", DestinationColumnName = "DRCREI"], [SourceColumnName = "DRUPDD", DestinationColumnName = "DRUPDD"], [SourceColumnName = "DRUPDT", DestinationColumnName = "DRUPDT"], [SourceColumnName = "DRUPDI", DestinationColumnName = "DRUPDI"], [SourceColumnName = "DRCO", DestinationColumnName = "DRCO"], [SourceColumnName = "DRDV", DestinationColumnName = "DRDV"], [SourceColumnName = "DRTM", DestinationColumnName = "DRTM"], [SourceColumnName = "DRBDAT", DestinationColumnName = "DRBDAT"], [SourceColumnName = "DRHDAT", DestinationColumnName = "DRHDAT"], [SourceColumnName = "DRRDAT", DestinationColumnName = "DRRDAT"], [SourceColumnName = "DRTDAT", DestinationColumnName = "DRTDAT"], [SourceColumnName = "DRLEXP", DestinationColumnName = "DRLEXP"], [SourceColumnName = "DRPEXP", DestinationColumnName = "DRPEXP"], [SourceColumnName = "DRLICE", DestinationColumnName = "DRLICE"], [SourceColumnName = "DRTYPE", DestinationColumnName = "DRTYPE"], [SourceColumnName = "DRSTAT", DestinationColumnName = "DRSTAT"], [SourceColumnName = "DRPRVO", DestinationColumnName = "DRPRVO"], [SourceColumnName = "DRPDSP", DestinationColumnName = "DRPDSP"], [SourceColumnName = "DRORD", DestinationColumnName = "DRORD"], [SourceColumnName = "DRDISP", DestinationColumnName = "DRDISP"], [SourceColumnName = "DRUNIT", DestinationColumnName = "DRUNIT"], [SourceColumnName = "DRDCTY", DestinationColumnName = "DRDCTY"], [SourceColumnName = "DRDST", DestinationColumnName = "DRDST"], [SourceColumnName = "DRMSG", DestinationColumnName = "DRMSG"], [SourceColumnName = "DRDLT", DestinationColumnName = "DRDLT"], [SourceColumnName = "DRENAM", DestinationColumnName = "DRENAM"], [SourceColumnName = "DRENUM", DestinationColumnName = "DRENUM"], [SourceColumnName = "DRPHAZ", DestinationColumnName = "DRPHAZ"], [SourceColumnName = "DRNUNT", DestinationColumnName = "DRNUNT"], [SourceColumnName = "DRSPS", DestinationColumnName = "DRSPS"], [SourceColumnName = "DRMISC", DestinationColumnName = "DRMISC"], [SourceColumnName = "DRFC", DestinationColumnName = "DRFC"], [SourceColumnName = "DRHOME", DestinationColumnName = "DRHOME"], [SourceColumnName = "DRVOIC", DestinationColumnName = "DRVOIC"], [SourceColumnName = "DRJIT", DestinationColumnName = "DRJIT"], [SourceColumnName = "DRTRAN", DestinationColumnName = "DRTRAN"], [SourceColumnName = "DR1DTE", DestinationColumnName = "DR1DTE"], [SourceColumnName = "DR1MIL", DestinationColumnName = "DR1MIL"], [SourceColumnName = "DR2DTE", DestinationColumnName = "DR2DTE"], [SourceColumnName = "DR2MIL", DestinationColumnName = "DR2MIL"], [SourceColumnName = "DR3DTE", DestinationColumnName = "DR3DTE"], [SourceColumnName = "DR3MIL", DestinationColumnName = "DR3MIL"], [SourceColumnName = "DR4DTE", DestinationColumnName = "DR4DTE"], [SourceColumnName = "DR4MIL", DestinationColumnName = "DR4MIL"], [SourceColumnName = "DR5DTE", DestinationColumnName = "DR5DTE"], [SourceColumnName = "DR5MIL", DestinationColumnName = "DR5MIL"], [SourceColumnName = "DR6DTE", DestinationColumnName = "DR6DTE"], [SourceColumnName = "DR6MIL", DestinationColumnName = "DR6MIL"], [SourceColumnName = "DR7DTE", DestinationColumnName = "DR7DTE"], [SourceColumnName = "DR7MIL", DestinationColumnName = "DR7MIL"], [SourceColumnName = "DRDBAL", DestinationColumnName = "DRDBAL"], [SourceColumnName = "DRCBAL", DestinationColumnName = "DRCBAL"], [SourceColumnName = "DRMBPW", DestinationColumnName = "DRMBPW"], [SourceColumnName = "DRLPAY", DestinationColumnName = "DRLPAY"], [SourceColumnName = "DRCARD", DestinationColumnName = "DRCARD"], [SourceColumnName = "DRSOLO", DestinationColumnName = "DRSOLO"], [SourceColumnName = "DRLTDT", DestinationColumnName = "DRLTDT"], [SourceColumnName = "DRNTDT", DestinationColumnName = "DRNTDT"], [SourceColumnName = "DRSMKR", DestinationColumnName = "DRSMKR"], [SourceColumnName = "DRRACE", DestinationColumnName = "DRRACE"], [SourceColumnName = "DRSEX", DestinationColumnName = "DRSEX"], [SourceColumnName = "DRLONG", DestinationColumnName = "DRLONG"], [SourceColumnName = "DRLGDT", DestinationColumnName = "DRLGDT"], [SourceColumnName = "DRTYCD", DestinationColumnName = "DRTYCD"], [SourceColumnName = "DRTERM", DestinationColumnName = "DRTERM"], [SourceColumnName = "DRPTAD", DestinationColumnName = "DRPTAD"], [SourceColumnName = "DRPTAT", DestinationColumnName = "DRPTAT"], [SourceColumnName = "DRHFM", DestinationColumnName = "DRHFM"], [SourceColumnName = "DRSPCT", DestinationColumnName = "DRSPCT"], [SourceColumnName = "DRSPST", DestinationColumnName = "DRSPST"], [SourceColumnName = "DRSDTE", DestinationColumnName = "DRSDTE"], [SourceColumnName = "DRSTME", DestinationColumnName = "DRSTME"], [SourceColumnName = "DRPRIO", DestinationColumnName = "DRPRIO"], [SourceColumnName = "DRDTED", DestinationColumnName = "DRDTED"], [SourceColumnName = "DRTMED", DestinationColumnName = "DRTMED"], [SourceColumnName = "DRUNTA", DestinationColumnName = "DRUNTA"], [SourceColumnName = "DRFIL", DestinationColumnName = "DRFIL"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared VW_DRIVERS = let
  Source = DB2.Database("S10A3543.STEVENSTRANSPORT.COM:447", "S10A3543", [HierarchicalNavigation = true, Implementation = "Microsoft"]),
  #"Navigation 1" = Source{[Schema = "FABRIC"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Name = "VW_DRIVERS"]}[Data],
  #"Renamed columns" = Table.RenameColumns(#"Navigation 2", {{"DRCO#", "DRCO"}, {"DRDV#", "DRDV"}, {"DRTM#", "DRTM"}, {"DRORD#", "DRORD"}})
in
  #"Renamed columns";
shared VW_DRIVERS_DataDestination = let
  Pattern = Lakehouse.Contents([CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "a6d2c31b-0b03-4c60-a258-c2664c56fe3d"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "f9a73da1-08e4-4f3d-a67f-74623bfde721"]}[Data],
  TableNavigation = Navigation_2{[Id = "ibmi_driver_bronze", ItemKind = "Table"]}[Data]
in
  TableNavigation;
