/*========================================================
  1) usp_ibmi_incr_cd_order_silver_new
  - ONLY change: add delete step (distinct ORODR) after #DedupedWithDates is created
  - NO other changes (no datatype changes, no column renames, etc.)
========================================================*/
CREATE   PROCEDURE [dbo].[usp_ibmi_incr_cd_order_silver_new]
AS
BEGIN
    SET NOCOUNT ON;

    -- Step 1: Prepare the deduplicated source data with date joins in a temp table
    IF OBJECT_ID('tempdb..#DedupedWithDates') IS NOT NULL DROP TABLE #DedupedWithDates;

    SELECT a.*,
           ORDATE.date_key_pk AS ORDATE_key,
           ORPDAT.date_key_pk AS ORPDAT_key,
           ORDDAT.date_key_pk AS ORDDAT_key,
           ORAPDT.date_key_pk AS ORAPDT_key,
           ORADDT.date_key_pk AS ORADDT_key,
           ORUPDD.date_key_pk AS ORUPDD_key,
           ORLCDT.date_key_pk AS ORLCDT_key,
           ORECDT.date_key_pk AS ORECDT_key,
           ORSHDT.date_key_pk AS ORSHDT_key
    INTO #DedupedWithDates
    FROM (
        SELECT *,
               ROW_NUMBER() OVER (
                   PARTITION BY ORODR
                   ORDER BY loadDate DESC, recordNumber DESC
               ) AS rn
        FROM data_central_lh.dbo.ibmi_incr_cd_order_bronze_new
    ) a
    LEFT JOIN gold.dim_date ORDATE ON a.ORDATE = ORDATE.date_ordinal
    LEFT JOIN gold.dim_date ORPDAT ON a.ORPDAT = ORPDAT.date_ordinal
    LEFT JOIN gold.dim_date ORDDAT ON a.ORDDAT = ORDDAT.date_ordinal
    LEFT JOIN gold.dim_date ORAPDT ON a.ORAPDT = ORAPDT.date_ordinal
    LEFT JOIN gold.dim_date ORADDT ON a.ORADDT = ORADDT.date_ordinal
    LEFT JOIN gold.dim_date ORUPDD ON a.ORUPDD = ORUPDD.date_ordinal
    LEFT JOIN gold.dim_date ORLCDT ON a.ORLCDT = ORLCDT.date_ordinal
    LEFT JOIN gold.dim_date ORECDT ON a.ORECDT = ORECDT.date_ordinal
    LEFT JOIN gold.dim_date ORSHDT ON a.ORSHDT = ORSHDT.date_ordinal
    WHERE a.rn = 1;

    /*========================================================
      NEW Step 1.5: Delete from target ONLY for DISTINCT ORODR in this run
    ========================================================*/
    IF OBJECT_ID('tempdb..#CdOrdersToDelete') IS NOT NULL DROP TABLE #CdOrdersToDelete;

    SELECT DISTINCT TRIM(ORODR) AS cd_order_load_number
    INTO #CdOrdersToDelete
    FROM #DedupedWithDates
    WHERE ORODR IS NOT NULL;

    DELETE TGT
    FROM silver.ibmi_incr_cd_order_new TGT
    JOIN #CdOrdersToDelete D
      ON TGT.cd_order_load_number = D.cd_order_load_number;

    -- Step 2: UPDATE existing records
    UPDATE TGT
    SET 
        cd_order_origin_area_code           = TRIM(SRC.ORARA),
        cd_order_load_number                = TRIM(SRC.ORODR),
        cd_order_status_code                = TRIM(SRC.ORSTAT),
        cd_order_date                       = SRC.ORDATE_key,
        cd_order_time                       = TRIM(SRC.ORTIME),
        cd_order_customer_code              = TRIM(SRC.ORCUST),
        cd_order_consignee_code             = TRIM(SRC.ORCONS),
        cd_order_billto_code                = TRIM(SRC.ORBILL),
        cd_order_loadat_code                = TRIM(SRC.ORLDAT),
        cd_order_early_pickup_date          = SRC.ORPDAT_key,
        cd_order_early_pickup_time          = TRIM(SRC.ORPTIM),
        is_pickup_required                  = CASE TRIM(SRC.ORRPIK) WHEN 'Y' THEN 'TRUE' WHEN 'N' THEN 'FALSE' ELSE 'unknown' END,
        cd_order_early_delivery_date        = SRC.ORDDAT_key,
        cd_order_early_delivery_time        = TRIM(SRC.ORDTIM),
        is_delivery_required                = CASE TRIM(SRC.ORRDEL) WHEN 'Y' THEN 'TRUE' WHEN 'N' THEN 'FALSE' ELSE 'unknown' END,
        cd_order_commodity_code             = TRIM(SRC.ORCOMC),
        cd_order_commodity_description      = TRIM(SRC.ORCOMD),
        cd_order_creation_initials          = TRIM(SRC.ORINIT),
        cd_order_customer_phone_area_code   = CONVERT(VARCHAR, SRC.ORCAC),
        cd_order_customer_phone_number      = CONVERT(VARCHAR, SRC.ORCPHN),
        cd_order_consignee_phone_area_code  = CONVERT(VARCHAR, SRC.ORRAC),
        cd_order_consignee_phone_number     = CONVERT(VARCHAR, SRC.ORRPHN),
        cd_order_load_weight                = SRC.ORWGT,
        cd_order_pallet_count               = TRIM(SRC.ORPLLT),
        cd_order_origin_city_code           = TRIM(SRC.OROCTY),
        cd_order_origin_state               = TRIM(SRC.OROST),
        cd_order_origin_bea_code            = SRC.OROBEA,
        cd_order_origin_gu_code             = TRIM(SRC.OROGU),
        cd_order_origin_city_short_name     = TRIM(SRC.OROSNM),
        cd_order_destination_city_code      = TRIM(SRC.ORDCTY),
        cd_order_destination_state          = TRIM(SRC.ORDST),
        cd_order_destination_bea_code       = SRC.ORDBEA,
        cd_order_destination_gu_code        = TRIM(SRC.ORDGU),
        cd_order_destination_city_short_name= TRIM(SRC.ORDSNM),
        cd_order_miles_billable             = SRC.ORMILE,
        cd_order_load_type                  = TRIM(SRC.ORRST),
        cd_order_stop_count                 = TRIM(SRC.ORSTP),
        cd_order_dispatch_count             = TRIM(SRC.OR_DSP),
        cd_order_preload_trailer            = TRIM(SRC.ORTRLR),
        cd_order_revenue_estimation         = SRC.ORESTR,
        cd_order_new_origin_area_code       = TRIM(SRC.ORNWPK),
        cd_order_destination_area_code      = TRIM(SRC.ORINAR),
        cd_order_bill_of_lading             = TRIM(SRC.ORCSH),
        cd_order_purchase_order             = TRIM(SRC.ORCNS),
        cd_order_pick_up_code               = TRIM(SRC.ORORBY),
        cd_order_piece_count                = TRIM(SRC.ORPIEC),
        cd_order_collection_method_code     = TRIM(SRC.ORPORC),
        cd_order_load_volume                = TRIM(SRC.ORCUBE),
        cd_order_message                    = TRIM(SRC.ORSPEC),
        cd_order_late_pickup_date           = SRC.ORAPDT_key,
        cd_order_late_pickup_time           = TRIM(SRC.ORAPTM),
        cd_order_late_delivery_date         = SRC.ORADDT_key,
        cd_order_late_delivery_time         = TRIM(SRC.ORADTM),
        cd_order_required_pallet_count      = SRC.ORPREQ,
        cd_order_ship_date                  = SRC.ORSHDT_key,
        order_ship_time                     = TRIM(SRC.ORSHTM),
        cd_order_temp_high                  = SRC.ORTMPH,
        cd_order_temp_low                   = SRC.ORTMPL,
        cd_order_last_update_date           = SRC.ORUPDD_key,
        cd_order_last_update_time           = TRIM(SRC.ORUPDT),
        cd_order_last_update_initials       = TRIM(SRC.ORUPDI),
        cd_order_company_code               = TRIM(SRC.ORCO),
        cd_order_division_code              = TRIM(SRC.ORDV),
        cd_order_lane_code                  = TRIM(SRC.ORTM),
        cd_order_seal_code                  = TRIM(SRC.ORSEL1),
        cd_order_service_failure_code       = TRIM(SRC.ORSERV),
        cd_order_driver_commit_flag         = TRIM(SRC.ORCMTM),
        is_edi_load                         = TRIM(SRC.OREDI),
        is_edi_stats_complete               = TRIM(SRC.OREDIC),
        is_driver_loaded                    = TRIM(SRC.ORDLD),
        is_driver_unloaded                  = TRIM(SRC.ORDULD),
        is_delivery_receipt_signed          = TRIM(SRC.ORSDR),
        cd_order_delivery_receipt_req       = TRIM(SRC.ORSDRR),
        cd_order_edi_message_billing_flag   = TRIM(SRC.OREDMB),
        is_load_just_in_time                = TRIM(SRC.ORJIT),
        cd_order_edi_billing_code           = TRIM(SRC.OREDFB),
        is_edi_inbound_or_outbound          = CASE TRIM(SRC.OREDIO) WHEN 'I' THEN 'INBOUND' WHEN 'O' THEN 'OUTBOUND' ELSE 'unknown' END,
        cd_order_current_city_code          = TRIM(SRC.ORCCTY),
        cd_order_current_state              = TRIM(SRC.ORCST),
        cd_order_loaded_call_date           = SRC.ORLCDT_key,
        cd_order_empty_call_date            = SRC.ORECDT_key,
        cd_order_trailer_length             = SRC.ORLGT,
        cd_order_trailer_height             = SRC.ORHGT,
        has_permit                          = TRIM(SRC.ORPMTF),
        has_permit_complete                 = TRIM(SRC.ORPCOM),
        cd_order_latitude                   = SRC.ORLAT,
        cd_order_longitude                  = SRC.ORLONG,
        is_tentitive_load                   = TRIM(SRC.ORTEN),
        cd_order_hours_under_dispatch       = SRC.ORHRS,
        cd_order_origin_zone_code           = TRIM(SRC.OROZN),
        cd_order_origin_region_code         = TRIM(SRC.ORORG),
        cd_order_destination_zone_code      = TRIM(SRC.ORDZN),
        cd_order_destination_region_code    = TRIM(SRC.ORDRG),
        is_to_be_rated                      = TRIM(SRC.ORTBRT),
        has_new_gu_code                     = TRIM(SRC.ORNGU),
        is_exclude_from_model               = TRIM(SRC.OREFM),
        cd_order_carry_over_flag            = TRIM(SRC.ORCARF),
        cd_order_truck_type_requirement_code= TRIM(SRC.ORUTYP),
        cd_order_delivery_code              = TRIM(SRC.ORFIL)
    FROM silver.ibmi_incr_cd_order_new TGT
    JOIN #DedupedWithDates SRC
        ON TGT.cd_order_load_number = TRIM(SRC.ORODR);

    -- Step 3: Insert new records
    INSERT INTO silver.ibmi_incr_cd_order_new (
        cd_order_origin_area_code,
        cd_order_load_number,
        cd_order_status_code,
        cd_order_date,
        cd_order_time,
        cd_order_customer_code,
        cd_order_consignee_code,
        cd_order_billto_code,
        cd_order_loadat_code,
        cd_order_early_pickup_date,
        cd_order_early_pickup_time,
        is_pickup_required,
        cd_order_early_delivery_date,
        cd_order_early_delivery_time,
        is_delivery_required,
        cd_order_commodity_code,
        cd_order_commodity_description,
        cd_order_creation_initials,
        cd_order_customer_phone_area_code,
        cd_order_customer_phone_number,
        cd_order_consignee_phone_area_code,
        cd_order_consignee_phone_number,
        cd_order_load_weight,
        cd_order_pallet_count,
        cd_order_origin_city_code,
        cd_order_origin_state,
        cd_order_origin_bea_code,
        cd_order_origin_gu_code,
        cd_order_origin_city_short_name,
        cd_order_destination_city_code,
        cd_order_destination_state,
        cd_order_destination_bea_code,
        cd_order_destination_gu_code,
        cd_order_destination_city_short_name,
        cd_order_miles_billable,
        cd_order_load_type,
        cd_order_stop_count,
        cd_order_dispatch_count,
        cd_order_preload_trailer,
        cd_order_revenue_estimation,
        cd_order_new_origin_area_code,
        cd_order_destination_area_code,
        cd_order_bill_of_lading,
        cd_order_purchase_order,
        cd_order_pick_up_code,
        cd_order_piece_count,
        cd_order_collection_method_code,
        cd_order_load_volume,
        cd_order_message,
        cd_order_late_pickup_date,
        cd_order_late_pickup_time,
        cd_order_late_delivery_date,
        cd_order_late_delivery_time,
        cd_order_required_pallet_count,
        cd_order_ship_date,
        order_ship_time,
        cd_order_temp_high,
        cd_order_temp_low,
        cd_order_last_update_date,
        cd_order_last_update_time,
        cd_order_last_update_initials,
        cd_order_company_code,
        cd_order_division_code,
        cd_order_lane_code,
        cd_order_seal_code,
        cd_order_service_failure_code,
        cd_order_driver_commit_flag,
        is_edi_load,
        is_edi_stats_complete,
        is_driver_loaded,
        is_driver_unloaded,
        is_delivery_receipt_signed,
        cd_order_delivery_receipt_req,
        cd_order_edi_message_billing_flag,
        is_load_just_in_time,
        cd_order_edi_billing_code,
        is_edi_inbound_or_outbound,
        cd_order_current_city_code,
        cd_order_current_state,
        cd_order_loaded_call_date,
        cd_order_empty_call_date,
        cd_order_trailer_length,
        cd_order_trailer_height,
        has_permit,
        has_permit_complete,
        cd_order_latitude,
        cd_order_longitude,
        is_tentitive_load,
        cd_order_hours_under_dispatch,
        cd_order_origin_zone_code,
        cd_order_origin_region_code,
        cd_order_destination_zone_code,
        cd_order_destination_region_code,
        is_to_be_rated,
        has_new_gu_code,
        is_exclude_from_model,
        cd_order_carry_over_flag,
        cd_order_truck_type_requirement_code,
        cd_order_delivery_code
    )
    SELECT 
        TRIM(SRC.ORARA),
        TRIM(SRC.ORODR),
        TRIM(SRC.ORSTAT),
        SRC.ORDATE_key,
        TRIM(SRC.ORTIME),
        TRIM(SRC.ORCUST),
        TRIM(SRC.ORCONS),
        TRIM(SRC.ORBILL),
        TRIM(SRC.ORLDAT),
        SRC.ORPDAT_key,
        TRIM(SRC.ORPTIM),
        CASE TRIM(SRC.ORRPIK) WHEN 'Y' THEN 'TRUE' WHEN 'N' THEN 'FALSE' ELSE 'unknown' END,
        SRC.ORDDAT_key,
        TRIM(SRC.ORDTIM),
        CASE TRIM(SRC.ORRDEL) WHEN 'Y' THEN 'TRUE' WHEN 'N' THEN 'FALSE' ELSE 'unknown' END,
        TRIM(SRC.ORCOMC),
        TRIM(SRC.ORCOMD),
        TRIM(SRC.ORINIT),
        CONVERT(VARCHAR, SRC.ORCAC),
        CONVERT(VARCHAR, SRC.ORCPHN),
        CONVERT(VARCHAR, SRC.ORRAC),
        CONVERT(VARCHAR, SRC.ORRPHN),
        SRC.ORWGT,
        TRIM(SRC.ORPLLT),
        TRIM(SRC.OROCTY),
        TRIM(SRC.OROST),
        SRC.OROBEA,
        TRIM(SRC.OROGU),
        TRIM(SRC.OROSNM),
        TRIM(SRC.ORDCTY),
        TRIM(SRC.ORDST),
        SRC.ORDBEA,
        TRIM(SRC.ORDGU),
        TRIM(SRC.ORDSNM),
        SRC.ORMILE,
        TRIM(SRC.ORRST),
        TRIM(SRC.ORSTP),
        TRIM(SRC.OR_DSP),
        TRIM(SRC.ORTRLR),
        SRC.ORESTR,
        TRIM(SRC.ORNWPK),
        TRIM(SRC.ORINAR),
        TRIM(SRC.ORCSH),
        TRIM(SRC.ORCNS),
        TRIM(SRC.ORORBY),
        TRIM(SRC.ORPIEC),
        TRIM(SRC.ORPORC),
        TRIM(SRC.ORCUBE),
        TRIM(SRC.ORSPEC),
        SRC.ORAPDT_key,
        TRIM(SRC.ORAPTM),
        SRC.ORADDT_key,
        TRIM(SRC.ORADTM),
        SRC.ORPREQ,
        SRC.ORSHDT_key,
        TRIM(SRC.ORSHTM),
        SRC.ORTMPH,
        SRC.ORTMPL,
        SRC.ORUPDD_key,
        TRIM(SRC.ORUPDT),
        TRIM(SRC.ORUPDI),
        TRIM(SRC.ORCO),
        TRIM(SRC.ORDV),
        TRIM(SRC.ORTM),
        TRIM(SRC.ORSEL1),
        TRIM(SRC.ORSERV),
        TRIM(SRC.ORCMTM),
        TRIM(SRC.OREDI),
        TRIM(SRC.OREDIC),
        TRIM(SRC.ORDLD),
        TRIM(SRC.ORDULD),
        TRIM(SRC.ORSDR),
        TRIM(SRC.ORSDRR),
        TRIM(SRC.OREDMB),
        TRIM(SRC.ORJIT),
        TRIM(SRC.OREDFB),
        CASE TRIM(SRC.OREDIO) WHEN 'I' THEN 'INBOUND' WHEN 'O' THEN 'OUTBOUND' ELSE 'unknown' END,
        TRIM(SRC.ORCCTY),
        TRIM(SRC.ORCST),
        SRC.ORLCDT_key,
        SRC.ORECDT_key,
        SRC.ORLGT,
        SRC.ORHGT,
        TRIM(SRC.ORPMTF),
        TRIM(SRC.ORPCOM),
        SRC.ORLAT,
        SRC.ORLONG,
        TRIM(SRC.ORTEN),
        SRC.ORHRS,
        TRIM(SRC.OROZN),
        TRIM(SRC.ORORG),
        TRIM(SRC.ORDZN),
        TRIM(SRC.ORDRG),
        TRIM(SRC.ORTBRT),
        TRIM(SRC.ORNGU),
        TRIM(SRC.OREFM),
        TRIM(SRC.ORCARF),
        TRIM(SRC.ORUTYP),
        TRIM(SRC.ORFIL)
    FROM #DedupedWithDates SRC
    WHERE NOT EXISTS (
        SELECT 1
        FROM silver.ibmi_incr_cd_order_new TGT
        WHERE TGT.cd_order_load_number = TRIM(SRC.ORODR)
    );

    DROP TABLE #DedupedWithDates;
    DROP TABLE #CdOrdersToDelete;
END