section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "VW_DEDUCTION_HISTORY_DataDestination", IsNewTarget = false], Settings = [Kind = "Manual", AllowCreation = false, ColumnSettings = [Mappings = {[SourceColumnName = "DHEMP", DestinationColumnName = "DHEMP"], [SourceColumnName = "DHRUN", DestinationColumnName = "DHRUN"], [SourceColumnName = "DHBPKG", DestinationColumnName = "DHBPKG"], [SourceColumnName = "DHTYPE", DestinationColumnName = "DHTYPE"], [SourceColumnName = "DHCODE", DestinationColumnName = "DHCODE"], [SourceColumnName = "DHWDCD", DestinationColumnName = "DHWDCD"], [SourceColumnName = "DHPAYD", DestinationColumnName = "DHPAYD"], [SourceColumnName = "DHWEEK", DestinationColumnName = "DHWEEK"], [SourceColumnName = "DHSEQ", DestinationColumnName = "DHSEQ"], [SourceColumnName = "DHDEPT", DestinationColumnName = "DHDEPT"], [SourceColumnName = "DHJOB", DestinationColumnName = "DHJOB"], [SourceColumnName = "DHADRP", DestinationColumnName = "DHADRP"], [SourceColumnName = "DHCHGC", DestinationColumnName = "DHCHGC"], [SourceColumnName = "DHHOLD", DestinationColumnName = "DHHOLD"], [SourceColumnName = "DHDVSN", DestinationColumnName = "DHDVSN"], [SourceColumnName = "DHORD", DestinationColumnName = "DHORD"], [SourceColumnName = "DHDSP", DestinationColumnName = "DHDSP"], [SourceColumnName = "DHUNIT", DestinationColumnName = "DHUNIT"], [SourceColumnName = "DHOWNR", DestinationColumnName = "DHOWNR"], [SourceColumnName = "DHTEXC", DestinationColumnName = "DHTEXC"], [SourceColumnName = "DHTCC", DestinationColumnName = "DHTCC"], [SourceColumnName = "DHWDMP", DestinationColumnName = "DHWDMP"], [SourceColumnName = "DHPYAC", DestinationColumnName = "DHPYAC"], [SourceColumnName = "DHLACT", DestinationColumnName = "DHLACT"], [SourceColumnName = "DHCACT", DestinationColumnName = "DHCACT"], [SourceColumnName = "DHCC1", DestinationColumnName = "DHCC1"], [SourceColumnName = "DHPC1", DestinationColumnName = "DHPC1"], [SourceColumnName = "DHCC2", DestinationColumnName = "DHCC2"], [SourceColumnName = "DHPC2", DestinationColumnName = "DHPC2"], [SourceColumnName = "DHCC3", DestinationColumnName = "DHCC3"], [SourceColumnName = "DHPC3", DestinationColumnName = "DHPC3"], [SourceColumnName = "DHERND", DestinationColumnName = "DHERND"], [SourceColumnName = "DHEBKM", DestinationColumnName = "DHEBKM"], [SourceColumnName = "DHEBKY", DestinationColumnName = "DHEBKY"], [SourceColumnName = "DHCKDT", DestinationColumnName = "DHCKDT"], [SourceColumnName = "DHCKCD", DestinationColumnName = "DHCKCD"], [SourceColumnName = "DHCKNO", DestinationColumnName = "DHCKNO"], [SourceColumnName = "DHPBKM", DestinationColumnName = "DHPBKM"], [SourceColumnName = "DHPBKY", DestinationColumnName = "DHPBKY"], [SourceColumnName = "DHSTAT", DestinationColumnName = "DHSTAT"], [SourceColumnName = "DHVDDT", DestinationColumnName = "DHVDDT"], [SourceColumnName = "DHVBKM", DestinationColumnName = "DHVBKM"], [SourceColumnName = "DHVBKY", DestinationColumnName = "DHVBKY"], [SourceColumnName = "DHAMT", DestinationColumnName = "DHAMT"], [SourceColumnName = "DHAMTA", DestinationColumnName = "DHAMTA"], [SourceColumnName = "DHAMTB", DestinationColumnName = "DHAMTB"], [SourceColumnName = "DHGROS", DestinationColumnName = "DHGROS"], [SourceColumnName = "DHQTY", DestinationColumnName = "DHQTY"], [SourceColumnName = "DHCOVG", DestinationColumnName = "DHCOVG"], [SourceColumnName = "DHPO", DestinationColumnName = "DHPO"], [SourceColumnName = "DHREF", DestinationColumnName = "DHREF"], [SourceColumnName = "DHVNDR", DestinationColumnName = "DHVNDR"], [SourceColumnName = "DHCITY", DestinationColumnName = "DHCITY"], [SourceColumnName = "DHST", DestinationColumnName = "DHST"], [SourceColumnName = "DHAUSR", DestinationColumnName = "DHAUSR"], [SourceColumnName = "DHADAT", DestinationColumnName = "DHADAT"], [SourceColumnName = "DHATIM", DestinationColumnName = "DHATIM"], [SourceColumnName = "DHCALC", DestinationColumnName = "DHCALC"], [SourceColumnName = "DHPCTC", DestinationColumnName = "DHPCTC"], [SourceColumnName = "DHTAXA", DestinationColumnName = "DHTAXA"], [SourceColumnName = "DHPCTB", DestinationColumnName = "DHPCTB"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared VW_DEDUCTION_HISTORY = let
  Source = DB2.Database("S10A3543.STEVENSTRANSPORT.COM:447", "S10A3543", [HierarchicalNavigation = true, Implementation = "Microsoft"]),
  #"Navigation 1" = Source{[Schema = "FABRIC"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Name = "VW_DEDUCTION_HISTORY"]}[Data],
  #"Renamed columns" = Table.RenameColumns(#"Navigation 2", {{"DHEMP#", "DHEMP"}, {"DHORD#", "DHORD"}, {"DHDSP#", "DHDSP"}, {"DHPO#", "DHPO"}, {"DHREF#", "DHREF"}})
in
  #"Renamed columns";
shared VW_DEDUCTION_HISTORY_DataDestination = let
  Pattern = Lakehouse.Contents([CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "a6d2c31b-0b03-4c60-a258-c2664c56fe3d"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "f9a73da1-08e4-4f3d-a67f-74623bfde721"]}[Data],
  TableNavigation = Navigation_2{[Id = "ibmi_deduction_history_bronze", ItemKind = "Table"]}[Data]
in
  TableNavigation;
