CREATE TABLE [bronze].[plsc_pltmhbdp] (

	[PLTHTRUCK] varchar(8000) NULL, 
	[PLTHHBID] bigint NULL, 
	[PLTHTYPE] varchar(8000) NULL, 
	[PLTHRECV] datetime2(6) NULL, 
	[PLTHLOGA] varchar(8000) NULL, 
	[PLTHSPEED] decimal(38,6) NULL, 
	[PLTHODO] decimal(38,6) NULL, 
	[PLTHODOJ] varchar(8000) NULL, 
	[PLTHHEAD] decimal(38,6) NULL, 
	[PLTHIGNS] varchar(8000) NULL, 
	[PLTHRPM] decimal(38,6) NULL, 
	[PLTHENGH] decimal(38,6) NULL, 
	[PLTHENGHJ] varchar(8000) NULL, 
	[PLTHWINM] varchar(8000) NULL, 
	[PLTHACU] varchar(8000) NULL, 
	[PLTHSAT] decimal(38,6) NULL, 
	[PLTHGPSV] varchar(8000) NULL, 
	[PLTHHDOP] varchar(8000) NULL, 
	[PLTHFUEL] decimal(38,6) NULL, 
	[PLTHFUELU] decimal(38,6) NULL, 
	[PLTHLAT] decimal(38,6) NULL, 
	[PLTHLON] decimal(38,6) NULL, 
	[PLTHLOCD] varchar(8000) NULL, 
	[PLTHRPD] decimal(38,6) NULL, 
	[PLTHRUM] varchar(8000) NULL, 
	[PLTHRDIR] varchar(8000) NULL, 
	[PLTHRCITY] varchar(8000) NULL, 
	[PLTHRSTATE] varchar(8000) NULL, 
	[PLTHRCUNTR] varchar(8000) NULL
);