section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "VW_UNITS_DataDestination", IsNewTarget = false], Settings = [Kind = "Manual", AllowCreation = false, ColumnSettings = [Mappings = {[SourceColumnName = "UNUNIT", DestinationColumnName = "UNUNIT"], [SourceColumnName = "UNOWN", DestinationColumnName = "UNOWN"], [SourceColumnName = "UNCO", DestinationColumnName = "UNCO"], [SourceColumnName = "UNDV", DestinationColumnName = "UNDV"], [SourceColumnName = "UNTM", DestinationColumnName = "UNTM"], [SourceColumnName = "UNYEAR", DestinationColumnName = "UNYEAR"], [SourceColumnName = "UNMAKE", DestinationColumnName = "UNMAKE"], [SourceColumnName = "UNSER", DestinationColumnName = "UNSER"], [SourceColumnName = "UNPLAT", DestinationColumnName = "UNPLAT"], [SourceColumnName = "UNPLST", DestinationColumnName = "UNPLST"], [SourceColumnName = "UNTNT", DestinationColumnName = "UNTNT"], [SourceColumnName = "UNHUT", DestinationColumnName = "UNHUT"], [SourceColumnName = "UNTERM", DestinationColumnName = "UNTERM"], [SourceColumnName = "UNCOST", DestinationColumnName = "UNCOST"], [SourceColumnName = "UNINS", DestinationColumnName = "UNINS"], [SourceColumnName = "UNPAYT", DestinationColumnName = "UNPAYT"], [SourceColumnName = "UNPERC", DestinationColumnName = "UNPERC"], [SourceColumnName = "UNLRAT", DestinationColumnName = "UNLRAT"], [SourceColumnName = "UNERAT", DestinationColumnName = "UNERAT"], [SourceColumnName = "UNHIRW", DestinationColumnName = "UNHIRW"], [SourceColumnName = "UNDR1", DestinationColumnName = "UNDR1"], [SourceColumnName = "UNDR2", DestinationColumnName = "UNDR2"], [SourceColumnName = "UNTRL1", DestinationColumnName = "UNTRL1"], [SourceColumnName = "UNPDR1", DestinationColumnName = "UNPDR1"], [SourceColumnName = "UNPDR2", DestinationColumnName = "UNPDR2"], [SourceColumnName = "UNPTR1", DestinationColumnName = "UNPTR1"], [SourceColumnName = "UNSTAT", DestinationColumnName = "UNSTAT"], [SourceColumnName = "UNORD", DestinationColumnName = "UNORD"], [SourceColumnName = "UNDISP", DestinationColumnName = "UNDISP"], [SourceColumnName = "UNPRVO", DestinationColumnName = "UNPRVO"], [SourceColumnName = "UNPDSP", DestinationColumnName = "UNPDSP"], [SourceColumnName = "UNDCTY", DestinationColumnName = "UNDCTY"], [SourceColumnName = "UNDST", DestinationColumnName = "UNDST"], [SourceColumnName = "UNDZN", DestinationColumnName = "UNDZN"], [SourceColumnName = "UNDRG", DestinationColumnName = "UNDRG"], [SourceColumnName = "UNDBEA", DestinationColumnName = "UNDBEA"], [SourceColumnName = "UNDGU", DestinationColumnName = "UNDGU"], [SourceColumnName = "UNDSNM", DestinationColumnName = "UNDSNM"], [SourceColumnName = "UNEWGT", DestinationColumnName = "UNEWGT"], [SourceColumnName = "UNGRWT", DestinationColumnName = "UNGRWT"], [SourceColumnName = "UNETAD", DestinationColumnName = "UNETAD"], [SourceColumnName = "UNETAT", DestinationColumnName = "UNETAT"], [SourceColumnName = "UNECDT", DestinationColumnName = "UNECDT"], [SourceColumnName = "UNCNTD", DestinationColumnName = "UNCNTD"], [SourceColumnName = "UNCNTT", DestinationColumnName = "UNCNTT"], [SourceColumnName = "UNCNTI", DestinationColumnName = "UNCNTI"], [SourceColumnName = "UNCCTY", DestinationColumnName = "UNCCTY"], [SourceColumnName = "UNCST", DestinationColumnName = "UNCST"], [SourceColumnName = "UNCSNM", DestinationColumnName = "UNCSNM"], [SourceColumnName = "UNMESS", DestinationColumnName = "UNMESS"], [SourceColumnName = "UNDEL", DestinationColumnName = "UNDEL"], [SourceColumnName = "UNTYPE", DestinationColumnName = "UNTYPE"], [SourceColumnName = "UNAXLE", DestinationColumnName = "UNAXLE"], [SourceColumnName = "UNFLET", DestinationColumnName = "UNFLET"], [SourceColumnName = "UNDHOR", DestinationColumnName = "UNDHOR"], [SourceColumnName = "UNPREO", DestinationColumnName = "UNPREO"], [SourceColumnName = "UNCMTM", DestinationColumnName = "UNCMTM"], [SourceColumnName = "UNFUEL", DestinationColumnName = "UNFUEL"], [SourceColumnName = "UNAVAS", DestinationColumnName = "UNAVAS"], [SourceColumnName = "UNDARA", DestinationColumnName = "UNDARA"], [SourceColumnName = "UNLHUB", DestinationColumnName = "UNLHUB"], [SourceColumnName = "UNLPRD", DestinationColumnName = "UNLPRD"], [SourceColumnName = "UNLPRT", DestinationColumnName = "UNLPRT"], [SourceColumnName = "UNLGAL", DestinationColumnName = "UNLGAL"], [SourceColumnName = "UNLMPG", DestinationColumnName = "UNLMPG"], [SourceColumnName = "UN1GAL", DestinationColumnName = "UN1GAL"], [SourceColumnName = "UN1MPG", DestinationColumnName = "UN1MPG"], [SourceColumnName = "UN1HUB", DestinationColumnName = "UN1HUB"], [SourceColumnName = "UN1PRD", DestinationColumnName = "UN1PRD"], [SourceColumnName = "UN1PRT", DestinationColumnName = "UN1PRT"], [SourceColumnName = "UNPGAL", DestinationColumnName = "UNPGAL"], [SourceColumnName = "UNPMPG", DestinationColumnName = "UNPMPG"], [SourceColumnName = "UNPHUB", DestinationColumnName = "UNPHUB"], [SourceColumnName = "UNPPRD", DestinationColumnName = "UNPPRD"], [SourceColumnName = "UNPPRT", DestinationColumnName = "UNPPRT"], [SourceColumnName = "UNCOSC", DestinationColumnName = "UNCOSC"], [SourceColumnName = "UNEDIS", DestinationColumnName = "UNEDIS"], [SourceColumnName = "UNNDIS", DestinationColumnName = "UNNDIS"], [SourceColumnName = "UNMULT", DestinationColumnName = "UNMULT"], [SourceColumnName = "UNLEN", DestinationColumnName = "UNLEN"], [SourceColumnName = "UNAXS", DestinationColumnName = "UNAXS"], [SourceColumnName = "UNFLIC", DestinationColumnName = "UNFLIC"], [SourceColumnName = "UNENG", DestinationColumnName = "UNENG"], [SourceColumnName = "UNMISC", DestinationColumnName = "UNMISC"], [SourceColumnName = "UNFCAP", DestinationColumnName = "UNFCAP"], [SourceColumnName = "UNPURD", DestinationColumnName = "UNPURD"], [SourceColumnName = "UNLCOD", DestinationColumnName = "UNLCOD"], [SourceColumnName = "UNWRKC", DestinationColumnName = "UNWRKC"], [SourceColumnName = "UNLSTS", DestinationColumnName = "UNLSTS"], [SourceColumnName = "UNSSNM", DestinationColumnName = "UNSSNM"], [SourceColumnName = "UNNXTL", DestinationColumnName = "UNNXTL"], [SourceColumnName = "UNNSNM", DestinationColumnName = "UNNSNM"], [SourceColumnName = "UNPTA", DestinationColumnName = "UNPTA"], [SourceColumnName = "UNPDA", DestinationColumnName = "UNPDA"], [SourceColumnName = "UNPCDT", DestinationColumnName = "UNPCDT"], [SourceColumnName = "UNSUPR", DestinationColumnName = "UNSUPR"], [SourceColumnName = "UNFMGR", DestinationColumnName = "UNFMGR"], [SourceColumnName = "UNSERV", DestinationColumnName = "UNSERV"], [SourceColumnName = "UNCSTF", DestinationColumnName = "UNCSTF"], [SourceColumnName = "UNCRED", DestinationColumnName = "UNCRED"], [SourceColumnName = "UNCRET", DestinationColumnName = "UNCRET"], [SourceColumnName = "UNCREI", DestinationColumnName = "UNCREI"], [SourceColumnName = "UNUPDD", DestinationColumnName = "UNUPDD"], [SourceColumnName = "UNUPDT", DestinationColumnName = "UNUPDT"], [SourceColumnName = "UNUPDI", DestinationColumnName = "UNUPDI"], [SourceColumnName = "UNOWNT", DestinationColumnName = "UNOWNT"], [SourceColumnName = "UNUBAL", DestinationColumnName = "UNUBAL"], [SourceColumnName = "UNCBAL", DestinationColumnName = "UNCBAL"], [SourceColumnName = "UNCTYT", DestinationColumnName = "UNCTYT"], [SourceColumnName = "UNMODL", DestinationColumnName = "UNMODL"], [SourceColumnName = "UNGATE", DestinationColumnName = "UNGATE"], [SourceColumnName = "UNDCST", DestinationColumnName = "UNDCST"], [SourceColumnName = "UNEDFL", DestinationColumnName = "UNEDFL"], [SourceColumnName = "UNTYP2", DestinationColumnName = "UNTYP2"], [SourceColumnName = "UNEFM", DestinationColumnName = "UNEFM"], [SourceColumnName = "UNAVLD", DestinationColumnName = "UNAVLD"], [SourceColumnName = "UNHDTE", DestinationColumnName = "UNHDTE"], [SourceColumnName = "UNFIL", DestinationColumnName = "UNFIL"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared VW_UNITS = let
  Source = DB2.Database("S10A3543.STEVENSTRANSPORT.COM:447", "S10A3543", [HierarchicalNavigation = true, Implementation = "Microsoft"]),
  #"Navigation 1" = Source{[Schema = "FABRIC"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Name = "VW_UNITS"]}[Data],
  #"Renamed columns" = Table.RenameColumns(#"Navigation 2", {{"UNCO#", "UNCO"}, {"UNDV#", "UNDV"}, {"UNTM#", "UNTM"}, {"UNORD#", "UNORD"}})
in
  #"Renamed columns";
shared VW_UNITS_DataDestination = let
  Pattern = Lakehouse.Contents([CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "a6d2c31b-0b03-4c60-a258-c2664c56fe3d"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "f9a73da1-08e4-4f3d-a67f-74623bfde721"]}[Data],
  TableNavigation = Navigation_2{[Id = "ibmi_unit_bronze", ItemKind = "Table"]}[Data]
in
  TableNavigation;
