[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "VW_PLSC_PLTDRPMP_DataDestination", IsNewTarget = false], Settings = [Kind = "Manual", AllowCreation = false, ColumnSettings = [Mappings = {[SourceColumnName = "PLPTRUCK", DestinationColumnName = "PLPTRUCK"], [SourceColumnName = "PLPDRVR1", DestinationColumnName = "PLPDRVR1"], [SourceColumnName = "PLPDRVR2", DestinationColumnName = "PLPDRVR2"], [SourceColumnName = "PLPORDER", DestinationColumnName = "PLPORDER"], [SourceColumnName = "PLPDISP#", DestinationColumnName = "PLPDISP#"], [SourceColumnName = "PLPTYPE", DestinationColumnName = "PLPTYPE"], [SourceColumnName = "PLPRECVT", DestinationColumnName = "PLPRECVT"], [SourceColumnName = "PLPLOGDT", DestinationColumnName = "PLPLOGDT"], [SourceColumnName = "PLPBEGINT", DestinationColumnName = "PLPBEGINT"], [SourceColumnName = "PLPENDT", DestinationColumnName = "PLPENDT"], [SourceColumnName = "PLPOVRSPDC", DestinationColumnName = "PLPOVRSPDC"], [SourceColumnName = "PLPOVRSPDT", DestinationColumnName = "PLPOVRSPDT"], [SourceColumnName = "PLPDRIVED", DestinationColumnName = "PLPDRIVED"], [SourceColumnName = "PLPDRIVET", DestinationColumnName = "PLPDRIVET"], [SourceColumnName = "PLPINTIDLT", DestinationColumnName = "PLPINTIDLT"], [SourceColumnName = "PLPSHTIDLT", DestinationColumnName = "PLPSHTIDLT"], [SourceColumnName = "PLPSTPIDLT", DestinationColumnName = "PLPSTPIDLT"], [SourceColumnName = "PLPTLIDLET", DestinationColumnName = "PLPTLIDLET"], [SourceColumnName = "PLPCRSCTLT", DestinationColumnName = "PLPCRSCTLT"], [SourceColumnName = "PLPOVRRPMC", DestinationColumnName = "PLPOVRRPMC"], [SourceColumnName = "PLPENGREDC", DestinationColumnName = "PLPENGREDC"], [SourceColumnName = "PLPEXCRPMT", DestinationColumnName = "PLPEXCRPMT"], [SourceColumnName = "PLPTPGEART", DestinationColumnName = "PLPTPGEART"], [SourceColumnName = "PLPPTOT", DestinationColumnName = "PLPPTOT"], [SourceColumnName = "PLPEXCOVST", DestinationColumnName = "PLPEXCOVST"], [SourceColumnName = "PLPSHIDLFU", DestinationColumnName = "PLPSHIDLFU"], [SourceColumnName = "PLPTLIDLFU", DestinationColumnName = "PLPTLIDLFU"], [SourceColumnName = "PLPTLFUELU", DestinationColumnName = "PLPTLFUELU"], [SourceColumnName = "PLPOVRPMMV", DestinationColumnName = "PLPOVRPMMV"], [SourceColumnName = "PLPOVRRPMT", DestinationColumnName = "PLPOVRRPMT"], [SourceColumnName = "PLPSTRODOM", DestinationColumnName = "PLPSTRODOM"], [SourceColumnName = "PLPTLTRIPC", DestinationColumnName = "PLPTLTRIPC"], [SourceColumnName = "PLPPTOFLU", DestinationColumnName = "PLPPTOFLU"], [SourceColumnName = "PLPMOVFLU", DestinationColumnName = "PLPMOVFLU"], [SourceColumnName = "PLPMOVINGT", DestinationColumnName = "PLPMOVINGT"], [SourceColumnName = "PLPENGINET", DestinationColumnName = "PLPENGINET"], [SourceColumnName = "PLPORPMMXT", DestinationColumnName = "PLPORPMMXT"], [SourceColumnName = "PLPOSPDMXT", DestinationColumnName = "PLPOSPDMXT"], [SourceColumnName = "PLPSTPIDFU", DestinationColumnName = "PLPSTPIDFU"], [SourceColumnName = "PLPCSOGERT", DestinationColumnName = "PLPCSOGERT"], [SourceColumnName = "PLPAVENGLT", DestinationColumnName = "PLPAVENGLT"], [SourceColumnName = "PLPGEARDTS", DestinationColumnName = "PLPGEARDTS"], [SourceColumnName = "PLPPERFGPI", DestinationColumnName = "PLPPERFGPI"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared VW_PLSC_PLTDRPMP = let
  Source = DB2.Database("S10A3543.STEVENSTRANSPORT.COM:447", "S10A3543", [HierarchicalNavigation = true, Implementation = "Microsoft"]),
  #"Navigation 1" = Source{[Schema = "FABRIC"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Name = "VW_PLSC_PLTDRPMP"]}[Data],
  #"Trimmed text" = Table.TransformColumns(#"Navigation 2", {{"PLPTRUCK", each Text.Trim(_), type text}, {"PLPDRVR1", each Text.Trim(_), type text}, {"PLPDRVR2", each Text.Trim(_), type text}, {"PLPORDER", each Text.Trim(_), type text}, {"PLPDISP#", each Text.Trim(_), type text}, {"PLPTYPE", each Text.Trim(_), type text}, {"PLPGEARDTS", each Text.Trim(_), type text}, {"PLPPERFGPI", each Text.Trim(_), type text}}),
  #"Removed columns" = Table.RemoveColumns(#"Trimmed text", {"PLPSPDRPM1", "PLPSPDRPM2", "PLPSPDRPM3", "PLPSPDRPM4", "PLPSPDRPM5", "PLPSPDRPM6", "PLPSPDRPM7", "PLPSPDRPM8", "PLPSPDRPM9"})
in
  #"Removed columns";
shared VW_PLSC_PLTDRPMP_DataDestination = let
  Pattern = Lakehouse.Contents([HierarchicalNavigation = null, CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "a6d2c31b-0b03-4c60-a258-c2664c56fe3d"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "f9a73da1-08e4-4f3d-a67f-74623bfde721"]}[Data],
  TableNavigation = Navigation_2{[Id = "PLSC_PLTDRPMP", ItemKind = "Table"]}[Data]
in
  TableNavigation;
