section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "gold dim_date_DataDestination", IsNewTarget = true], Settings = [Kind = "Manual", AllowCreation = true, ColumnSettings = [Mappings = {[SourceColumnName = "date_key_pk", DestinationColumnName = "date_key_pk"], [SourceColumnName = "date_julian", DestinationColumnName = "date_julian"], [SourceColumnName = "date_db2_julian", DestinationColumnName = "date_db2_julian"], [SourceColumnName = "date_ordinal", DestinationColumnName = "date_ordinal"], [SourceColumnName = "the_day", DestinationColumnName = "the_day"], [SourceColumnName = "the_day_suffix", DestinationColumnName = "the_day_suffix"], [SourceColumnName = "the_day_name", DestinationColumnName = "the_day_name"], [SourceColumnName = "the_day_of_week", DestinationColumnName = "the_day_of_week"], [SourceColumnName = "the_day_of_week_in_month", DestinationColumnName = "the_day_of_week_in_month"], [SourceColumnName = "the_day_of_year", DestinationColumnName = "the_day_of_year"], [SourceColumnName = "is_weekend", DestinationColumnName = "is_weekend"], [SourceColumnName = "the_week", DestinationColumnName = "the_week"], [SourceColumnName = "the_iso_week", DestinationColumnName = "the_iso_week"], [SourceColumnName = "the_first_of_week", DestinationColumnName = "the_first_of_week"], [SourceColumnName = "the_last_of_week", DestinationColumnName = "the_last_of_week"], [SourceColumnName = "the_week_of_month", DestinationColumnName = "the_week_of_month"], [SourceColumnName = "the_month_number", DestinationColumnName = "the_month_number"], [SourceColumnName = "the_month_name", DestinationColumnName = "the_month_name"], [SourceColumnName = "the_first_of_month_date", DestinationColumnName = "the_first_of_month_date"], [SourceColumnName = "the_last_of_month_date", DestinationColumnName = "the_last_of_month_date"], [SourceColumnName = "the_first_of_next_month_date", DestinationColumnName = "the_first_of_next_month_date"], [SourceColumnName = "the_last_of_next_month_date", DestinationColumnName = "the_last_of_next_month_date"], [SourceColumnName = "the_quarter", DestinationColumnName = "the_quarter"], [SourceColumnName = "the_first_of_quarter_date", DestinationColumnName = "the_first_of_quarter_date"], [SourceColumnName = "the_last_of_quarter_date", DestinationColumnName = "the_last_of_quarter_date"], [SourceColumnName = "the_year", DestinationColumnName = "the_year"], [SourceColumnName = "the_iso_year", DestinationColumnName = "the_iso_year"], [SourceColumnName = "the_first_of_year", DestinationColumnName = "the_first_of_year"], [SourceColumnName = "the_last_of_year", DestinationColumnName = "the_last_of_year"], [SourceColumnName = "is_leap_year", DestinationColumnName = "is_leap_year"], [SourceColumnName = "has_53_weeks", DestinationColumnName = "has_53_weeks"], [SourceColumnName = "has_53_iso_weeks", DestinationColumnName = "has_53_iso_weeks"], [SourceColumnName = "mmyyyy", DestinationColumnName = "mmyyyy"], [SourceColumnName = "mm_dd_yyyy", DestinationColumnName = "mm_dd_yyyy"], [SourceColumnName = "dd_mm_yyyy", DestinationColumnName = "dd_mm_yyyy"], [SourceColumnName = "yyyymmdd", DestinationColumnName = "yyyymmdd"], [SourceColumnName = "yyyy_mm_dd", DestinationColumnName = "yyyy_mm_dd"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared #"gold dim_date" = let
  Source = Sql.Database("azsqlsrv-scus-01.database.windows.net", "azrsqldb_scus_edw"),
  #"Navigation 1" = Source{[Schema = "gold", Item = "dim_date"]}[Data],
  #"Changed column type" = Table.TransformColumnTypes(#"Navigation 1", {{"the_day_of_week_in_month", Int64.Type}, {"the_week_of_month", Int64.Type}, {"is_weekend", type logical}, {"has_53_weeks", type logical}, {"has_53_iso_weeks", type logical}})
in
  #"Changed column type";
shared #"gold dim_date_DataDestination" = let
  Pattern = Fabric.Warehouse([CreateNavigationProperties = false]),
  Navigation_1 = Pattern{[workspaceId = "a6d2c31b-0b03-4c60-a258-c2664c56fe3d"]}[Data],
  Navigation_2 = Navigation_1{[warehouseId = "f8578495-391e-4e7e-b791-4949397ba86f"]}[Data],
  TableNavigation = Navigation_2{[Item = "dim_date", Schema = "dbo"]}?[Data]?
in
  TableNavigation;
