section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "VW_CUSTOMER_DataDestination", IsNewTarget = false], Settings = [Kind = "Manual", AllowCreation = false, ColumnSettings = [Mappings = {[SourceColumnName = "CUCODE", DestinationColumnName = "CUCODE"], [SourceColumnName = "CUDLT", DestinationColumnName = "CUDLT"], [SourceColumnName = "CUNAME", DestinationColumnName = "CUNAME"], [SourceColumnName = "CUBAD1", DestinationColumnName = "CUBAD1"], [SourceColumnName = "CUBAD2", DestinationColumnName = "CUBAD2"], [SourceColumnName = "CUBCTY", DestinationColumnName = "CUBCTY"], [SourceColumnName = "CUBST", DestinationColumnName = "CUBST"], [SourceColumnName = "CUBZIP", DestinationColumnName = "CUBZIP"], [SourceColumnName = "CUBZP2", DestinationColumnName = "CUBZP2"], [SourceColumnName = "CUBCTC", DestinationColumnName = "CUBCTC"], [SourceColumnName = "CUBLCD", DestinationColumnName = "CUBLCD"], [SourceColumnName = "CUTERR", DestinationColumnName = "CUTERR"], [SourceColumnName = "CUSLMN", DestinationColumnName = "CUSLMN"], [SourceColumnName = "CUSHPC", DestinationColumnName = "CUSHPC"], [SourceColumnName = "CULACT", DestinationColumnName = "CULACT"], [SourceColumnName = "CUTRIP", DestinationColumnName = "CUTRIP"], [SourceColumnName = "CUSAC", DestinationColumnName = "CUSAC"], [SourceColumnName = "CUSPHN", DestinationColumnName = "CUSPHN"], [SourceColumnName = "CUSNMX", DestinationColumnName = "CUSNMX"], [SourceColumnName = "CUFAC", DestinationColumnName = "CUFAC"], [SourceColumnName = "CUFPHN", DestinationColumnName = "CUFPHN"], [SourceColumnName = "CUCRCD", DestinationColumnName = "CUCRCD"], [SourceColumnName = "CUCNTY", DestinationColumnName = "CUCNTY"], [SourceColumnName = "CUSTMF", DestinationColumnName = "CUSTMF"], [SourceColumnName = "CUINVF", DestinationColumnName = "CUINVF"], [SourceColumnName = "CUCUR", DestinationColumnName = "CUCUR"], [SourceColumnName = "CURANK", DestinationColumnName = "CURANK"], [SourceColumnName = "CUINTR", DestinationColumnName = "CUINTR"], [SourceColumnName = "CUNCUS", DestinationColumnName = "CUNCUS"], [SourceColumnName = "CUCRET", DestinationColumnName = "CUCRET"], [SourceColumnName = "CUCREI", DestinationColumnName = "CUCREI"], [SourceColumnName = "CUUPDD", DestinationColumnName = "CUUPDD"], [SourceColumnName = "CUUPDT", DestinationColumnName = "CUUPDT"], [SourceColumnName = "CUUPDI", DestinationColumnName = "CUUPDI"], [SourceColumnName = "CUCTLS", DestinationColumnName = "CUCTLS"], [SourceColumnName = "CUCODS", DestinationColumnName = "CUCODS"], [SourceColumnName = "CUCODB", DestinationColumnName = "CUCODB"], [SourceColumnName = "CUCODL", DestinationColumnName = "CUCODL"], [SourceColumnName = "CUCODC", DestinationColumnName = "CUCODC"], [SourceColumnName = "CUEDI", DestinationColumnName = "CUEDI"], [SourceColumnName = "CUCOMC", DestinationColumnName = "CUCOMC"], [SourceColumnName = "CUAREA", DestinationColumnName = "CUAREA"], [SourceColumnName = "CUSHNM", DestinationColumnName = "CUSHNM"], [SourceColumnName = "CUSERB", DestinationColumnName = "CUSERB"], [SourceColumnName = "CUSERA", DestinationColumnName = "CUSERA"], [SourceColumnName = "CUTARE", DestinationColumnName = "CUTARE"], [SourceColumnName = "CUPAYF", DestinationColumnName = "CUPAYF"], [SourceColumnName = "CUCOSC", DestinationColumnName = "CUCOSC"], [SourceColumnName = "CUSVRP", DestinationColumnName = "CUSVRP"], [SourceColumnName = "CUCO", DestinationColumnName = "CUCO"], [SourceColumnName = "CUDV", DestinationColumnName = "CUDV"], [SourceColumnName = "CUTM", DestinationColumnName = "CUTM"], [SourceColumnName = "CUBLTP", DestinationColumnName = "CUBLTP"], [SourceColumnName = "CUEDI2", DestinationColumnName = "CUEDI2"], [SourceColumnName = "CUEDI3", DestinationColumnName = "CUEDI3"], [SourceColumnName = "CUEDMB", DestinationColumnName = "CUEDMB"], [SourceColumnName = "CUBBOC", DestinationColumnName = "CUBBOC"], [SourceColumnName = "CUJIT", DestinationColumnName = "CUJIT"], [SourceColumnName = "CUTEST", DestinationColumnName = "CUTEST"], [SourceColumnName = "CUGSTC", DestinationColumnName = "CUGSTC"], [SourceColumnName = "CUPBIL", DestinationColumnName = "CUPBIL"], [SourceColumnName = "CUCCBT", DestinationColumnName = "CUCCBT"], [SourceColumnName = "CUCCET", DestinationColumnName = "CUCCET"], [SourceColumnName = "CUJCHR", DestinationColumnName = "CUJCHR"], [SourceColumnName = "CUCHR", DestinationColumnName = "CUCHR"], [SourceColumnName = "CUPLN", DestinationColumnName = "CUPLN"], [SourceColumnName = "CUCYL", DestinationColumnName = "CUCYL"], [SourceColumnName = "CUCDF", DestinationColumnName = "CUCDF"], [SourceColumnName = "CUEFM", DestinationColumnName = "CUEFM"], [SourceColumnName = "CUCARF", DestinationColumnName = "CUCARF"], [SourceColumnName = "CUHAZC", DestinationColumnName = "CUHAZC"], [SourceColumnName = "CUSF30", DestinationColumnName = "CUSF30"], [SourceColumnName = "CUFIL", DestinationColumnName = "CUFIL"], [SourceColumnName = "CULMRK", DestinationColumnName = "CULMRK"], [SourceColumnName = "CULMPO", DestinationColumnName = "CULMPO"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared VW_CUSTOMER = let
  Source = DB2.Database("S10A3543.STEVENSTRANSPORT.COM:447", "S10A3543", [HierarchicalNavigation = true, Implementation = "Microsoft"]),
  #"Navigation 1" = Source{[Schema = "FABRIC"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Name = "VW_CUSTOMER"]}[Data],
  #"Renamed columns" = Table.RenameColumns(#"Navigation 2", {{"CUCO#", "CUCO"}, {"CUDV#", "CUDV"}, {"CUTM#", "CUTM"}})
in
  #"Renamed columns";
shared VW_CUSTOMER_DataDestination = let
  Pattern = Lakehouse.Contents([CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "a6d2c31b-0b03-4c60-a258-c2664c56fe3d"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "f9a73da1-08e4-4f3d-a67f-74623bfde721"]}[Data],
  TableNavigation = Navigation_2{[Id = "ibmi_customer_bronze", ItemKind = "Table"]}[Data]
in
  TableNavigation;
