[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "silver ibmi_unit_DataDestination", IsNewTarget = true], Settings = [Kind = "Manual", AllowCreation = true, ColumnSettings = [Mappings = {[SourceColumnName = "unit_truck_number", DestinationColumnName = "unit_truck_number"], [SourceColumnName = "unit_owner_code", DestinationColumnName = "unit_owner_code"], [SourceColumnName = "unit_truck_division_code", DestinationColumnName = "unit_truck_division_code"], [SourceColumnName = "unit_year", DestinationColumnName = "unit_year"], [SourceColumnName = "unit_make", DestinationColumnName = "unit_make"], [SourceColumnName = "unit_vin", DestinationColumnName = "unit_vin"], [SourceColumnName = "unit_base_license_plate", DestinationColumnName = "unit_base_license_plate"], [SourceColumnName = "unit_base_state", DestinationColumnName = "unit_base_state"], [SourceColumnName = "unit_new_york_license", DestinationColumnName = "unit_new_york_license"], [SourceColumnName = "unit_other", DestinationColumnName = "unit_other"], [SourceColumnName = "unit_term_date", DestinationColumnName = "unit_term_date"], [SourceColumnName = "unit_pay_type", DestinationColumnName = "unit_pay_type"], [SourceColumnName = "unit_hire_date", DestinationColumnName = "unit_hire_date"], [SourceColumnName = "unit_seat_1_driver_code", DestinationColumnName = "unit_seat_1_driver_code"], [SourceColumnName = "unit_seat_2_driver_code", DestinationColumnName = "unit_seat_2_driver_code"], [SourceColumnName = "unit_trailer_1_code", DestinationColumnName = "unit_trailer_1_code"], [SourceColumnName = "unit_previous_seat_1_driver_code", DestinationColumnName = "unit_previous_seat_1_driver_code"], [SourceColumnName = "unit_previous_seat_2_driver_code", DestinationColumnName = "unit_previous_seat_2_driver_code"], [SourceColumnName = "unit_previous_trailer_1_code", DestinationColumnName = "unit_previous_trailer_1_code"], [SourceColumnName = "unit_status_code", DestinationColumnName = "unit_status_code"], [SourceColumnName = "unit_current_load", DestinationColumnName = "unit_current_load"], [SourceColumnName = "unit_current_dispatch", DestinationColumnName = "unit_current_dispatch"], [SourceColumnName = "unit_previous_load", DestinationColumnName = "unit_previous_load"], [SourceColumnName = "unit_previous_dispatch", DestinationColumnName = "unit_previous_dispatch"], [SourceColumnName = "unit_destination_city_code", DestinationColumnName = "unit_destination_city_code"], [SourceColumnName = "unit_destination_state", DestinationColumnName = "unit_destination_state"], [SourceColumnName = "unit_destination_region_code", DestinationColumnName = "unit_destination_region_code"], [SourceColumnName = "unit_destination_bea_code", DestinationColumnName = "unit_destination_bea_code"], [SourceColumnName = "unit_destination_gu_code", DestinationColumnName = "unit_destination_gu_code"], [SourceColumnName = "unit_destination_city_short_description", DestinationColumnName = "unit_destination_city_short_description"], [SourceColumnName = "unit_empty_weight", DestinationColumnName = "unit_empty_weight"], [SourceColumnName = "unit_gross_weight", DestinationColumnName = "unit_gross_weight"], [SourceColumnName = "unit_eta_date", DestinationColumnName = "unit_eta_date"], [SourceColumnName = "unit_eta_change_date", DestinationColumnName = "unit_eta_change_date"], [SourceColumnName = "unit_contact_date", DestinationColumnName = "unit_contact_date"], [SourceColumnName = "unit_contact_initials", DestinationColumnName = "unit_contact_initials"], [SourceColumnName = "unit_contact_city_code", DestinationColumnName = "unit_contact_city_code"], [SourceColumnName = "unit_contact_state", DestinationColumnName = "unit_contact_state"], [SourceColumnName = "unit_contact_city_short_description", DestinationColumnName = "unit_contact_city_short_description"], [SourceColumnName = "has_message_flag", DestinationColumnName = "has_message_flag"], [SourceColumnName = "is_truck_deleted", DestinationColumnName = "is_truck_deleted"], [SourceColumnName = "unit_truck_type", DestinationColumnName = "unit_truck_type"], [SourceColumnName = "unit_axle_count", DestinationColumnName = "unit_axle_count"], [SourceColumnName = "unit_fleet_code", DestinationColumnName = "unit_fleet_code"], [SourceColumnName = "unit_preplan_load", DestinationColumnName = "unit_preplan_load"], [SourceColumnName = "is_preplan_committed", DestinationColumnName = "is_preplan_committed"], [SourceColumnName = "unit_fuel_type_code", DestinationColumnName = "unit_fuel_type_code"], [SourceColumnName = "has_avas_code", DestinationColumnName = "has_avas_code"], [SourceColumnName = "unit_destination_area_code", DestinationColumnName = "unit_destination_area_code"], [SourceColumnName = "unit_lastest_hub_miles", DestinationColumnName = "unit_lastest_hub_miles"], [SourceColumnName = "unit_lastest_purchase_date", DestinationColumnName = "unit_lastest_purchase_date"], [SourceColumnName = "unit_first_purchase_date", DestinationColumnName = "unit_first_purchase_date"], [SourceColumnName = "UNPGAL", DestinationColumnName = "UNPGAL"], [SourceColumnName = "UNPMPG", DestinationColumnName = "UNPMPG"], [SourceColumnName = "unit_previous_hub_miles", DestinationColumnName = "unit_previous_hub_miles"], [SourceColumnName = "unit_previous_purchase_date", DestinationColumnName = "unit_previous_purchase_date"], [SourceColumnName = "unit_latitude", DestinationColumnName = "unit_latitude"], [SourceColumnName = "unit_longitude", DestinationColumnName = "unit_longitude"], [SourceColumnName = "has_fleet_license", DestinationColumnName = "has_fleet_license"], [SourceColumnName = "unit_2_character_code", DestinationColumnName = "unit_2_character_code"], [SourceColumnName = "unit_last_satalite_location", DestinationColumnName = "unit_last_satalite_location"], [SourceColumnName = "unit_last_satalite_location_short_name", DestinationColumnName = "unit_last_satalite_location_short_name"], [SourceColumnName = "unit_next_stop_short_name", DestinationColumnName = "unit_next_stop_short_name"], [SourceColumnName = "unit_proj_avail_date", DestinationColumnName = "unit_proj_avail_date"], [SourceColumnName = "unit_pta_change_date", DestinationColumnName = "unit_pta_change_date"], [SourceColumnName = "unit_dm_code", DestinationColumnName = "unit_dm_code"], [SourceColumnName = "unit_dmol_code", DestinationColumnName = "unit_dmol_code"], [SourceColumnName = "is_customer_site_flagged", DestinationColumnName = "is_customer_site_flagged"], [SourceColumnName = "unit_last_update_date", DestinationColumnName = "unit_last_update_date"], [SourceColumnName = "unit_last_update_initials", DestinationColumnName = "unit_last_update_initials"], [SourceColumnName = "is_city_truck", DestinationColumnName = "is_city_truck"], [SourceColumnName = "unit_model_code", DestinationColumnName = "unit_model_code"], [SourceColumnName = "unit_gate_check_location", DestinationColumnName = "unit_gate_check_location"], [SourceColumnName = "unit_dedicated_customer_code", DestinationColumnName = "unit_dedicated_customer_code"], [SourceColumnName = "unit_subtype", DestinationColumnName = "unit_subtype"], [SourceColumnName = "is_available_for_limited_dispatch", DestinationColumnName = "is_available_for_limited_dispatch"], [SourceColumnName = "unit_temp_hold_date", DestinationColumnName = "unit_temp_hold_date"], [SourceColumnName = "unit_truck_sold_flag", DestinationColumnName = "unit_truck_sold_flag"], [SourceColumnName = "has_jake", DestinationColumnName = "has_jake"], [SourceColumnName = "has_cruise", DestinationColumnName = "has_cruise"], [SourceColumnName = "unit_speed_control", DestinationColumnName = "unit_speed_control"], [SourceColumnName = "has_esp", DestinationColumnName = "has_esp"], [SourceColumnName = "has_apu", DestinationColumnName = "has_apu"], [SourceColumnName = "is_carbon_compliant", DestinationColumnName = "is_carbon_compliant"], [SourceColumnName = "has_team_gone_solo", DestinationColumnName = "has_team_gone_solo"], [SourceColumnName = "snapshotDateUtc", DestinationColumnName = "snapshotDateUtc"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared #"silver ibmi_unit" = let
  Source = Fabric.Warehouse(null),
  Navigation = Source{[workspaceId = "a6d2c31b-0b03-4c60-a258-c2664c56fe3d"]}[Data],
  #"Navigation 1" = Navigation{[warehouseId = "f8578495-391e-4e7e-b791-4949397ba86f"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Schema = "silver", Item = "ibmi_unit"]}[Data],

  // Filter per your SQL WHERE clause
  #"Filtered Rows" =
    Table.SelectRows(
      #"Navigation 2",
      each
        [unit_seat_1_driver_code] = "" and
        [is_truck_deleted] = "FALSE" and
        List.Contains({"ST","CD","AL"}, [unit_fleet_code]) and
        not List.Contains({"34","84","85"}, [unit_truck_division_code])
    ),

  // Add snapshot timestamp (UTC is safest for consistency)
  #"Added SnapshotTs" =
    Table.AddColumn(#"Filtered Rows", "snapshotTsUtc", each DateTimeZone.UtcNow(), type datetimezone),

  // Optional: also add a date column for easy partitioning/filtering in reports
  #"Added SnapshotDate" =
    Table.AddColumn(#"Added SnapshotTs", "snapshotDateUtc", each Date.From(DateTimeZone.UtcNow()), type date)

in
  #"Added SnapshotDate";
shared #"silver ibmi_unit_DataDestination" = let
  Pattern = Fabric.Warehouse([HierarchicalNavigation = null, CreateNavigationProperties = false]),
  Navigation_1 = Pattern{[workspaceId = "a6d2c31b-0b03-4c60-a258-c2664c56fe3d"]}[Data],
  Navigation_2 = Navigation_1{[warehouseId = "f8578495-391e-4e7e-b791-4949397ba86f"]}[Data],
  TableNavigation = Navigation_2{[Item = "ibmi_open_truck_snapshot", Schema = "dbo"]}?[Data]?
in
  TableNavigation;
