[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "VW_INCR_INCR_UTLFILE_DataDestination", IsNewTarget = false], Settings = [Kind = "Manual", AllowCreation = false, ColumnSettings = [Mappings = {[SourceColumnName = "UWUNIT", DestinationColumnName = "UWUNIT"], [SourceColumnName = "UWCODE", DestinationColumnName = "UWCODE"], [SourceColumnName = "UWTYPE", DestinationColumnName = "UWTYPE"], [SourceColumnName = "UWSUPR", DestinationColumnName = "UWSUPR"], [SourceColumnName = "UWDMGR", DestinationColumnName = "UWDMGR"], [SourceColumnName = "UWFMGR", DestinationColumnName = "UWFMGR"], [SourceColumnName = "UWSFMG", DestinationColumnName = "UWSFMG"], [SourceColumnName = "UWCOUN", DestinationColumnName = "UWCOUN"], [SourceColumnName = "UWSEAT", DestinationColumnName = "UWSEAT"], [SourceColumnName = "UWDRS1", DestinationColumnName = "UWDRS1"], [SourceColumnName = "UWDRS2", DestinationColumnName = "UWDRS2"], [SourceColumnName = "UWTLVL", DestinationColumnName = "UWTLVL"], [SourceColumnName = "UWTMYN", DestinationColumnName = "UWTMYN"], [SourceColumnName = "UWTRTM", DestinationColumnName = "UWTRTM"], [SourceColumnName = "UWMILS", DestinationColumnName = "UWMILS"], [SourceColumnName = "UWAMLS", DestinationColumnName = "UWAMLS"], [SourceColumnName = "UWGOAL", DestinationColumnName = "UWGOAL"], [SourceColumnName = "UWPERF", DestinationColumnName = "UWPERF"], [SourceColumnName = "UWUDAT", DestinationColumnName = "UWUDAT"], [SourceColumnName = "UWPDA", DestinationColumnName = "UWPDA"], [SourceColumnName = "UWPTA", DestinationColumnName = "UWPTA"], [SourceColumnName = "UWWEEK", DestinationColumnName = "UWWEEK"], [SourceColumnName = "UWPRD", DestinationColumnName = "UWPRD"], [SourceColumnName = "UWYEAR", DestinationColumnName = "UWYEAR"], [SourceColumnName = "UWHOME", DestinationColumnName = "UWHOME"], [SourceColumnName = "UWHOLD", DestinationColumnName = "UWHOLD"], [SourceColumnName = "UWBRKD", DestinationColumnName = "UWBRKD"], [SourceColumnName = "UWFLAG", DestinationColumnName = "UWFLAG"], [SourceColumnName = "UWDATE", DestinationColumnName = "UWDATE"], [SourceColumnName = "UWTRK", DestinationColumnName = "UWTRK"], [SourceColumnName = "UWLOAD", DestinationColumnName = "UWLOAD"], [SourceColumnName = "UWGRHD", DestinationColumnName = "UWGRHD"], [SourceColumnName = "UWOMIT", DestinationColumnName = "UWOMIT"], [SourceColumnName = "UWDIV", DestinationColumnName = "UWDIV"], [SourceColumnName = "UWRDO", DestinationColumnName = "UWRDO"], [SourceColumnName = "UWTRNR", DestinationColumnName = "UWTRNR"], [SourceColumnName = "UWTRAV", DestinationColumnName = "UWTRAV"], [SourceColumnName = "UWTRCD", DestinationColumnName = "UWTRCD"], [SourceColumnName = "UWCNDV", DestinationColumnName = "UWCNDV"], [SourceColumnName = "UWDAT2", DestinationColumnName = "UWDAT2"], [SourceColumnName = "UWCMZN", DestinationColumnName = "UWCMZN"], [SourceColumnName = "UWDATJ", DestinationColumnName = "UWDATJ"], [SourceColumnName = "UWYARD", DestinationColumnName = "UWYARD"], [SourceColumnName = "UWBUNT", DestinationColumnName = "UWBUNT"], [SourceColumnName = "UWXFLD", DestinationColumnName = "UWXFLD"], [SourceColumnName = "recordNumber", DestinationColumnName = "recordNumber"], [SourceColumnName = "loadDate", DestinationColumnName = "loadDate"], [SourceColumnName = "refreshDate", DestinationColumnName = "refreshDate"], [SourceColumnName = "sourceSystem", DestinationColumnName = "sourceSystem"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared VW_INCR_INCR_UTLFILE = let
  Source = DB2.Database("S10A3543.STEVENSTRANSPORT.COM:447", "S10A3543", [HierarchicalNavigation = true, Implementation = "Microsoft"]),
  #"Navigation 1" = Source{[Schema = "FABRIC"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Name = "VW_INCR_UTLFILE"]}[Data],
  #"Renamedcolumns" = Table.RenameColumns(#"Navigation 2", {{"UWPRD#", "UWPRD"}, {"UWTRK#", "UWTRK"}, {"UWDIV#", "UWDIV"}, {"UWRDO#", "UWRDO"}}),
    AddRecordNumber = Table.AddIndexColumn(Renamedcolumns, "recordNumber", 1, 1, Int64.Type),
    AddLoadDate = Table.AddColumn(AddRecordNumber, "loadDate", each DateTime.LocalNow(), type datetime),
    AddRefreshDate = Table.AddColumn(AddLoadDate, "refreshDate", each Date.From(DateTime.LocalNow()), type date),
    AddSourceSystem = Table.AddColumn(AddRefreshDate, "sourceSystem", each "IBM", type text)

in
    AddSourceSystem;
shared VW_INCR_INCR_UTLFILE_DataDestination = let
  Pattern = Lakehouse.Contents([HierarchicalNavigation = null, CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "a6d2c31b-0b03-4c60-a258-c2664c56fe3d"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "f9a73da1-08e4-4f3d-a67f-74623bfde721"]}[Data],
  TableNavigation = Navigation_2{[Id = "ibmi_incr_utlfile_bronze", ItemKind = "Table"]}[Data]
in
  TableNavigation;
