section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "Query_DataDestination", IsNewTarget = true], Settings = [Kind = "Manual", AllowCreation = true, ColumnSettings = [Mappings = {[SourceColumnName = "id", DestinationColumnName = "id"], [SourceColumnName = "group", DestinationColumnName = "group"], [SourceColumnName = "ro_group_hierarchy", DestinationColumnName = "ro_group_hierarchy"], [SourceColumnName = "vin", DestinationColumnName = "vin"], [SourceColumnName = "unit_number", DestinationColumnName = "unit_number"], [SourceColumnName = "unit_type", DestinationColumnName = "unit_type"], [SourceColumnName = "custom_asset_id", DestinationColumnName = "custom_asset_id"], [SourceColumnName = "vendor_name", DestinationColumnName = "vendor_name"], [SourceColumnName = "vendor_company_id", DestinationColumnName = "vendor_company_id"], [SourceColumnName = "vendor_city", DestinationColumnName = "vendor_city"], [SourceColumnName = "vendor_state", DestinationColumnName = "vendor_state"], [SourceColumnName = "vendor_province", DestinationColumnName = "vendor_province"], [SourceColumnName = "vendor_zip_code", DestinationColumnName = "vendor_zip_code"], [SourceColumnName = "vendor_timezone", DestinationColumnName = "vendor_timezone"], [SourceColumnName = "customer_name", DestinationColumnName = "customer_name"], [SourceColumnName = "customer_company_id", DestinationColumnName = "customer_company_id"], [SourceColumnName = "odometer_miles", DestinationColumnName = "odometer_miles"], [SourceColumnName = "engine_hours", DestinationColumnName = "engine_hours"], [SourceColumnName = "priority_code", DestinationColumnName = "priority_code"], [SourceColumnName = "cost_center", DestinationColumnName = "cost_center"], [SourceColumnName = "tag", DestinationColumnName = "tag"], [SourceColumnName = "status", DestinationColumnName = "status"], [SourceColumnName = "created_by", DestinationColumnName = "created_by"], [SourceColumnName = "date_created", DestinationColumnName = "date_created"], [SourceColumnName = "date_started", DestinationColumnName = "date_started"], [SourceColumnName = "date_expected_finish", DestinationColumnName = "date_expected_finish"], [SourceColumnName = "date_finished", DestinationColumnName = "date_finished"], [SourceColumnName = "date_invoiced", DestinationColumnName = "date_invoiced"], [SourceColumnName = "date_invoice_paid", DestinationColumnName = "date_invoice_paid"], [SourceColumnName = "po_number", DestinationColumnName = "po_number"], [SourceColumnName = "additional_charges", DestinationColumnName = "additional_charges"], [SourceColumnName = "tax_total", DestinationColumnName = "tax_total"], [SourceColumnName = "credit_amount", DestinationColumnName = "credit_amount"], [SourceColumnName = "estimate", DestinationColumnName = "estimate"], [SourceColumnName = "grand_total", DestinationColumnName = "grand_total"], [SourceColumnName = "paid_amount", DestinationColumnName = "paid_amount"], [SourceColumnName = "remit_to", DestinationColumnName = "remit_to"], [SourceColumnName = "remit_to_company_id", DestinationColumnName = "remit_to_company_id"], [SourceColumnName = "tasks_task_id", DestinationColumnName = "tasks_task_id"], [SourceColumnName = "tasks_labor_hourly_rate", DestinationColumnName = "tasks_labor_hourly_rate"], [SourceColumnName = "tasks_labor_hours", DestinationColumnName = "tasks_labor_hours"], [SourceColumnName = "tasks_labor_subtotal", DestinationColumnName = "tasks_labor_subtotal"], [SourceColumnName = "tasks_labor_tax_rate", DestinationColumnName = "tasks_labor_tax_rate"], [SourceColumnName = "tasks_labor_complaint", DestinationColumnName = "tasks_labor_complaint"], [SourceColumnName = "tasks_labor_cause_code", DestinationColumnName = "tasks_labor_cause_code"], [SourceColumnName = "tasks_labor_correction_code", DestinationColumnName = "tasks_labor_correction_code"], [SourceColumnName = "tasks_labor_system_code", DestinationColumnName = "tasks_labor_system_code"], [SourceColumnName = "tasks_labor_system_component_code", DestinationColumnName = "tasks_labor_system_component_code"], [SourceColumnName = "tasks_scheduled_maintenance_id", DestinationColumnName = "tasks_scheduled_maintenance_id"], [SourceColumnName = "tasks_issue_id", DestinationColumnName = "tasks_issue_id"], [SourceColumnName = "tasks_assigned_to", DestinationColumnName = "tasks_assigned_to"], [SourceColumnName = "tasks_date_added", DestinationColumnName = "tasks_date_added"], [SourceColumnName = "tasks_parts_task_part_id", DestinationColumnName = "tasks_parts_task_part_id"], [SourceColumnName = "tasks_parts_part_id", DestinationColumnName = "tasks_parts_part_id"], [SourceColumnName = "tasks_parts_part_number", DestinationColumnName = "tasks_parts_part_number"], [SourceColumnName = "tasks_parts_part_description", DestinationColumnName = "tasks_parts_part_description"], [SourceColumnName = "tasks_parts_part_system_code", DestinationColumnName = "tasks_parts_part_system_code"], [SourceColumnName = "tasks_parts_part_type", DestinationColumnName = "tasks_parts_part_type"], [SourceColumnName = "tasks_parts_part_price", DestinationColumnName = "tasks_parts_part_price"], [SourceColumnName = "tasks_parts_part_quantity", DestinationColumnName = "tasks_parts_part_quantity"], [SourceColumnName = "tasks_parts_part_tax_rate", DestinationColumnName = "tasks_parts_part_tax_rate"], [SourceColumnName = "tasks_parts_part_location", DestinationColumnName = "tasks_parts_part_location"], [SourceColumnName = "tasks_parts_tire_brand", DestinationColumnName = "tasks_parts_tire_brand"], [SourceColumnName = "tasks_parts_tire_product_line", DestinationColumnName = "tasks_parts_tire_product_line"], [SourceColumnName = "tasks_parts_tire_size", DestinationColumnName = "tasks_parts_tire_size"], [SourceColumnName = "tasks_parts_tire_type", DestinationColumnName = "tasks_parts_tire_type"], [SourceColumnName = "tasks_parts_date_added", DestinationColumnName = "tasks_parts_date_added"], [SourceColumnName = "notes_note_id", DestinationColumnName = "notes_note_id"], [SourceColumnName = "notes_note", DestinationColumnName = "notes_note"], [SourceColumnName = "notes_added_by", DestinationColumnName = "notes_added_by"], [SourceColumnName = "notes_date_added", DestinationColumnName = "notes_date_added"]}], DynamicSchema = false, UpdateMethod = [Kind = "Append"], TypeSettings = [Kind = "Table"]]]}]
shared Query = let
  Source = Json.Document(Web.Contents("https://www.fleetrock.com/API/GetRO?username=paragon&token=c70314d6-e0f4-44cc-810a-1f39476023ed&event=created&start=01-01-2023&end=02-28-2023")),
  Navigation = Source[repair_orders],
  #"Converted to table" = Table.FromList(Navigation, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
  #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to table", "Column1", {"id", "group", "ro_group_hierarchy", "vin", "unit_number", "unit_type", "custom_asset_id", "vendor_name", "vendor_company_id", "vendor_city", "vendor_state", "vendor_province", "vendor_zip_code", "vendor_timezone", "customer_name", "customer_company_id", "odometer_miles", "engine_hours", "priority_code", "cost_center", "tag", "status", "created_by", "date_created", "date_started", "date_expected_finish", "date_finished", "date_invoiced", "date_invoice_paid", "po_number", "additional_charges", "tax_total", "credit_amount", "estimate", "grand_total", "paid_amount", "remit_to", "remit_to_company_id", "tasks", "notes"}, {"id", "group", "ro_group_hierarchy", "vin", "unit_number", "unit_type", "custom_asset_id", "vendor_name", "vendor_company_id", "vendor_city", "vendor_state", "vendor_province", "vendor_zip_code", "vendor_timezone", "customer_name", "customer_company_id", "odometer_miles", "engine_hours", "priority_code", "cost_center", "tag", "status", "created_by", "date_created", "date_started", "date_expected_finish", "date_finished", "date_invoiced", "date_invoice_paid", "po_number", "additional_charges", "tax_total", "credit_amount", "estimate", "grand_total", "paid_amount", "remit_to", "remit_to_company_id", "tasks", "notes"}),
  #"Expanded tasks" = Table.ExpandListColumn(#"Expanded Column1", "tasks"),
  #"Expanded tasks 1" = Table.ExpandRecordColumn(#"Expanded tasks", "tasks", {"task_id", "labor_hourly_rate", "labor_hours", "labor_subtotal", "labor_tax_rate", "labor_complaint", "labor_cause_code", "labor_correction_code", "labor_system_code", "labor_system_component_code", "scheduled_maintenance_id", "issue_id", "assigned_to", "date_added", "parts"}, {"tasks.task_id", "tasks.labor_hourly_rate", "tasks.labor_hours", "tasks.labor_subtotal", "tasks.labor_tax_rate", "tasks.labor_complaint", "tasks.labor_cause_code", "tasks.labor_correction_code", "tasks.labor_system_code", "tasks.labor_system_component_code", "tasks.scheduled_maintenance_id", "tasks.issue_id", "tasks.assigned_to", "tasks.date_added", "tasks.parts"}),
  #"Expanded tasks.parts" = Table.ExpandListColumn(#"Expanded tasks 1", "tasks.parts"),
  #"Expanded tasks.parts 1" = Table.ExpandRecordColumn(#"Expanded tasks.parts", "tasks.parts", {"task_part_id", "part_id", "part_number", "part_description", "part_system_code", "part_type", "part_price", "part_quantity", "part_tax_rate", "part_location", "tire_brand", "tire_product_line", "tire_size", "tire_type", "date_added"}, {"tasks.parts.task_part_id", "tasks.parts.part_id", "tasks.parts.part_number", "tasks.parts.part_description", "tasks.parts.part_system_code", "tasks.parts.part_type", "tasks.parts.part_price", "tasks.parts.part_quantity", "tasks.parts.part_tax_rate", "tasks.parts.part_location", "tasks.parts.tire_brand", "tasks.parts.tire_product_line", "tasks.parts.tire_size", "tasks.parts.tire_type", "tasks.parts.date_added"}),
  #"Expanded notes" = Table.ExpandListColumn(#"Expanded tasks.parts 1", "notes"),
  #"Expanded notes 1" = Table.ExpandRecordColumn(#"Expanded notes", "notes", {"note_id", "note", "added_by", "date_added"}, {"notes.note_id", "notes.note", "notes.added_by", "notes.date_added"}),
  #"Changed column type" = Table.TransformColumnTypes(#"Expanded notes 1", {{"id", Int64.Type}, {"odometer_miles", Int64.Type}, {"engine_hours", Int64.Type}}),
  #"Changed column type 1" = Table.TransformColumnTypes(#"Changed column type", {{"date_created", type datetime}, {"date_started", type datetime}, {"date_expected_finish", type datetime}, {"date_finished", type datetime}, {"date_invoiced", type datetime}, {"date_invoice_paid", type datetime}, {"additional_charges", type number}, {"tax_total", type number}, {"credit_amount", type number}, {"estimate", type number}, {"grand_total", type number}, {"paid_amount", type number}}),
  #"Renamed columns" = Table.RenameColumns(#"Changed column type 1", {{"tasks.task_id", "tasks_task_id"}, {"tasks.labor_hourly_rate", "tasks_labor_hourly_rate"}, {"tasks.labor_hours", "tasks_labor_hours"}, {"tasks.labor_subtotal", "tasks_labor_subtotal"}, {"tasks.labor_tax_rate", "tasks_labor_tax_rate"}}),
  #"Changed column type 2" = Table.TransformColumnTypes(#"Renamed columns", {{"tasks_labor_hourly_rate", type number}, {"tasks_labor_hours", type number}, {"tasks_labor_subtotal", type number}, {"tasks_labor_tax_rate", type number}}),
  #"Renamed columns 1" = Table.RenameColumns(#"Changed column type 2", {{"tasks.labor_complaint", "tasks_labor_complaint"}, {"tasks.labor_cause_code", "tasks_labor_cause_code"}, {"tasks.labor_correction_code", "tasks_labor_correction_code"}, {"tasks.labor_system_code", "tasks_labor_system_code"}, {"tasks.labor_system_component_code", "tasks_labor_system_component_code"}, {"tasks.scheduled_maintenance_id", "tasks_scheduled_maintenance_id"}, {"tasks.issue_id", "tasks_issue_id"}, {"tasks.assigned_to", "tasks_assigned_to"}, {"tasks.date_added", "tasks_date_added"}}),
  #"Changed column type 3" = Table.TransformColumnTypes(#"Renamed columns 1", {{"tasks_date_added", type datetime}}),
  #"Renamed columns 2" = Table.RenameColumns(#"Changed column type 3", {{"tasks.parts.task_part_id", "tasks_parts.task_part_id"}, {"tasks.parts.part_id", "tasks_parts_part_id"}, {"tasks.parts.part_number", "tasks_parts_part_number"}, {"tasks.parts.part_description", "tasks_parts_part_description"}, {"tasks.parts.part_system_code", "tasks_parts_part_system_code"}, {"tasks.parts.part_type", "tasks_parts_part_type"}, {"tasks.parts.part_price", "tasks_parts_part_price"}}),
  #"Changed column type 4" = Table.TransformColumnTypes(#"Renamed columns 2", {{"tasks_parts_part_price", type number}}),
  #"Renamed columns 3" = Table.RenameColumns(#"Changed column type 4", {{"tasks.parts.part_quantity", "tasks_parts_part_quantity"}}),
  #"Changed column type 5" = Table.TransformColumnTypes(#"Renamed columns 3", {{"tasks_parts_part_quantity", Int64.Type}, {"tasks.parts.part_tax_rate", type number}}),
  #"Renamed columns 4" = Table.RenameColumns(#"Changed column type 5", {{"tasks.parts.part_tax_rate", "tasks_parts_part_tax_rate"}, {"tasks.parts.part_location", "tasks_parts_part_location"}, {"tasks.parts.tire_brand", "tasks_parts_tire_brand"}, {"tasks.parts.tire_product_line", "tasks_parts_tire_product_line"}, {"tasks.parts.tire_size", "tasks_parts_tire_size"}, {"tasks.parts.tire_type", "tasks_parts_tire_type"}, {"tasks.parts.date_added", "tasks_parts_date_added"}}),
  #"Changed column type 6" = Table.TransformColumnTypes(#"Renamed columns 4", {{"tasks_parts_date_added", type datetime}}),
  #"Renamed columns 5" = Table.RenameColumns(#"Changed column type 6", {{"notes.note_id", "notes_note_id"}, {"notes.note", "notes_note"}}),
  #"Changed column type 7" = Table.TransformColumnTypes(#"Renamed columns 5", {{"group", type text}, {"ro_group_hierarchy", type text}, {"vin", type text}, {"unit_number", type text}, {"unit_type", type text}, {"custom_asset_id", type text}, {"vendor_name", type text}, {"vendor_company_id", type text}, {"vendor_city", type text}, {"vendor_state", type text}, {"vendor_province", type text}, {"vendor_zip_code", type text}, {"vendor_timezone", type text}, {"customer_name", type text}, {"customer_company_id", type text}, {"priority_code", type text}, {"cost_center", type text}, {"tag", type text}, {"status", type text}, {"created_by", type text}, {"po_number", type text}, {"remit_to", type text}, {"remit_to_company_id", type text}, {"tasks_task_id", Int64.Type}, {"tasks_labor_complaint", type text}, {"tasks_labor_cause_code", type text}, {"tasks_labor_correction_code", type text}, {"tasks_labor_system_code", type text}, {"tasks_labor_system_component_code", type text}, {"tasks_scheduled_maintenance_id", type text}, {"tasks_issue_id", Int64.Type}, {"tasks_assigned_to", type text}, {"tasks_parts.task_part_id", Int64.Type}}),
  #"Renamed columns 6" = Table.RenameColumns(#"Changed column type 7", {{"tasks_parts.task_part_id", "tasks_parts_task_part_id"}}),
  #"Changed column type 8" = Table.TransformColumnTypes(#"Renamed columns 6", {{"tasks_parts_part_id", Int64.Type}, {"tasks_parts_part_number", type text}, {"tasks_parts_part_description", type text}, {"tasks_parts_part_system_code", type text}, {"tasks_parts_part_type", type text}, {"tasks_parts_part_location", type text}, {"tasks_parts_tire_brand", type text}, {"tasks_parts_tire_product_line", type text}, {"tasks_parts_tire_size", type text}, {"tasks_parts_tire_type", type text}, {"notes_note_id", Int64.Type}, {"notes_note", type text}, {"notes.added_by", type text}, {"notes.date_added", type datetime}}),
  #"Renamed columns 7" = Table.RenameColumns(#"Changed column type 8", {{"notes.added_by", "notes_added_by"}, {"notes.date_added", "notes_date_added"}})
in
  #"Renamed columns 7";
shared Query_DataDestination = let
  Pattern = Lakehouse.Contents([CreateNavigationProperties = false]),
  Navigation_1 = Pattern{[workspaceId = "a6d2c31b-0b03-4c60-a258-c2664c56fe3d"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "f9a73da1-08e4-4f3d-a67f-74623bfde721"]}[Data],
  TableNavigation = Navigation_2{[Id = "flrk_repair_order_bronze", ItemKind = "Table"]}?[Data]?
in
  TableNavigation;
