table 'Miles Measure Sel'
	lineageTag: 984eec65-f2d0-447b-8df6-260fb1a713e7

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 90aa76ad-2dfa-4702-accf-4465d1cb4fa3
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Measure Name'
		dataType: string
		lineageTag: 02b8f042-7a6e-440f-b4e6-33c1497b253f
		summarizeBy: none
		sourceColumn: Measure Name

		annotation SummarizationSetBy = Automatic

	partition 'Miles Measure Sel' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUQrJL0nMUfDNzEktVorViVYyAor5ZOalKngkliKLGwPFXXMLSiqRxEyAYv4hQUgipkARl9SUzOTEktQUJHEzoHhQanpmfh6KZeYgy/KTUcQsQEoTM+FCsQA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ID = _t, #"Measure Name" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ID", Int64.Type}, {"Measure Name", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

