CREATE TABLE [dbo].[ibmi_cities_silver] (

	[State] varchar(8000) NULL, 
	[City] varchar(8000) NULL, 
	[Record Number] int NULL, 
	[Country] varchar(8000) NULL, 
	[Latitude NS Direction] varchar(8000) NULL, 
	[Longitude EW Direction] varchar(8000) NULL, 
	[Commerical Zone] varchar(8000) NULL, 
	[County Code] int NULL, 
	[BEA Code] int NULL, 
	[GU Code] int NULL, 
	[SMSA Code] int NULL, 
	[City Zip Prefix] varchar(8000) NULL, 
	[City Zip Suffix] varchar(8000) NULL, 
	[SPLC Code] int NULL, 
	[Area Code] varchar(8000) NULL, 
	[Territory Code] varchar(8000) NULL, 
	[City Timezone] int NULL, 
	[City Same State Twice] varchar(8000) NULL, 
	[Half Zone] varchar(8000) NULL, 
	[City Daylight Savings] varchar(8000) NULL, 
	[House Hold Movers] varchar(8000) NULL, 
	[Big City Code] varchar(8000) NULL, 
	[Duplicate City In State] varchar(8000) NULL, 
	[Near City Code] varchar(8000) NULL, 
	[Direction From Near City] int NULL, 
	[Distance Near City] int NULL, 
	[City in Two Counties] varchar(8000) NULL, 
	[City Other County] int NULL, 
	[City Size Code] varchar(8000) NULL, 
	[City Level Code] int NULL, 
	[Is Population Est] varchar(8000) NULL, 
	[City Population] int NULL, 
	[cityName] varchar(8000) NULL, 
	[cityShortName] varchar(8000) NULL, 
	[cityLatitude] int NULL, 
	[cityLongitude] int NULL, 
	[lastUpdate] int NULL, 
	[lastUpdateTime] int NULL, 
	[lastUpdateInitals] varchar(8000) NULL, 
	[cityCO1Zone] int NULL, 
	[cityCO1Term] int NULL, 
	[cityCO2Zone] int NULL, 
	[cityC02Term] int NULL, 
	[cityCountyQualified] varchar(8000) NULL, 
	[cityACountyAbbrev] varchar(8000) NULL
);