section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "flrk_repair_order_bronze_DataDestination", IsNewTarget = false], Settings = [Kind = "Manual", AllowCreation = false, ColumnSettings = [Mappings = {[SourceColumnName = "repair_order_id", DestinationColumnName = "repair_order_id"], [SourceColumnName = "ro_group", DestinationColumnName = "ro_group"], [SourceColumnName = "ro_group_hierarchy", DestinationColumnName = "ro_group_hierarchy"], [SourceColumnName = "ro_vin", DestinationColumnName = "ro_vin"], [SourceColumnName = "ro_unit_number", DestinationColumnName = "ro_unit_number"], [SourceColumnName = "ro_unit_type", DestinationColumnName = "ro_unit_type"], [SourceColumnName = "ro_custom_asset_id", DestinationColumnName = "ro_custom_asset_id"], [SourceColumnName = "ro_vendor_name", DestinationColumnName = "ro_vendor_name"], [SourceColumnName = "ro_vendor_company_id", DestinationColumnName = "ro_vendor_company_id"], [SourceColumnName = "ro_vendor_city", DestinationColumnName = "ro_vendor_city"], [SourceColumnName = "ro_vendor_state", DestinationColumnName = "ro_vendor_state"], [SourceColumnName = "ro_vendor_province", DestinationColumnName = "ro_vendor_province"], [SourceColumnName = "ro_vendor_zip_code", DestinationColumnName = "ro_vendor_zip_code"], [SourceColumnName = "ro_vendor_timezone", DestinationColumnName = "ro_vendor_timezone"], [SourceColumnName = "ro_customer_name", DestinationColumnName = "ro_customer_name"], [SourceColumnName = "ro_customer_company_id", DestinationColumnName = "ro_customer_company_id"], [SourceColumnName = "ro_odometer_miles", DestinationColumnName = "ro_odometer_miles"], [SourceColumnName = "ro_engine_hours", DestinationColumnName = "ro_engine_hours"], [SourceColumnName = "ro_priority_code", DestinationColumnName = "ro_priority_code"], [SourceColumnName = "ro_cost_center", DestinationColumnName = "ro_cost_center"], [SourceColumnName = "ro_tag", DestinationColumnName = "ro_tag"], [SourceColumnName = "ro_status", DestinationColumnName = "ro_status"], [SourceColumnName = "ro_created_by", DestinationColumnName = "ro_created_by"], [SourceColumnName = "ro_created_datetime", DestinationColumnName = "ro_created_datetime"], [SourceColumnName = "ro_started_datetime", DestinationColumnName = "ro_started_datetime"], [SourceColumnName = "ro_expected_finish_datetime", DestinationColumnName = "ro_expected_finish_datetime"], [SourceColumnName = "ro_finished_datetime", DestinationColumnName = "ro_finished_datetime"], [SourceColumnName = "ro_invoiced_datetime", DestinationColumnName = "ro_invoiced_datetime"], [SourceColumnName = "ro_invoice_paid_datetime", DestinationColumnName = "ro_invoice_paid_datetime"], [SourceColumnName = "ro_po_number", DestinationColumnName = "ro_po_number"], [SourceColumnName = "ro_additional_charges", DestinationColumnName = "ro_additional_charges"], [SourceColumnName = "ro_tax_total", DestinationColumnName = "ro_tax_total"], [SourceColumnName = "ro_credit_amount", DestinationColumnName = "ro_credit_amount"], [SourceColumnName = "ro_estimate", DestinationColumnName = "ro_estimate"], [SourceColumnName = "ro_grand_total", DestinationColumnName = "ro_grand_total"], [SourceColumnName = "ro_paid_amount", DestinationColumnName = "ro_paid_amount"], [SourceColumnName = "ro_remit_to", DestinationColumnName = "ro_remit_to"], [SourceColumnName = "ro_remit_to_company_id", DestinationColumnName = "ro_remit_to_company_id"]}], DynamicSchema = false, UpdateMethod = [Kind = "Append"], TypeSettings = [Kind = "Table"]]]}]
shared flrk_repair_order_bronze = let
  Source = Lakehouse.Contents(null){[workspaceId = "a6d2c31b-0b03-4c60-a258-c2664c56fe3d"]}[Data]{[lakehouseId = "f9a73da1-08e4-4f3d-a67f-74623bfde721"]}[Data],
  #"Navigation 1" = Source{[Id = "flrk_repair_order_bronze", ItemKind = "Table"]}[Data],
  #"Changed column type" = Table.TransformColumnTypes(#"Navigation 1", {{"id", Int64.Type}, {"odometer_miles", Int64.Type}, {"engine_hours", Int64.Type}, {"date_created", type datetime}, {"date_started", type datetime}, {"date_expected_finish", type datetime}, {"date_finished", type datetime}, {"date_invoiced", type datetime}, {"date_invoice_paid", type datetime}, {"additional_charges", type number}, {"tax_total", type number}, {"credit_amount", type number}, {"repair_orders.estimate", type number}, {"grand_total", type number}, {"paid_amount", type number}}),
  #"Removed columns" = Table.RemoveColumns(#"Changed column type", {"tasks.task_id", "tasks.labor_hourly_rate", "tasks.labor_hours", "tasks.labor_subtotal", "tasks.labor_tax_rate", "tasks.labor_complaint", "tasks.labor_cause_code", "tasks.labor_correction_code", "tasks.labor_system_code", "tasks.labor_system_component_code", "tasks.scheduled_maintenance_id", "tasks.issue_id", "tasks.assigned_to", "tasks.date_added", "notes.note_id", "notes.note", "notes.added_by", "notes.date_added", "tasks.parts.task_part_id", "tasks.parts.part_id", "tasks.parts.part_number", "tasks.parts.part_description", "tasks.parts.part_system_code", "tasks.parts.part_type", "tasks.parts.part_price", "tasks.parts.part_quantity", "tasks.parts.part_tax_rate", "tasks.parts.part_location", "tasks.parts.tire_brand", "tasks.parts.tire_product_line", "tasks.parts.tire_size", "tasks.parts.tire_type", "tasks.parts.date_added"}),
  #"Renamed columns" = Table.RenameColumns(#"Removed columns", {{"id", "repair_order_id"}}),
  #"Renamed columns 1" = Table.RenameColumns(#"Renamed columns", {{"date_created", "ro_created_datetime"}, {"created_by", "ro_created_by"}, {"date_started", "ro_started_datetime"}, {"date_expected_finish", "ro_expected_finish_datetime"}, {"date_finished", "ro_finished_datetime"}, {"date_invoiced", "ro_invoiced_datetime"}, {"date_invoice_paid", "ro_invoice_paid_datetime"}, {"group", "ro_group"}, {"vin", "ro_vin"}, {"unit_number", "ro_unit_number"}, {"unit_type", "ro_unit_type"}, {"custom_asset_id", "ro_custom_asset_id"}, {"vendor_name", "ro_vendor_name"}, {"vendor_company_id", "ro_vendor_company_id"}, {"vendor_city", "ro_vendor_city"}, {"vendor_state", "ro_vendor_state"}, {"vendor_province", "ro_vendor_province"}, {"vendor_zip_code", "ro_vendor_zip_code"}, {"vendor_timezone", "ro_vendor_timezone"}, {"customer_name", "ro_customer_name"}, {"customer_company_id", "ro_customer_company_id"}}),
  #"Renamed columns 2" = Table.RenameColumns(#"Renamed columns 1", {{"odometer_miles", "ro_odometer_miles"}, {"engine_hours", "ro_engine_hours"}, {"priority_code", "ro_priority_code"}, {"cost_center", "ro_cost_center"}, {"tag", "ro_tag"}, {"status", "ro_status"}, {"po_number", "ro_po_number"}, {"additional_charges", "ro_additional_charges"}, {"tax_total", "ro_tax_total"}, {"credit_amount", "ro_credit_amount"}, {"repair_orders.estimate", "ro_estimate"}, {"grand_total", "ro_grand_total"}, {"paid_amount", "ro_paid_amount"}, {"remit_to", "ro_remit_to"}, {"remit_to_company_id", "ro_remit_to_company_id"}}),
  #"Removed duplicates" = Table.Distinct(#"Renamed columns 2")
in
  #"Removed duplicates";
shared flrk_repair_order_bronze_DataDestination = let
  Pattern = Fabric.Warehouse([CreateNavigationProperties = false]),
  Navigation_1 = Pattern{[workspaceId = "a6d2c31b-0b03-4c60-a258-c2664c56fe3d"]}[Data],
  Navigation_2 = Navigation_1{[warehouseId = "f8578495-391e-4e7e-b791-4949397ba86f"]}[Data],
  TableNavigation = Navigation_2{[Schema = "silver", Item = "flrk_repair_order"]}[Data]
in
  TableNavigation;
