section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "VW_INCR_ORDER_DataDestination", IsNewTarget = false], Settings = [Kind = "Manual", AllowCreation = false, ColumnSettings = [Mappings = {[SourceColumnName = "ORARA", DestinationColumnName = "ORARA"], [SourceColumnName = "ORODR", DestinationColumnName = "ORODR"], [SourceColumnName = "ORSTAT", DestinationColumnName = "ORSTAT"], [SourceColumnName = "ORDATE", DestinationColumnName = "ORDATE"], [SourceColumnName = "ORTIME", DestinationColumnName = "ORTIME"], [SourceColumnName = "ORCUST", DestinationColumnName = "ORCUST"], [SourceColumnName = "ORCONS", DestinationColumnName = "ORCONS"], [SourceColumnName = "ORBILL", DestinationColumnName = "ORBILL"], [SourceColumnName = "ORLDAT", DestinationColumnName = "ORLDAT"], [SourceColumnName = "ORPDAT", DestinationColumnName = "ORPDAT"], [SourceColumnName = "ORPTIM", DestinationColumnName = "ORPTIM"], [SourceColumnName = "ORRPIK", DestinationColumnName = "ORRPIK"], [SourceColumnName = "ORDDAT", DestinationColumnName = "ORDDAT"], [SourceColumnName = "ORDTIM", DestinationColumnName = "ORDTIM"], [SourceColumnName = "ORRDEL", DestinationColumnName = "ORRDEL"], [SourceColumnName = "ORCOMC", DestinationColumnName = "ORCOMC"], [SourceColumnName = "ORCOMD", DestinationColumnName = "ORCOMD"], [SourceColumnName = "ORINIT", DestinationColumnName = "ORINIT"], [SourceColumnName = "ORCAC", DestinationColumnName = "ORCAC"], [SourceColumnName = "ORCPHN", DestinationColumnName = "ORCPHN"], [SourceColumnName = "ORRAC", DestinationColumnName = "ORRAC"], [SourceColumnName = "ORRPHN", DestinationColumnName = "ORRPHN"], [SourceColumnName = "ORCTIM", DestinationColumnName = "ORCTIM"], [SourceColumnName = "ORWGT", DestinationColumnName = "ORWGT"], [SourceColumnName = "ORTWGT", DestinationColumnName = "ORTWGT"], [SourceColumnName = "ORHOOK", DestinationColumnName = "ORHOOK"], [SourceColumnName = "ORRACK", DestinationColumnName = "ORRACK"], [SourceColumnName = "ORPLLT", DestinationColumnName = "ORPLLT"], [SourceColumnName = "OROCTY", DestinationColumnName = "OROCTY"], [SourceColumnName = "OROST", DestinationColumnName = "OROST"], [SourceColumnName = "OROBEA", DestinationColumnName = "OROBEA"], [SourceColumnName = "OROGU", DestinationColumnName = "OROGU"], [SourceColumnName = "OROSNM", DestinationColumnName = "OROSNM"], [SourceColumnName = "ORDCTY", DestinationColumnName = "ORDCTY"], [SourceColumnName = "ORDST", DestinationColumnName = "ORDST"], [SourceColumnName = "ORDBEA", DestinationColumnName = "ORDBEA"], [SourceColumnName = "ORDGU", DestinationColumnName = "ORDGU"], [SourceColumnName = "ORDSNM", DestinationColumnName = "ORDSNM"], [SourceColumnName = "ORMILE", DestinationColumnName = "ORMILE"], [SourceColumnName = "ORLDMI", DestinationColumnName = "ORLDMI"], [SourceColumnName = "OREMIL", DestinationColumnName = "OREMIL"], [SourceColumnName = "ORRST", DestinationColumnName = "ORRST"], [SourceColumnName = "ORSTP", DestinationColumnName = "ORSTP"], [SourceColumnName = "ORLD", DestinationColumnName = "ORLD"], [SourceColumnName = "ORPDRV", DestinationColumnName = "ORPDRV"], [SourceColumnName = "OR_DSP", DestinationColumnName = "OR_DSP"], [SourceColumnName = "ORDSP", DestinationColumnName = "ORDSP"], [SourceColumnName = "ORTRLR", DestinationColumnName = "ORTRLR"], [SourceColumnName = "ORESTR", DestinationColumnName = "ORESTR"], [SourceColumnName = "ORNWPK", DestinationColumnName = "ORNWPK"], [SourceColumnName = "ORINAR", DestinationColumnName = "ORINAR"], [SourceColumnName = "ORCSH", DestinationColumnName = "ORCSH"], [SourceColumnName = "ORCNS", DestinationColumnName = "ORCNS"], [SourceColumnName = "ORORBY", DestinationColumnName = "ORORBY"], [SourceColumnName = "ORLS", DestinationColumnName = "ORLS"], [SourceColumnName = "ORPIEC", DestinationColumnName = "ORPIEC"], [SourceColumnName = "ORPORC", DestinationColumnName = "ORPORC"], [SourceColumnName = "ORMAN", DestinationColumnName = "ORMAN"], [SourceColumnName = "ORCUBE", DestinationColumnName = "ORCUBE"], [SourceColumnName = "ORSPEC", DestinationColumnName = "ORSPEC"], [SourceColumnName = "ORAPDT", DestinationColumnName = "ORAPDT"], [SourceColumnName = "ORAPTM", DestinationColumnName = "ORAPTM"], [SourceColumnName = "ORAPNM", DestinationColumnName = "ORAPNM"], [SourceColumnName = "ORAPIN", DestinationColumnName = "ORAPIN"], [SourceColumnName = "ORADDT", DestinationColumnName = "ORADDT"], [SourceColumnName = "ORADTM", DestinationColumnName = "ORADTM"], [SourceColumnName = "ORADNM", DestinationColumnName = "ORADNM"], [SourceColumnName = "ORADIN", DestinationColumnName = "ORADIN"], [SourceColumnName = "ORPREQ", DestinationColumnName = "ORPREQ"], [SourceColumnName = "ORARR", DestinationColumnName = "ORARR"], [SourceColumnName = "ORCPIC", DestinationColumnName = "ORCPIC"], [SourceColumnName = "ORCWGT", DestinationColumnName = "ORCWGT"], [SourceColumnName = "ORSHDT", DestinationColumnName = "ORSHDT"], [SourceColumnName = "ORSHTM", DestinationColumnName = "ORSHTM"], [SourceColumnName = "ORTMPH", DestinationColumnName = "ORTMPH"], [SourceColumnName = "ORTMPL", DestinationColumnName = "ORTMPL"], [SourceColumnName = "OREQTY", DestinationColumnName = "OREQTY"], [SourceColumnName = "ORUPDD", DestinationColumnName = "ORUPDD"], [SourceColumnName = "ORUPDT", DestinationColumnName = "ORUPDT"], [SourceColumnName = "ORUPDI", DestinationColumnName = "ORUPDI"], [SourceColumnName = "ORCO", DestinationColumnName = "ORCO"], [SourceColumnName = "ORDV", DestinationColumnName = "ORDV"], [SourceColumnName = "ORTM", DestinationColumnName = "ORTM"], [SourceColumnName = "ORSEL1", DestinationColumnName = "ORSEL1"], [SourceColumnName = "ORSEL2", DestinationColumnName = "ORSEL2"], [SourceColumnName = "ORSERV", DestinationColumnName = "ORSERV"], [SourceColumnName = "ORCMTM", DestinationColumnName = "ORCMTM"], [SourceColumnName = "ORHAZM", DestinationColumnName = "ORHAZM"], [SourceColumnName = "OREDI", DestinationColumnName = "OREDI"], [SourceColumnName = "OREDIC", DestinationColumnName = "OREDIC"], [SourceColumnName = "ORDLD", DestinationColumnName = "ORDLD"], [SourceColumnName = "ORDULD", DestinationColumnName = "ORDULD"], [SourceColumnName = "ORSDR", DestinationColumnName = "ORSDR"], [SourceColumnName = "ORSDRR", DestinationColumnName = "ORSDRR"], [SourceColumnName = "OREDMB", DestinationColumnName = "OREDMB"], [SourceColumnName = "ORBBOC", DestinationColumnName = "ORBBOC"], [SourceColumnName = "ORJIT", DestinationColumnName = "ORJIT"], [SourceColumnName = "ORCDED", DestinationColumnName = "ORCDED"], [SourceColumnName = "ORAGNT", DestinationColumnName = "ORAGNT"], [SourceColumnName = "OREDFB", DestinationColumnName = "OREDFB"], [SourceColumnName = "OREDIO", DestinationColumnName = "OREDIO"], [SourceColumnName = "ORQUT", DestinationColumnName = "ORQUT"], [SourceColumnName = "OROPLM", DestinationColumnName = "OROPLM"], [SourceColumnName = "ORDPLM", DestinationColumnName = "ORDPLM"], [SourceColumnName = "ORCCTY", DestinationColumnName = "ORCCTY"], [SourceColumnName = "ORCST", DestinationColumnName = "ORCST"], [SourceColumnName = "ORLCDT", DestinationColumnName = "ORLCDT"], [SourceColumnName = "ORECDT", DestinationColumnName = "ORECDT"], [SourceColumnName = "ORRATO", DestinationColumnName = "ORRATO"], [SourceColumnName = "ORLDWG", DestinationColumnName = "ORLDWG"], [SourceColumnName = "ORLGT", DestinationColumnName = "ORLGT"], [SourceColumnName = "ORHGT", DestinationColumnName = "ORHGT"], [SourceColumnName = "ORWDT", DestinationColumnName = "ORWDT"], [SourceColumnName = "ORPMTF", DestinationColumnName = "ORPMTF"], [SourceColumnName = "ORPCOM", DestinationColumnName = "ORPCOM"], [SourceColumnName = "ORLAT", DestinationColumnName = "ORLAT"], [SourceColumnName = "ORLONG", DestinationColumnName = "ORLONG"], [SourceColumnName = "ORTEN", DestinationColumnName = "ORTEN"], [SourceColumnName = "ORHRS", DestinationColumnName = "ORHRS"], [SourceColumnName = "ORMIN", DestinationColumnName = "ORMIN"], [SourceColumnName = "OROZN", DestinationColumnName = "OROZN"], [SourceColumnName = "ORORG", DestinationColumnName = "ORORG"], [SourceColumnName = "ORDZN", DestinationColumnName = "ORDZN"], [SourceColumnName = "ORDRG", DestinationColumnName = "ORDRG"], [SourceColumnName = "ORTBRT", DestinationColumnName = "ORTBRT"], [SourceColumnName = "ORNZN", DestinationColumnName = "ORNZN"], [SourceColumnName = "ORNRG", DestinationColumnName = "ORNRG"], [SourceColumnName = "ORNBEA", DestinationColumnName = "ORNBEA"], [SourceColumnName = "ORNGU", DestinationColumnName = "ORNGU"], [SourceColumnName = "OREFM", DestinationColumnName = "OREFM"], [SourceColumnName = "ORCARF", DestinationColumnName = "ORCARF"], [SourceColumnName = "ORUTYP", DestinationColumnName = "ORUTYP"], [SourceColumnName = "ORTTYP", DestinationColumnName = "ORTTYP"], [SourceColumnName = "ORDTYP", DestinationColumnName = "ORDTYP"], [SourceColumnName = "ORHAZC", DestinationColumnName = "ORHAZC"], [SourceColumnName = "ORFIL", DestinationColumnName = "ORFIL"]}], DynamicSchema = false, UpdateMethod = [Kind = "Append"], TypeSettings = [Kind = "Table"]]]}]
shared VW_INCR_ORDER = let
  Source = DB2.Database("S10A3543.STEVENSTRANSPORT.COM:447", "S10A3543", [HierarchicalNavigation = true, Implementation = "Microsoft"]),
  #"Navigation 1" = Source{[Schema = "FABRIC"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Name = "VW_INCR_ORDER"]}[Data],
  #"Renamedcolumns" = Table.RenameColumns(#"Navigation 2", {{"ORODR#", "ORODR"}, {"ORSTP#", "ORSTP"}, {"ORLD#", "ORLD"}, {"OR#DSP", "OR_DSP"}, {"ORDSP#", "ORDSP"}, {"ORCSH#", "ORCSH"}, {"ORCNS#", "ORCNS"}, {"ORLS#", "ORLS"}, {"ORMAN#", "ORMAN"}, {"ORCO#", "ORCO"}, {"ORDV#", "ORDV"}, {"ORTM#", "ORTM"}, {"ORQUT#", "ORQUT"}}),
    AddRecordNumber = Table.AddIndexColumn(Renamedcolumns, "recordNumber", 1, 1, Int64.Type),
    AddLoadDate = Table.AddColumn(AddRecordNumber, "loadDate", each DateTime.LocalNow(), type datetime),
    AddRefreshDate = Table.AddColumn(AddLoadDate, "refreshDate", each Date.From(DateTime.LocalNow()), type date),
    AddSourceSystem = Table.AddColumn(AddRefreshDate, "sourceSystem", each "IBM", type text)

in
    AddSourceSystem;
shared VW_INCR_ORDER_DataDestination = let
  Pattern = Lakehouse.Contents([CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "a6d2c31b-0b03-4c60-a258-c2664c56fe3d"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "f9a73da1-08e4-4f3d-a67f-74623bfde721"]}[Data],
  TableNavigation = Navigation_2{[Id = "ibmi_incr_order_bronze", ItemKind = "Table"]}[Data]
in
  TableNavigation;
