section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "silver flrk_repair_order_DataDestination", IsNewTarget = false], Settings = [Kind = "Manual", AllowCreation = false, ColumnSettings = [Mappings = {[SourceColumnName = "repair_order_id", DestinationColumnName = "repair_order_id"], [SourceColumnName = "ro_group", DestinationColumnName = "ro_group"], [SourceColumnName = "ro_group_hierarchy", DestinationColumnName = "ro_group_hierarchy"], [SourceColumnName = "ro_vin", DestinationColumnName = "ro_vin"], [SourceColumnName = "ro_unit_number", DestinationColumnName = "ro_unit_number"], [SourceColumnName = "ro_unit_type", DestinationColumnName = "ro_unit_type"], [SourceColumnName = "ro_custom_asset_id", DestinationColumnName = "ro_custom_asset_id"], [SourceColumnName = "ro_vendor_name", DestinationColumnName = "ro_vendor_name"], [SourceColumnName = "ro_vendor_company_id", DestinationColumnName = "ro_vendor_company_id"], [SourceColumnName = "ro_vendor_city", DestinationColumnName = "ro_vendor_city"], [SourceColumnName = "ro_vendor_state", DestinationColumnName = "ro_vendor_state"], [SourceColumnName = "ro_vendor_zip_code", DestinationColumnName = "ro_vendor_zip_code"], [SourceColumnName = "ro_vendor_timezone", DestinationColumnName = "ro_vendor_timezone"], [SourceColumnName = "ro_customer_name", DestinationColumnName = "ro_customer_name"], [SourceColumnName = "ro_odometer_miles", DestinationColumnName = "ro_odometer_miles"], [SourceColumnName = "ro_engine_hours", DestinationColumnName = "ro_engine_hours"], [SourceColumnName = "ro_tag", DestinationColumnName = "ro_tag"], [SourceColumnName = "ro_status", DestinationColumnName = "ro_status"], [SourceColumnName = "ro_created_by", DestinationColumnName = "ro_created_by"], [SourceColumnName = "ro_created_datetime", DestinationColumnName = "ro_created_datetime"], [SourceColumnName = "ro_created_date", DestinationColumnName = "ro_created_date"], [SourceColumnName = "ro_started_datetime", DestinationColumnName = "ro_started_datetime"], [SourceColumnName = "ro_started_date", DestinationColumnName = "ro_started_date"], [SourceColumnName = "ro_expected_finish_datetime", DestinationColumnName = "ro_expected_finish_datetime"], [SourceColumnName = "ro_expected_finish_date", DestinationColumnName = "ro_expected_finish_date"], [SourceColumnName = "ro_finished_datetime", DestinationColumnName = "ro_finished_datetime"], [SourceColumnName = "ro_finished_date", DestinationColumnName = "ro_finished_date"], [SourceColumnName = "ro_invoiced_datetime", DestinationColumnName = "ro_invoiced_datetime"], [SourceColumnName = "ro_invoiced_date", DestinationColumnName = "ro_invoiced_date"], [SourceColumnName = "ro_invoice_paid_datetime", DestinationColumnName = "ro_invoice_paid_datetime"], [SourceColumnName = "ro_invoice_paid_date", DestinationColumnName = "ro_invoice_paid_date"], [SourceColumnName = "ro_po_number", DestinationColumnName = "ro_po_number"], [SourceColumnName = "ro_additional_charges", DestinationColumnName = "ro_additional_charges"], [SourceColumnName = "ro_tax_total", DestinationColumnName = "ro_tax_total"], [SourceColumnName = "ro_credit_amount", DestinationColumnName = "ro_credit_amount"], [SourceColumnName = "ro_estimate", DestinationColumnName = "ro_estimate"], [SourceColumnName = "ro_grand_total", DestinationColumnName = "ro_grand_total"], [SourceColumnName = "ro_paid_amount", DestinationColumnName = "ro_paid_amount"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared #"silver flrk_repair_order" = let
  Source = Fabric.Warehouse(null){[workspaceId = "a6d2c31b-0b03-4c60-a258-c2664c56fe3d"]}[Data]{[warehouseId = "f8578495-391e-4e7e-b791-4949397ba86f"]}[Data],
  #"Navigation 1" = Source{[Schema = "silver", Item = "flrk_repair_order"]}[Data],
  #"Removed columns" = Table.RemoveColumns(#"Navigation 1", {"ro_vendor_province", "ro_customer_company_id", "ro_priority_code", "ro_cost_center"}),
  #"Added custom" = Table.TransformColumnTypes(Table.AddColumn(#"Removed columns", "ro_created_date", each [ro_created_datetime]), {{"ro_created_date", type date}}),
  #"Reordered columns" = Table.ReorderColumns(#"Added custom", {"repair_order_id", "ro_group", "ro_group_hierarchy", "ro_vin", "ro_unit_number", "ro_unit_type", "ro_custom_asset_id", "ro_vendor_name", "ro_vendor_company_id", "ro_vendor_city", "ro_vendor_state", "ro_vendor_zip_code", "ro_vendor_timezone", "ro_customer_name", "ro_odometer_miles", "ro_engine_hours", "ro_tag", "ro_status", "ro_created_by", "ro_created_datetime", "ro_created_date", "ro_started_datetime", "ro_expected_finish_datetime", "ro_finished_datetime", "ro_invoiced_datetime", "ro_invoice_paid_datetime", "ro_po_number", "ro_additional_charges", "ro_tax_total", "ro_credit_amount", "ro_estimate", "ro_grand_total", "ro_paid_amount", "ro_remit_to", "ro_remit_to_company_id"}),
  #"Added custom 1" = Table.AddColumn(#"Reordered columns", "ro_started_date", each [ro_started_datetime]),
  #"Changed column type" = Table.TransformColumnTypes(#"Added custom 1", {{"ro_started_date", type date}}),
  #"Reordered columns 1" = Table.ReorderColumns(#"Changed column type", {"repair_order_id", "ro_group", "ro_group_hierarchy", "ro_vin", "ro_unit_number", "ro_unit_type", "ro_custom_asset_id", "ro_vendor_name", "ro_vendor_company_id", "ro_vendor_city", "ro_vendor_state", "ro_vendor_zip_code", "ro_vendor_timezone", "ro_customer_name", "ro_odometer_miles", "ro_engine_hours", "ro_tag", "ro_status", "ro_created_by", "ro_created_datetime", "ro_created_date", "ro_started_datetime", "ro_started_date", "ro_expected_finish_datetime", "ro_finished_datetime", "ro_invoiced_datetime", "ro_invoice_paid_datetime", "ro_po_number", "ro_additional_charges", "ro_tax_total", "ro_credit_amount", "ro_estimate", "ro_grand_total", "ro_paid_amount", "ro_remit_to", "ro_remit_to_company_id"}),
  #"Added custom 2" = Table.TransformColumnTypes(Table.AddColumn(#"Reordered columns 1", "ro_expected_finish_date", each [ro_expected_finish_datetime]), {{"ro_expected_finish_date", type date}}),
  #"Reordered columns 2" = Table.ReorderColumns(#"Added custom 2", {"repair_order_id", "ro_group", "ro_group_hierarchy", "ro_vin", "ro_unit_number", "ro_unit_type", "ro_custom_asset_id", "ro_vendor_name", "ro_vendor_company_id", "ro_vendor_city", "ro_vendor_state", "ro_vendor_zip_code", "ro_vendor_timezone", "ro_customer_name", "ro_odometer_miles", "ro_engine_hours", "ro_tag", "ro_status", "ro_created_by", "ro_created_datetime", "ro_created_date", "ro_started_datetime", "ro_started_date", "ro_expected_finish_datetime", "ro_expected_finish_date", "ro_finished_datetime", "ro_invoiced_datetime", "ro_invoice_paid_datetime", "ro_po_number", "ro_additional_charges", "ro_tax_total", "ro_credit_amount", "ro_estimate", "ro_grand_total", "ro_paid_amount", "ro_remit_to", "ro_remit_to_company_id"}),
  #"Added custom 3" = Table.TransformColumnTypes(Table.AddColumn(#"Reordered columns 2", "ro_finished_date", each [ro_finished_datetime]), {{"ro_finished_date", type date}}),
  #"Reordered columns 3" = Table.ReorderColumns(#"Added custom 3", {"repair_order_id", "ro_group", "ro_group_hierarchy", "ro_vin", "ro_unit_number", "ro_unit_type", "ro_custom_asset_id", "ro_vendor_name", "ro_vendor_company_id", "ro_vendor_city", "ro_vendor_state", "ro_vendor_zip_code", "ro_vendor_timezone", "ro_customer_name", "ro_odometer_miles", "ro_engine_hours", "ro_tag", "ro_status", "ro_created_by", "ro_created_datetime", "ro_created_date", "ro_started_datetime", "ro_started_date", "ro_expected_finish_datetime", "ro_expected_finish_date", "ro_finished_datetime", "ro_finished_date", "ro_invoiced_datetime", "ro_invoice_paid_datetime", "ro_po_number", "ro_additional_charges", "ro_tax_total", "ro_credit_amount", "ro_estimate", "ro_grand_total", "ro_paid_amount", "ro_remit_to", "ro_remit_to_company_id"}),
  #"Added custom 4" = Table.AddColumn(#"Reordered columns 3", "ro_invoiced_date", each [ro_invoiced_datetime]),
  #"Changed column type 1" = Table.TransformColumnTypes(#"Added custom 4", {{"ro_invoiced_date", type date}}),
  #"Reordered columns 4" = Table.ReorderColumns(#"Changed column type 1", {"repair_order_id", "ro_group", "ro_group_hierarchy", "ro_vin", "ro_unit_number", "ro_unit_type", "ro_custom_asset_id", "ro_vendor_name", "ro_vendor_company_id", "ro_vendor_city", "ro_vendor_state", "ro_vendor_zip_code", "ro_vendor_timezone", "ro_customer_name", "ro_odometer_miles", "ro_engine_hours", "ro_tag", "ro_status", "ro_created_by", "ro_created_datetime", "ro_created_date", "ro_started_datetime", "ro_started_date", "ro_expected_finish_datetime", "ro_expected_finish_date", "ro_finished_datetime", "ro_finished_date", "ro_invoiced_datetime", "ro_invoiced_date", "ro_invoice_paid_datetime", "ro_po_number", "ro_additional_charges", "ro_tax_total", "ro_credit_amount", "ro_estimate", "ro_grand_total", "ro_paid_amount", "ro_remit_to", "ro_remit_to_company_id"}),
  #"Added custom 5" = Table.TransformColumnTypes(Table.AddColumn(#"Reordered columns 4", "ro_invoice_paid_date", each [ro_invoice_paid_datetime]), {{"ro_invoice_paid_date", type date}}),
  #"Reordered columns 5" = Table.ReorderColumns(#"Added custom 5", {"repair_order_id", "ro_group", "ro_group_hierarchy", "ro_vin", "ro_unit_number", "ro_unit_type", "ro_custom_asset_id", "ro_vendor_name", "ro_vendor_company_id", "ro_vendor_city", "ro_vendor_state", "ro_vendor_zip_code", "ro_vendor_timezone", "ro_customer_name", "ro_odometer_miles", "ro_engine_hours", "ro_tag", "ro_status", "ro_created_by", "ro_created_datetime", "ro_created_date", "ro_started_datetime", "ro_started_date", "ro_expected_finish_datetime", "ro_expected_finish_date", "ro_finished_datetime", "ro_finished_date", "ro_invoiced_datetime", "ro_invoiced_date", "ro_invoice_paid_datetime", "ro_invoice_paid_date", "ro_po_number", "ro_additional_charges", "ro_tax_total", "ro_credit_amount", "ro_estimate", "ro_grand_total", "ro_paid_amount", "ro_remit_to", "ro_remit_to_company_id"}),
  #"Removed columns 1" = Table.RemoveColumns(#"Reordered columns 5", {"ro_remit_to", "ro_remit_to_company_id"})
in
  #"Removed columns 1";
shared #"silver flrk_repair_order_DataDestination" = let
  Pattern = Fabric.Warehouse([HierarchicalNavigation = null, CreateNavigationProperties = false]),
  Navigation_1 = Pattern{[workspaceId = "a6d2c31b-0b03-4c60-a258-c2664c56fe3d"]}[Data],
  Navigation_2 = Navigation_1{[warehouseId = "f8578495-391e-4e7e-b791-4949397ba86f"]}[Data],
  TableNavigation = Navigation_2{[Schema = "gold", Item = "fact_maint_repair_order"]}[Data]
in
  TableNavigation;
