CREATE TABLE [silver].[ibmi_tlb_tlbinv] (

	[tlb_tlbinv_status_code] varchar(8000) NULL, 
	[tlb_tlbinv_carrier_code] varchar(8000) NULL, 
	[tlb_tlbinv_division_code] varchar(8000) NULL, 
	[tlb_tlbinv_load_number] varchar(8000) NULL, 
	[tlb_tlbinv_dispatch] varchar(8000) NULL, 
	[tlb_tlbinv_original_load_number] varchar(8000) NULL, 
	[tlb_tlbinv_original_dispatch] varchar(8000) NULL, 
	[tlb_tlbinv_carrier_invoice_number] varchar(8000) NULL, 
	[tlb_tlbinv_invoice_date] date NULL, 
	[tlb_tlbinv_due_date] date NULL, 
	[tlb_tlbinv_to_pay_date] date NULL, 
	[tlb_tlbinv_invoice_amount] decimal(18,2) NULL, 
	[tlb_tlbinv_reference] varchar(8000) NULL, 
	[tlb_tlbinv_fund_code] varchar(8000) NULL, 
	[tlb_tlbinv_check_number] int NULL, 
	[tlb_tlbinv_check_date] date NULL, 
	[tlb_tlbinv_check_amount] decimal(18,2) NULL, 
	[is_expensed] varchar(5) NOT NULL, 
	[is_voided] varchar(5) NOT NULL, 
	[tlb_tlbinv_expensed_month] varchar(8000) NULL, 
	[tlb_tlbinv_expensed_year] varchar(8000) NULL, 
	[tlb_tlbinv_voided_month] varchar(8000) NULL, 
	[tlb_tlbinv_voided_year] varchar(8000) NULL, 
	[tlb_tlbinv_paid_month] varchar(8000) NULL, 
	[tlb_tlbinv_paid_year] varchar(8000) NULL, 
	[tlb_tlbinv_create_user_code] varchar(8000) NULL, 
	[tlb_tlbinv_create_date] date NULL, 
	[tlb_tlbinv_create_time] time(0) NULL, 
	[tlb_tlbinv_maint_user_code] varchar(8000) NULL, 
	[tlb_tlbinv_maint_date] date NULL, 
	[tlb_tlbinv_maint_time] time(0) NULL
);