CREATE TABLE [silver].[ibmi_incr_invoice] (

	[loadNumber] varchar(20) NULL, 
	[dispatchNumber] varchar(10) NULL, 
	[divisionNumber] varchar(10) NULL, 
	[orderNumber] varchar(20) NULL, 
	[invoiceNumber] varchar(20) NULL, 
	[carrierCode] varchar(20) NULL, 
	[enteredUser] varchar(20) NULL, 
	[enteredDate] date NULL, 
	[enteredTime] time(0) NULL, 
	[modifiedUser] varchar(20) NULL, 
	[modifiedDate] date NULL, 
	[modifiedTime] time(0) NULL, 
	[bookMonth] varchar(2) NULL, 
	[bookYear] varchar(2) NULL, 
	[voidFlag] char(1) NULL, 
	[refNumber] varchar(50) NULL, 
	[checkNumber] varchar(50) NULL, 
	[checkDate] date NULL, 
	[checkAmount] decimal(18,2) NULL, 
	[invoiceDate] date NULL, 
	[updateDate] date NULL, 
	[paymentDate] date NULL, 
	[invoiceAmount] decimal(18,2) NULL, 
	[is_deleted] int NULL, 
	[loadDate] datetime2(6) NULL, 
	[refreshDate] date NULL, 
	[sourceSystem] varchar(10) NULL
);