CREATE TABLE [silver].[ibmi_service_exceptions] (

	[serv_exc_load_number] varchar(8000) NULL, 
	[serv_exc_sequence_number] bigint NULL, 
	[serv_exc_type] varchar(18) NOT NULL, 
	[serv_exc_dispatch] varchar(8000) NULL, 
	[serv_exc_order_status_code] varchar(8000) NULL, 
	[serv_exc_truck_number] varchar(8000) NULL, 
	[serv_exc_trailer_number] varchar(8000) NULL, 
	[serv_exc_seat_1_driver_code] varchar(8000) NULL, 
	[serv_exc_dm_code] varchar(8000) NULL, 
	[serv_exc_dmol_code] varchar(8000) NULL, 
	[serv_exc_csr_code] varchar(8000) NULL, 
	[serv_exc_stop_number] bigint NULL, 
	[is_customer_reportable] varchar(7) NOT NULL, 
	[has_csr_signoff] varchar(7) NOT NULL, 
	[has_dm_signoff] varchar(7) NOT NULL, 
	[is_customer_responsible] varchar(5) NOT NULL, 
	[is_shipper_responsible] varchar(5) NOT NULL, 
	[is_loadat_responsible] varchar(5) NOT NULL, 
	[is_consignee_responsible] varchar(5) NOT NULL, 
	[is_driver_responsible] varchar(5) NOT NULL, 
	[is_equipment_responsible] varchar(5) NOT NULL, 
	[is_weather_responsible] varchar(5) NOT NULL, 
	[is_sales_responsible] varchar(5) NOT NULL, 
	[is_csr_responsible] varchar(5) NOT NULL, 
	[is_planner_responsible] varchar(5) NOT NULL, 
	[is_dm_responsible] varchar(5) NOT NULL, 
	[is_brokerage_responsible] varchar(5) NOT NULL, 
	[serv_exc_occurance_date] date NULL, 
	[serv_exc_occurance_time] time(0) NULL, 
	[serv_exc_create_date] date NULL, 
	[serv_exc_create_time] time(0) NULL, 
	[serv_exc_create_user_code] varchar(8000) NULL, 
	[serv_exc_create_program_code] varchar(8000) NULL, 
	[serv_exc_last_update_date] date NULL, 
	[serv_exc_last_update_time] time(0) NULL, 
	[serv_exc_last_update_user_code] varchar(8000) NULL, 
	[is_no_charge] varchar(5) NOT NULL, 
	[is_rail_responsible] varchar(5) NOT NULL, 
	[has_planner_signoff] varchar(7) NOT NULL, 
	[serv_exc_planner_code] varchar(8000) NULL, 
	[serv_exc_severity] varchar(9) NOT NULL, 
	[serv_exc_appt_change_reason_code] varchar(8000) NULL, 
	[is_driver_reportable] varchar(7) NOT NULL, 
	[serv_exc_exception_status_code] varchar(8000) NULL, 
	[serv_exc_regional_manager_code] varchar(8000) NULL, 
	[is_road_condition_responsible] varchar(5) NOT NULL, 
	[serv_exc_region_code] varchar(8000) NULL
);