CREATE TABLE [silver].[ibmi_cd_ordbill] (

	[cd_ordbill_load_number] varchar(8000) NULL, 
	[cd_ordbill_sequence_number] varchar(8000) NULL, 
	[cd_ordbill_rate_clerk_initials] varchar(8000) NULL, 
	[cd_ordbill_invoice_number] varchar(8000) NULL, 
	[cd_ordbill_void_invoice_number] varchar(8000) NULL, 
	[cd_ordbill_billed_date] date NULL, 
	[cd_ordbill_load_bill_amount] decimal(7,2) NULL, 
	[cd_ordbill_load_total_amount] decimal(7,2) NULL, 
	[cd_ordbill_load_book_month] varchar(8000) NULL, 
	[cd_ordbill_load_book_year] varchar(8000) NULL, 
	[is_billing_flagged] varchar(7) NULL, 
	[cd_ordbill_ar_status_flag] varchar(8000) NULL, 
	[cd_ordbill_tariff_code] varchar(8000) NULL, 
	[cd_ordbill_item_code] varchar(8000) NULL, 
	[cd_ordbill_line_code] varchar(8000) NULL, 
	[cd_ordbill_rate_code] varchar(8000) NULL, 
	[cd_ordbill_billed_amount_linehaul] decimal(7,2) NULL, 
	[cd_ordbill_billed_amount_accessorial] decimal(7,2) NULL, 
	[cd_ordbill_total_amount_linehaul] decimal(7,2) NULL, 
	[cd_ordbill_total_amount_accessorial] decimal(7,2) NULL, 
	[cd_ordbill_load_fuel_surcharge_amount] decimal(7,2) NULL, 
	[cd_ordbill_total_fuel_surcharge_amount] decimal(7,2) NULL, 
	[cd_ordbill_audit_date] date NULL, 
	[cd_ordbill_audit_initials] varchar(8000) NULL, 
	[cd_ordbill_print_date] date NULL, 
	[cd_ordbill_cost_record_flag] varchar(8000) NULL
);