CREATE TABLE [silver].[ibmi_ordbill] (

	[ordbill_load_number] varchar(8000) NULL, 
	[ordbill_sequence_number] varchar(8000) NULL, 
	[ordbill_rate_clerk_initials] varchar(8000) NULL, 
	[ordbill_invoice_number] varchar(8000) NULL, 
	[ordbill_void_invoice_number] varchar(8000) NULL, 
	[ordbill_billed_date] date NULL, 
	[ordbill_load_bill_amount] decimal(7,2) NULL, 
	[ordbill_load_total_amount] decimal(7,2) NULL, 
	[ordbill_load_book_month] varchar(8000) NULL, 
	[ordbill_load_book_year] varchar(8000) NULL, 
	[is_billing_flagged] varchar(7) NULL, 
	[ordbill_ar_status_flag] varchar(8000) NULL, 
	[ordbill_tariff_code] varchar(8000) NULL, 
	[ordbill_item_code] varchar(8000) NULL, 
	[ordbill_line_code] varchar(8000) NULL, 
	[ordbill_rate_code] varchar(8000) NULL, 
	[ordbill_billed_amount_linehaul] decimal(7,2) NULL, 
	[ordbill_billed_amount_accessorial] decimal(7,2) NULL, 
	[ordbill_total_amount_linehaul] decimal(7,2) NULL, 
	[ordbill_total_amount_accessorial] decimal(7,2) NULL, 
	[ordbill_load_fuel_surcharge_amount] decimal(7,2) NULL, 
	[ordbill_total_fuel_surcharge_amount] decimal(7,2) NULL, 
	[ordbill_audit_date] date NULL, 
	[ordbill_audit_initials] varchar(8000) NULL, 
	[ordbill_print_date] date NULL, 
	[ordbill_cost_record_flag] varchar(8000) NULL
);