CREATE TABLE [silver].[ibmi_paid_load] (

	[paid_loads_paid_date] date NULL, 
	[paid_loads_load_number] varchar(8000) NULL, 
	[paid_loads_customer_name] varchar(8000) NULL, 
	[paid_loads_dead_head_origin_city_name] varchar(8000) NULL, 
	[paid_loads_dead_head_origin_state] varchar(8000) NULL, 
	[paid_loads_origin_city_name] varchar(8000) NULL, 
	[paid_loads_origin_state] varchar(8000) NULL, 
	[paid_loads_destination_city_name] varchar(8000) NULL, 
	[paid_loads_destination_state] varchar(8000) NULL, 
	[paid_loads_pickup_date] date NULL, 
	[paid_loads_delivery_date] date NULL, 
	[paid_loads_miles_dead_head] decimal(5,0) NULL, 
	[paid_loads_miles_loaded] decimal(5,0) NULL, 
	[paid_loads_miles_total] decimal(5,0) NULL, 
	[paid_loads_pallet_count] decimal(2,0) NULL, 
	[paid_loads_stop_count] varchar(8000) NULL, 
	[paid_loads_billed_total] decimal(8,2) NULL, 
	[paid_loads_billed_linehaul] decimal(8,2) NULL, 
	[paid_loads_billed_fuel_surcharge] decimal(8,2) NULL, 
	[paid_loads_billed_unloading] decimal(8,2) NULL, 
	[paid_loads_billed_pallet_charge] decimal(8,2) NULL, 
	[paid_loads_billed_other_charge] decimal(8,2) NULL, 
	[paid_loads_billed_mexico_charge] decimal(8,2) NULL, 
	[paid_loads_billed_stopoff_charge] decimal(8,2) NULL, 
	[paid_loads_billed_detention] decimal(8,2) NULL, 
	[paid_loads_billed_dead_head] decimal(8,2) NULL, 
	[paid_loads_unload_paid_to_driver] decimal(9,2) NULL, 
	[paid_loads_billed_tolls] decimal(9,2) NULL, 
	[paid_loads_mph] decimal(5,0) NULL, 
	[paid_loads_origin_area_code] varchar(8000) NULL, 
	[paid_loads_destination_area_code] varchar(8000) NULL, 
	[paid_loads_salesperson_code] varchar(8000) NULL, 
	[paid_loads_dm_code] varchar(8000) NULL, 
	[paid_loads_dmol_code] varchar(8000) NULL, 
	[paid_loads_truck_number] varchar(8000) NULL
);