CREATE TABLE [silver].[ibmi_unit] (

	[unit_truck_number] varchar(8000) NULL, 
	[unit_owner_code] varchar(8000) NULL, 
	[unit_truck_division_code] varchar(8000) NULL, 
	[unit_year] varchar(8000) NULL, 
	[unit_make] varchar(8000) NULL, 
	[unit_vin] varchar(8000) NULL, 
	[unit_base_license_plate] varchar(8000) NULL, 
	[unit_base_state] varchar(8000) NULL, 
	[unit_new_york_license] varchar(8000) NULL, 
	[unit_other] varchar(8000) NULL, 
	[unit_term_date] date NULL, 
	[unit_pay_type] varchar(8000) NULL, 
	[unit_hire_date] date NULL, 
	[unit_seat_1_driver_code] varchar(8000) NULL, 
	[unit_seat_2_driver_code] varchar(8000) NULL, 
	[unit_trailer_1_code] varchar(8000) NULL, 
	[unit_previous_seat_1_driver_code] varchar(8000) NULL, 
	[unit_previous_seat_2_driver_code] varchar(8000) NULL, 
	[unit_previous_trailer_1_code] varchar(8000) NULL, 
	[unit_status_code] varchar(8000) NULL, 
	[unit_current_load] varchar(8000) NULL, 
	[unit_current_dispatch] varchar(8000) NULL, 
	[unit_previous_load] varchar(8000) NULL, 
	[unit_previous_dispatch] varchar(8000) NULL, 
	[unit_destination_city_code] varchar(8000) NULL, 
	[unit_destination_state] varchar(8000) NULL, 
	[unit_destination_region_code] varchar(8000) NULL, 
	[unit_destination_bea_code] decimal(34,6) NULL, 
	[unit_destination_gu_code] varchar(8000) NULL, 
	[unit_destination_city_short_description] varchar(8000) NULL, 
	[unit_empty_weight] decimal(34,6) NULL, 
	[unit_gross_weight] decimal(34,6) NULL, 
	[unit_eta_date] date NULL, 
	[unit_eta_time] time(0) NULL, 
	[unit_eta_change_date] date NULL, 
	[unit_contact_date] date NULL, 
	[unit_contact_time] time(0) NULL, 
	[unit_contact_initials] varchar(8000) NULL, 
	[unit_contact_city_code] varchar(8000) NULL, 
	[unit_contact_state] varchar(8000) NULL, 
	[unit_contact_city_short_description] varchar(8000) NULL, 
	[has_message_flag] varchar(5) NOT NULL, 
	[is_truck_deleted] varchar(5) NOT NULL, 
	[unit_truck_type] varchar(8000) NULL, 
	[unit_axle_count] varchar(8000) NULL, 
	[unit_fleet_code] varchar(8000) NULL, 
	[unit_preplan_load] varchar(8000) NULL, 
	[is_preplan_committed] varchar(7) NOT NULL, 
	[unit_fuel_type_code] varchar(8000) NULL, 
	[has_avas_code] varchar(5) NOT NULL, 
	[unit_destination_area_code] varchar(8000) NULL, 
	[unit_lastest_hub_miles] decimal(34,6) NULL, 
	[unit_lastest_purchase_date] date NULL, 
	[unit_lastest_purchase_time] time(0) NULL, 
	[unit_first_purchase_date] date NULL, 
	[unit_first_purchase_time] time(0) NULL, 
	[UNPGAL] decimal(34,6) NULL, 
	[UNPMPG] decimal(34,6) NULL, 
	[unit_previous_hub_miles] decimal(34,6) NULL, 
	[unit_previous_purchase_date] bigint NULL, 
	[unit_previous_purchase_time] time(0) NULL, 
	[unit_latitude] decimal(34,6) NULL, 
	[unit_longitude] decimal(34,6) NULL, 
	[has_fleet_license] varchar(5) NOT NULL, 
	[unit_2_character_code] varchar(8000) NULL, 
	[unit_last_satalite_location] varchar(8000) NULL, 
	[unit_last_satalite_location_short_name] varchar(8000) NULL, 
	[unit_next_stop_short_name] varchar(8000) NULL, 
	[unit_proj_avail_time] time(0) NULL, 
	[unit_proj_avail_date] date NULL, 
	[unit_pta_change_date] date NULL, 
	[unit_dm_code] varchar(8000) NULL, 
	[unit_dmol_code] varchar(8000) NULL, 
	[is_customer_site_flagged] varchar(7) NOT NULL, 
	[unit_last_update_date] date NULL, 
	[unit_last_update_time] time(0) NULL, 
	[unit_last_update_initials] varchar(8000) NULL, 
	[is_city_truck] varchar(7) NOT NULL, 
	[unit_model_code] varchar(8000) NULL, 
	[unit_gate_check_location] varchar(8000) NULL, 
	[unit_dedicated_customer_code] varchar(8000) NULL, 
	[unit_subtype] varchar(8000) NULL, 
	[is_available_for_limited_dispatch] varchar(7) NOT NULL, 
	[unit_temp_hold_date] date NULL, 
	[unit_truck_sold_flag] varchar(8) NULL, 
	[has_jake] varchar(7) NOT NULL, 
	[has_cruise] varchar(7) NOT NULL, 
	[unit_speed_control] varchar(16) NULL, 
	[has_esp] varchar(7) NOT NULL, 
	[has_apu] varchar(7) NOT NULL, 
	[is_carbon_compliant] varchar(7) NOT NULL, 
	[has_team_gone_solo] varchar(5) NOT NULL
);