CREATE TABLE [silver].[ibmi_paypo] (

	[paypo_type_code] varchar(8000) NULL, 
	[is_deleted] varchar(5) NOT NULL, 
	[paypo_category] varchar(14) NOT NULL, 
	[paypo_description] varchar(8000) NULL, 
	[is_taxable] varchar(7) NOT NULL, 
	[paypo_gl_account_number] varchar(8000) NULL, 
	[paypo_normal_rate] decimal(34,6) NULL, 
	[paypo_max_amount] decimal(34,6) NULL, 
	[paypo_min_amount] decimal(34,6) NULL, 
	[can_override_limit] varchar(7) NOT NULL, 
	[is_split_for_teams] varchar(7) NOT NULL, 
	[paypo_creation_date] date NULL, 
	[paypo_creation_time] time(0) NULL, 
	[paypo_creation_initials] varchar(8000) NULL, 
	[paypo_last_update_date] date NULL, 
	[paypo_last_update_time] time(0) NULL, 
	[paypo_last_update_initials] varchar(8000) NULL, 
	[paypo_divisions] varchar(8000) NULL, 
	[paypo_max_limit_l2] decimal(34,6) NULL, 
	[paypo_max_limit_l3] decimal(34,6) NULL, 
	[paypo_pay_class_code] varchar(8000) NULL, 
	[paypo_pay_rate] varchar(8000) NULL, 
	[has_benefits_package] varchar(5) NOT NULL, 
	[paypo_deduction_type_code] varchar(8000) NULL, 
	[paypo_deduction_subtype_code] int NULL, 
	[paypo_pay_type] varchar(13) NOT NULL, 
	[paypo_credit_gl_account] varchar(8000) NULL, 
	[paypo_commodity_code] varchar(8000) NULL
);