CREATE TABLE [silver].[ibmi_utlfile] (

	[utlfile_truck_number] varchar(8000) NULL, 
	[utlfile_driver_code] varchar(8000) NULL, 
	[utlfile_driver_type] varchar(7) NOT NULL, 
	[utlfile_truck_dm_code] varchar(8000) NULL, 
	[utlfile_driver_dm_code] varchar(8000) NULL, 
	[utlfile_dmol_code] varchar(8000) NULL, 
	[utlfile_safety_manager_code] varchar(8000) NULL, 
	[utlfile_counselor_code] varchar(8000) NULL, 
	[utlfile_seat] varchar(8000) NULL, 
	[utlfile_first_seat_code] varchar(8000) NULL, 
	[utlfile_second_seat_code] varchar(8000) NULL, 
	[utlfile_training_level_code] varchar(8000) NULL, 
	[is_team_truck] varchar(5) NOT NULL, 
	[is_training_team] varchar(5) NOT NULL, 
	[utlfile_miles_hub] decimal(34,6) NULL, 
	[utlfile_miles_adj_hub] decimal(34,6) NULL, 
	[utlfile_miles_goal] decimal(34,6) NULL, 
	[utlfile_utilization_ratio] decimal(34,6) NULL, 
	[utlfile_projected_date_available] date NULL, 
	[utlfile_projected_time_available] varchar(8000) NULL, 
	[is_home_time] varchar(7) NOT NULL, 
	[utlfile_hold_codes] varchar(8000) NULL, 
	[utlfile_equipment_breakdown] varchar(8000) NULL, 
	[is_resweep] varchar(5) NOT NULL, 
	[utlfile_load_number] varchar(8000) NULL, 
	[is_grad_hold] varchar(7) NOT NULL, 
	[is_omitted] varchar(7) NOT NULL, 
	[utlfile_division] varchar(8000) NULL, 
	[utlfile_requested_days_out] decimal(34,6) NULL, 
	[is_trainer] varchar(7) NOT NULL, 
	[utlfile_trainer_availability_code] varchar(8000) NULL, 
	[utlfile_trainer_status_code] varchar(8000) NULL, 
	[is_allowed_to_drive] varchar(7) NOT NULL, 
	[utlfile_record_date] date NULL, 
	[utlfile_comfort_zone_code] varchar(8000) NULL, 
	[is_on_yard] varchar(7) NOT NULL, 
	[utlfile_business_unit_code] varchar(7) NOT NULL, 
	[utlfile_business_class] varchar(8000) NULL, 
	[utlfile_business_description] varchar(8000) NULL
);