CREATE TABLE [silver].[ibmi_arfile] (

	[arfile_record_code] varchar(8000) NULL, 
	[arfile_customer_code] varchar(8000) NULL, 
	[arfile_invoice_number] varchar(8000) NULL, 
	[arfile_adj_batch_code] varchar(8000) NULL, 
	[arfile_record_type] varchar(8000) NULL, 
	[arfile_record_number] decimal(34,6) NULL, 
	[arfile_invoice_date] date NULL, 
	[arfile_load_number] varchar(8000) NULL, 
	[arfile_deposit_date] date NULL, 
	[arfile_cust_order_number] varchar(8000) NULL, 
	[arfile_book_month] varchar(8000) NULL, 
	[arfile_book_year] varchar(8000) NULL, 
	[arfile_amount] decimal(34,6) NULL, 
	[arfile_balance_forward] decimal(34,6) NULL, 
	[is_daily_pro_register] varchar(5) NOT NULL, 
	[is_weekly_pro_register] varchar(5) NOT NULL, 
	[is_monthly_pro_register] varchar(5) NOT NULL, 
	[is_non_current] varchar(5) NOT NULL, 
	[arfile_customer_name] varchar(8000) NULL, 
	[arfile_sequence_code] varchar(8000) NULL, 
	[arfile_statement_number] varchar(8000) NULL, 
	[arfile_dispatch_date] date NULL
);