CREATE TABLE [silver].[ibmi_driver] (

	[drv_code] varchar(8000) NULL, 
	[drv_full_name] varchar(8000) NULL, 
	[drv_last_name] varchar(8000) NULL, 
	[drv_first_name] varchar(8000) NULL, 
	[drv_short_name] varchar(8000) NULL, 
	[drv_address_line_1] varchar(8000) NULL, 
	[drv_address_city] varchar(8000) NULL, 
	[drv_address_state] varchar(8000) NULL, 
	[drv_address_zip] varchar(8000) NULL, 
	[drv_address_zip_extn] varchar(8000) NULL, 
	[drv_area_code] varchar(30) NULL, 
	[drv_phone_number] varchar(30) NULL, 
	[drv_social_security] varchar(8000) NULL, 
	[drv_dm_code] varchar(8000) NULL, 
	[drv_dmol_code] varchar(8000) NULL, 
	[drv_create_date] date NULL, 
	[drv_create_time] time(0) NULL, 
	[drv_create_initial] varchar(8000) NULL, 
	[drv_update_date] date NULL, 
	[drv_update_time] time(0) NULL, 
	[drv_update_initial] varchar(8000) NULL, 
	[drv_school_code] varchar(8000) NULL, 
	[drv_birth_date] date NULL, 
	[drv_hire_date] date NULL, 
	[drv_review_date] date NULL, 
	[drv_termination_date] date NULL, 
	[drv_license_expiry_date] date NULL, 
	[drv_physical_expiry_date] date NULL, 
	[drv_license_number] varchar(184) NULL, 
	[drv_license_state] varchar(8000) NULL, 
	[drv_type] varchar(7) NOT NULL, 
	[drv_availability_code] varchar(8000) NULL, 
	[drv_previous_load_number] varchar(8000) NULL, 
	[drv_previous_dispatch] varchar(8000) NULL, 
	[drv_current_load_number] varchar(8000) NULL, 
	[drv_current_dispatch] varchar(8000) NULL, 
	[drv_assigned_truck] varchar(8000) NULL, 
	[drv_dispatch_city_code] varchar(8000) NULL, 
	[drv_dispatch_state] varchar(8000) NULL, 
	[drv_dispatch_st_city] varchar(8000) NOT NULL, 
	[has_drv_messages] varchar(5) NOT NULL, 
	[is_drv_deleted] varchar(5) NOT NULL, 
	[drv_emerg_contact_name] varchar(8000) NULL, 
	[drv_emerg_contact_phone] varchar(8000) NULL, 
	[drv_trainee_level_code] varchar(8000) NULL, 
	[drv_trainee_counselor_code] varchar(8000) NULL, 
	[drv_last_safety_talk_date] date NULL, 
	[drv_safety_talk_code] varchar(24) NULL, 
	[drv_home_city_code] varchar(48) NOT NULL, 
	[drv_voice_box] varchar(8000) NULL, 
	[is_jit_drv] varchar(7) NOT NULL, 
	[is_trainee_drv] varchar(8000) NULL, 
	[drv_adv_balance] decimal(34,6) NULL, 
	[drv_mailbox_pwd] decimal(34,6) NULL, 
	[drv_fuel_card] varchar(8000) NULL, 
	[drv_grad_date] date NULL, 
	[is_drv_smoker] varchar(7) NOT NULL, 
	[drv_race] varchar(8000) NULL, 
	[drv_gender] varchar(7) NOT NULL, 
	[has_hazmat_cert] varchar(7) NOT NULL, 
	[drv_hazmat_exp_date] date NULL, 
	[drv_cell_area_code] varchar(8000) NULL, 
	[drv_cell_number] varchar(8000) NULL, 
	[drv_grad_level_code] varchar(8000) NULL, 
	[drv_sr_cert_date] date NULL, 
	[drv_status_code] varchar(8000) NULL, 
	[drv_counselor_status_code] varchar(8000) NULL, 
	[is_canada_cert] varchar(7) NOT NULL, 
	[is_nyc_cert] varchar(7) NOT NULL
);