CREATE TABLE [silver].[ibmi_cd_ar_extension] (

	[cd_ar_ext_create_date] date NULL, 
	[cd_ar_ext_create_time] time(0) NULL, 
	[cd_ar_ext_customer_code] varchar(8000) NULL, 
	[cd_ar_ext_invoice_number] varchar(8000) NULL, 
	[cd_ar_ext_load_number] varchar(8000) NULL, 
	[cd_ar_ext_sequence_code] varchar(8000) NULL, 
	[cd_ar_ext_ar_code] varchar(8000) NULL, 
	[cd_ar_ext_record_type_code] varchar(8000) NULL, 
	[cd_ar_ext_record_number] decimal(34,6) NULL, 
	[cd_ar_ext_invoice_amount] decimal(34,6) NULL, 
	[cd_ar_ext_record_code] varchar(8000) NULL, 
	[cd_ar_ext_invoice_date] date NULL, 
	[cd_ar_ext_deposit_or_adjustment_date] date NULL, 
	[cd_ar_ext_bol] varchar(8000) NULL, 
	[cd_ar_ext_book_month] varchar(8000) NULL, 
	[cd_ar_ext_book_year] varchar(8000) NULL, 
	[cd_ar_ext_balance_forward_amount] decimal(34,6) NULL, 
	[cd_ar_ext_customer_name] varchar(8000) NULL, 
	[cd_ar_ext_statement_number] varchar(8000) NULL, 
	[cd_ar_ext_dispatch_date] date NULL, 
	[cd_ar_ext_create_user_code] varchar(8000) NULL, 
	[cd_ar_ext_create_program_code] varchar(8000) NULL, 
	[cd_ar_ext_last_change_date] date NULL, 
	[cd_ar_ext_last_change_time] time(0) NULL, 
	[cd_ar_ext_last_change_user_code] varchar(8000) NULL, 
	[cd_ar_ext_last_change_program_code] varchar(8000) NULL, 
	[cd_ar_ext_delete_date] date NULL, 
	[cd_ar_ext_delete_time] time(0) NULL, 
	[cd_ar_ext_delete_user_code] varchar(8000) NULL, 
	[cd_ar_ext_delete_program_code] varchar(8000) NULL
);