CREATE TABLE [silver].[plsc_driver_perf_slices] (

	[truck_id] varchar(20) NOT NULL, 
	[load_id] varchar(20) NOT NULL, 
	[primary_driver_id] varchar(20) NULL, 
	[co_driver_id] varchar(20) NULL, 
	[snapshot_type] varchar(20) NOT NULL, 
	[server_received_at] datetime2(3) NOT NULL, 
	[slice_start_utc] datetime2(3) NOT NULL, 
	[slice_end_utc] datetime2(3) NOT NULL, 
	[miles_driven] decimal(10,2) NULL, 
	[minutes_driving] decimal(10,2) NULL, 
	[minutes_idle_internal] decimal(10,2) NULL, 
	[minutes_idle_shutdown] decimal(10,2) NULL, 
	[minutes_idle_stopped] decimal(10,2) NULL, 
	[minutes_moving] decimal(10,2) NULL, 
	[fuel_move_gal] decimal(12,4) NULL, 
	[fuel_idle_gal] decimal(12,4) NULL, 
	[fuel_pto_gal] decimal(12,4) NULL, 
	[overspeed_events] int NULL, 
	[minutes_overspeed] decimal(10,2) NULL, 
	[minutes_high_rpm] decimal(10,2) NULL, 
	[avg_engine_load_pct] decimal(7,3) NULL, 
	[max_rpm] int NULL, 
	[max_speed_mph] int NULL, 
	[odometer_end_mi] decimal(12,3) NULL, 
	[trip_distance_mi] decimal(12,3) NULL, 
	[engine_hours_end] decimal(12,2) NULL, 
	[load_date] date NULL
);