CREATE TABLE [silver].[plsc_vehicle_health] (

	[vh_truck_raw] varchar(16) NULL, 
	[vh_hbid_raw] varchar(40) NULL, 
	[vh_type_raw] varchar(32) NULL, 
	[vh_recv_ts_raw] varchar(40) NULL, 
	[vh_logger_ts_raw] varchar(40) NULL, 
	[vh_speed_raw] varchar(16) NULL, 
	[vh_run_unit_raw] varchar(8) NULL, 
	[vh_run_dir_raw] varchar(8) NULL, 
	[vh_city_raw] varchar(64) NULL, 
	[vh_state_raw] varchar(8) NULL, 
	[vh_country_raw] varchar(8) NULL, 
	[vh_fuel_raw] varchar(32) NULL, 
	[vh_fuel_unit_raw] varchar(8) NULL, 
	[vh_lat_raw] varchar(32) NULL, 
	[vh_lon_raw] varchar(32) NULL, 
	[vh_loc_desc_raw] varchar(256) NULL, 
	[vh_rpd_raw] varchar(16) NULL, 
	[vh_engine_hrs_j_raw] varchar(32) NULL, 
	[vh_winm_raw] varchar(8) NULL, 
	[vh_acu_raw] varchar(16) NULL, 
	[vh_sat_raw] varchar(8) NULL, 
	[vh_gpsv_raw] varchar(8) NULL, 
	[vh_hdop_raw] varchar(8) NULL, 
	[vh_odo_raw] varchar(32) NULL, 
	[vh_odoj_raw] varchar(32) NULL, 
	[vh_heading_raw] varchar(16) NULL, 
	[vh_ign_raw] varchar(8) NULL, 
	[vh_rpm_raw] varchar(16) NULL, 
	[vh_engine_hrs_raw] varchar(32) NULL
);