CREATE TABLE [silver].[plsc_vehicle_heartbeats] (

	[plt_truck_id] varchar(20) NOT NULL, 
	[heartbeat_id] varchar(24) NOT NULL, 
	[msg_type] varchar(30) NULL, 
	[recv_utc_raw] varchar(40) NULL, 
	[log_utc_raw] varchar(40) NULL, 
	[speed_raw] varchar(20) NULL, 
	[distance_unit] varchar(5) NULL, 
	[heading_cardinal] varchar(8) NULL, 
	[city] varchar(60) NULL, 
	[state] varchar(3) NULL, 
	[country] varchar(3) NULL, 
	[fuel_instant] varchar(24) NULL, 
	[fuel_total] varchar(24) NULL, 
	[latitude_raw] varchar(24) NULL, 
	[longitude_raw] varchar(24) NULL, 
	[location_desc] varchar(120) NULL, 
	[road_grade_raw] varchar(24) NULL, 
	[eng_hrs_j1939] varchar(24) NULL, 
	[windows_mask] varchar(24) NULL, 
	[acu_raw] varchar(24) NULL, 
	[sat_count_raw] varchar(24) NULL, 
	[gps_fix_raw] varchar(24) NULL, 
	[hdop_raw] varchar(24) NULL, 
	[odometer_raw] varchar(24) NULL, 
	[odo_j1939_raw] varchar(24) NULL, 
	[heading_deg_raw] varchar(24) NULL, 
	[ignition_raw] varchar(5) NULL, 
	[rpm_raw] varchar(24) NULL, 
	[eng_hrs_total] varchar(24) NULL
);