CREATE TABLE [silver].[risk_claim_master] (

	[claim_mast_company_code] float NULL, 
	[claim_mast_record_code] float NULL, 
	[claim_mast_pre_claim_code] float NULL, 
	[claim_mast_type] varchar(24) NOT NULL, 
	[claim_mast_claim_number] varchar(8000) NULL, 
	[claim_mast_occurance_date] date NULL, 
	[claim_mast_occurance_time] time(0) NULL, 
	[claim_mast_occurance_datetime] datetime2(6) NULL, 
	[is_cargo_included] varchar(5) NOT NULL, 
	[claim_mast_reported_by_code] float NULL, 
	[claim_mast_claimant_company_code] int NULL, 
	[claim_mast_claimant_individual_code] int NULL, 
	[claim_mast_involved_driver_code] int NULL, 
	[claim_mast_claimant_customer_code] int NULL, 
	[claim_mast_wc_claimant_code] int NULL, 
	[claim_mast_witness_code] int NULL, 
	[claim_mast_create_date] date NULL, 
	[claim_mast_create_time] time(0) NULL, 
	[claim_mast_create_datetime] datetime2(6) NULL, 
	[claim_mast_create_user_code] varchar(8000) NULL, 
	[claim_mast_last_update_date] date NULL, 
	[claim_mast_last_update_time] time(0) NULL, 
	[claim_mast_last_update_datetime] datetime2(6) NULL, 
	[claim_mast_last_update_user_code] varchar(8000) NULL, 
	[claim_mast_misc_code] int NULL, 
	[claim_mast_coequipment_code] int NULL, 
	[claim_mast_truck_number] varchar(8000) NULL, 
	[claim_mast_trailer_number] varchar(8000) NULL, 
	[claim_mast_driver_home_code] varchar(8000) NULL, 
	[claim_mast_primary_adjuster_code] int NULL, 
	[claim_mast_current_status_code] int NULL, 
	[claim_mast_closing_date] date NULL, 
	[claim_mast_closing_time] time(0) NULL, 
	[claim_mast_closing_datetime] datetime2(6) NULL
);