CREATE TABLE [silver].[risk_company_master] (

	[company_mast_record_code] float NULL, 
	[company_mast_name] varchar(8000) NULL, 
	[company_mast_company_code] varchar(8000) NULL, 
	[company_mast_tax_id] varchar(8000) NULL, 
	[is_new_claims_to_register] varchar(7) NOT NULL, 
	[is_forced_date_reported] varchar(7) NOT NULL, 
	[is_forced_time_reported] varchar(7) NOT NULL, 
	[is_use_reserve_type_for_payments] varchar(7) NOT NULL, 
	[is_bonus_deduction_allowed] varchar(7) NOT NULL, 
	[company_mast_bonus_deduction_limit] int NULL, 
	[is_salary_deduction_allowed] varchar(7) NOT NULL, 
	[company_mast_salary_deduction_limit] int NULL, 
	[company_mast_allowed_deduction_at] varchar(8000) NULL, 
	[is_forced_salvage_to_reserve] varchar(7) NOT NULL, 
	[is_forced_salvage_to_equipment] varchar(7) NOT NULL, 
	[is_posted_recovery_to_gl] varchar(7) NOT NULL, 
	[company_mast_claim_mask] varchar(8000) NULL, 
	[is_claim_record_reset] varchar(7) NOT NULL, 
	[is_branch_specific_allowed] varchar(7) NOT NULL, 
	[is_closing_status_extended] varchar(7) NOT NULL, 
	[is_payment_on_closed_allowed] varchar(7) NOT NULL, 
	[company_mast_next_avail_claim_record] int NULL, 
	[company_mast_next_avail_pre_claim_record] int NULL, 
	[is_attached_adjustment_to_claimant] varchar(7) NOT NULL, 
	[company_mast_create_datetime] datetime2(6) NULL, 
	[company_mast_create_user_code] varchar(8000) NULL, 
	[company_mast_last_changed_datetime] datetime2(6) NULL, 
	[company_mast_last_changed_user_code] varchar(8000) NULL, 
	[company_mast_fund_code] float NULL, 
	[company_mast_claim_date_usage_code] varchar(8000) NULL, 
	[is_manual_claim_number] varchar(7) NOT NULL, 
	[has_company_specific_master_tables] varchar(7) NOT NULL, 
	[is_check_request_disabled] varchar(7) NOT NULL, 
	[company_mast_fiscal_year_start_date] datetime2(6) NULL, 
	[is_closed_claim_read_only] varchar(7) NOT NULL, 
	[is_excess_recovery_allowed] varchar(7) NOT NULL
);